Boomerang: FromSSAFormPass Class Reference
FromSSAFormPass Class Reference final
Transforms the statements a proc out of SSA form.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/passes/late/FromSSAFormPass.h>
Public Member Functions
bool execute (UserProc *proc) override
Run this pass, updating proc.
FromSSAFormPass ()
Public Member Functions inherited from IPass
const QString & getName () const
PassID getType () const
IPass (const QString &name, PassID type)
virtual bool isProcLocal () const
virtual ~IPass ()=default
Private Member Functions
void findPhiUnites (UserProc *proc, ConnectionGraph &pu)
Find the locations united by Phi-functions.
void insertCastsForStmt (Statement *stmt)
void mapParameters (UserProc *proc)
void mapRegistersToLocals (Statement *stmt)
map registers and temporaries to local variables
void nameParameterPhis (UserProc *proc)
Add a mapping for the destinations of phi functions that have one argument that is a parameter.
void removeSubscriptsFromParameters (UserProc *proc)
void removeSubscriptsFromSymbols (UserProc *proc)
Detailed Description
Transforms the statements a proc out of SSA form.
Definition at line 21 of file FromSSAFormPass.h.
Constructor & Destructor Documentation
FromSSAFormPass()
FromSSAFormPass::FromSSAFormPass ()
Definition at line 32 of file FromSSAFormPass.cpp.
References FromSSAForm.
Member Function Documentation
execute()
bool FromSSAFormPass::execute (UserProc * proc) override virtual
Run this pass, updating proc.
Returns
true iff any change
Implements IPass.
Definition at line 38 of file FromSSAFormPass.cpp.
References InterferenceFinder::findInterferences(), findPhiUnites(), insertCastsForStmt(), LocalAndParamMap, LOG_MSG, LOG_VERBOSE, LOG_WARN, mapParameters(), mapRegistersToLocals(), nameParameterPhis(), PhiAssign, removeSubscriptsFromParameters(), and removeSubscriptsFromSymbols().
findPhiUnites()
void FromSSAFormPass::findPhiUnites (UserProc * proc, ConnectionGraph & pu) private
Find the locations united by Phi-functions.
Definition at line 458 of file FromSSAFormPass.cpp.
References PhiAssign, and stmt.
Referenced by execute().
insertCastsForStmt()
void FromSSAFormPass::insertCastsForStmt (Statement * stmt) private
Definition at line 481 of file FromSSAFormPass.cpp.
References stmt.
Referenced by execute().
mapParameters()
void FromSSAFormPass::mapParameters (UserProc * proc) private
Definition at line 391 of file FromSSAFormPass.cpp.
References LOG_WARN.
Referenced by execute().
mapRegistersToLocals()
void FromSSAFormPass::mapRegistersToLocals (Statement * stmt) private
map registers and temporaries to local variables
Definition at line 494 of file FromSSAFormPass.cpp.
References stmt.
Referenced by execute().
nameParameterPhis()
void FromSSAFormPass::nameParameterPhis (UserProc * proc) private
Add a mapping for the destinations of phi functions that have one argument that is a parameter.
The idea here is to give a name to those SSA variables that have one and only one parameter amongst the phi arguments. For example, in test/source/param1, there is 18 v m[r28{-} + 8] := phi{- 7} with m[r28{-} + 8]{0} mapped to param1; insert a mapping for m[r28{-} + 8]{18} to param1. This will avoid a copy, and will use the name of the parameter only when it is acually used as a parameter.
Definition at line 344 of file FromSSAFormPass.cpp.
References PhiAssign.
Referenced by execute().
removeSubscriptsFromParameters()
void FromSSAFormPass::removeSubscriptsFromParameters (UserProc * proc) private
Definition at line 446 of file FromSSAFormPass.cpp.
Referenced by execute().
removeSubscriptsFromSymbols()
void FromSSAFormPass::removeSubscriptsFromSymbols (UserProc * proc) private
Definition at line 418 of file FromSSAFormPass.cpp.
Referenced by execute().
The documentation for this class was generated from the following files:
FromSSAFormPass.h
FromSSAFormPass.cpp