Boomerang: StmtRegMapper Class Reference
StmtRegMapper Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/stmtexpvisitor/StmtRegMapper.h>
Public Member Functions
virtual bool common (Assignment *stmt, bool &visitChildren)
StmtRegMapper (ExpRegMapper *erm)
virtual bool visit (Assign *stmt, bool &visitChildren) override
virtual bool visit (BoolAssign *stmt, bool &visitChildren) override
virtual bool visit (ImplicitAssign *stmt, bool &visitChildren) override
virtual bool visit (PhiAssign *stmt, bool &visitChildren) override
virtual ~StmtRegMapper ()=default
Detailed Description
Definition at line 23 of file StmtRegMapper.h.
Constructor & Destructor Documentation
StmtRegMapper()
StmtRegMapper::StmtRegMapper (ExpRegMapper * erm)
Definition at line 20 of file StmtRegMapper.cpp.
~StmtRegMapper()
virtual StmtRegMapper::~StmtRegMapper () virtual default
Member Function Documentation
common()
bool StmtRegMapper::common (Assignment * stmt, bool & visitChildren) virtual
Definition at line 26 of file StmtRegMapper.cpp.
References stmt.
Referenced by visit().
visit() [1/4]
bool StmtRegMapper::visit (Assign * stmt, bool & visitChildren) override virtual
Definition at line 38 of file StmtRegMapper.cpp.
References common(), and stmt.
visit() [2/4]
bool StmtRegMapper::visit (BoolAssign * stmt, bool & visitChildren) override virtual
Definition at line 56 of file StmtRegMapper.cpp.
References common(), and stmt.
visit() [3/4]
bool StmtRegMapper::visit (ImplicitAssign * stmt, bool & visitChildren) override virtual
Definition at line 50 of file StmtRegMapper.cpp.
References common(), and stmt.
visit() [4/4]
bool StmtRegMapper::visit (PhiAssign * stmt, bool & visitChildren) override virtual
Definition at line 44 of file StmtRegMapper.cpp.
References common(), and stmt.
The documentation for this class was generated from the following files:
StmtRegMapper.h
StmtRegMapper.cpp