Boomerang: UnusedReturnRemover Class Reference
UnusedReturnRemover Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/decomp/UnusedReturnRemover.h>
Public Member Functions
bool removeUnusedReturns ()
Remove unused return locations.
UnusedReturnRemover (Prog *prog)
Private Member Functions
bool removeUnusedParamsAndReturns (UserProc *proc)
Remove any returns that are not used by any callers.
void updateForUseChange (UserProc *proc)
Update parameters and call livenesses to take into account the changes caused by removing a return from this procedure, or a callee's parameter (which affects this procedure's arguments, which are also uses).
Private Attributes
Prog * m_prog
ProcSet m_removeRetSet
UserProcs that need their returns updated.
Detailed Description
Definition at line 24 of file UnusedReturnRemover.h.
Constructor & Destructor Documentation
UnusedReturnRemover()
UnusedReturnRemover::UnusedReturnRemover (Prog * prog) explicit
Definition at line 37 of file UnusedReturnRemover.cpp.
Member Function Documentation
removeUnusedParamsAndReturns()
bool UnusedReturnRemover::removeUnusedParamsAndReturns (UserProc * proc) private
Remove any returns that are not used by any callers.
Remove unused returns for this procedure, based on the equation: returns = modifieds isect union(live at c) for all c calling this procedure. The intersection operation will only remove locations. Removing returns can have three effects for each component y used by that return (e.g. if return r24 := r25{10} + r26{20} is removed, statements 10 and 20 will be affected and y will take the values r25{10} and r26{20}): 1) a statement s defining a return becomes unused if the only use of its definition was y 2) a call statement c defining y will no longer have y live if the return was the only use of y. This could cause a change to the returns of c's destination, so removeRedundantReturns has to be called for c's destination proc (if it turns out to be the only definition, and that proc was not already scheduled for return removing). 3) if y is a parameter (i.e. y is of the form loc{0}), then the signature of this procedure changes, and all callers have to have their arguments trimmed, and a similar process has to be applied to all those caller's removed arguments as is applied here to the removed returns.
The removeRetSet is the set of procedures to process with this logic; caller in Prog calls all elements in this set (only add procs to this set, never remove)
Returns
true if any change
Definition at line 83 of file UnusedReturnRemover.cpp.
References Assign, CallArgumentUpdate, LOG_MSG, LOG_WARN, m_prog, m_removeRetSet, UnusedParamRemoval, and updateForUseChange().
Referenced by removeUnusedReturns().
removeUnusedReturns()
bool UnusedReturnRemover::removeUnusedReturns ()
Remove unused return locations.
This is the global removing of unused and redundant returns. The initial idea is simple enough: remove some returns according to the formula: returns(p) = modifieds(p) isect union(live at c) for all c calling p.
However, removing returns reduces the uses, leading to three effects: 1) The statement that defines the return, if only used by that return, becomes unused 2) if the return is implicitly defined, then the parameters may be reduced, which affects all callers 3) if the return is defined at a call, the location may no longer be live at the call. If not, you need to check the child, and do the union again (hence needing a list of callers) to find out if this change also affects that child.
Returns
true if any change
Definition at line 43 of file UnusedReturnRemover.cpp.
References lessUserProc(), LocalTypeAnalysis, m_prog, m_removeRetSet, removeUnusedParamsAndReturns(), and UnusedStatementRemoval.
updateForUseChange()
void UnusedReturnRemover::updateForUseChange (UserProc * proc) private
Update parameters and call livenesses to take into account the changes caused by removing a return from this procedure, or a callee's parameter (which affects this procedure's arguments, which are also uses).
Need to save the old parameters and call livenesses, redo the dataflow and removal of unused statements, recalculate the parameters and call livenesses, and if either or both of these are changed, recurse to parents or those calls' children respectively. (When call livenesses change like this, it means that the recently removed return was the only use of that liveness, i.e. there was a return chain.)
See also
removeRedundantReturns().
Definition at line 236 of file UnusedReturnRemover.cpp.
References BlockVarRename, CallArgumentUpdate, CallDefineUpdate, CallLivenessRemoval, FinalDone, FinalParameterSearch, LocalTypeAnalysis, LOG_MSG, m_prog, m_removeRetSet, ParameterSymbolMap, PhiPlacement, StatementPropagation, UnusedParamRemoval, and UnusedStatementRemoval.
Referenced by removeUnusedParamsAndReturns().
Member Data Documentation
m_prog
Prog* UnusedReturnRemover::m_prog private
Definition at line 86 of file UnusedReturnRemover.h.
Referenced by removeUnusedParamsAndReturns(), removeUnusedReturns(), and updateForUseChange().
m_removeRetSet
ProcSet UnusedReturnRemover::m_removeRetSet private
UserProcs that need their returns updated.
Definition at line 87 of file UnusedReturnRemover.h.
Referenced by removeUnusedParamsAndReturns(), removeUnusedReturns(), and updateForUseChange().
The documentation for this class was generated from the following files:
UnusedReturnRemover.h
UnusedReturnRemover.cpp