Boomerang: SSL2ParserDriver Class Reference
SSL2ParserDriver Class Reference
Class for parsing an SSL specification file.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/ssl/parser/SSL2ParserDriver.h>
Public Member Functions
bool expandTables (const std::shared_ptr< InsNameElem > &iname, const std::shared_ptr< std::list< QString >> &params, SharedRTL o_rtlist, RTLInstDict *dict)
Expand tables in an RTL and save to dictionary.
SharedExp makeSuccessor (SharedExp e)
Make the successor of the given expression, e.g.
int parse (const std::string &fileName)
Parse the file with name eturn 0 on success.
SSL2ParserDriver (RTLInstDict *dict)
OPER strToOper (const QString &s)
Public Attributes
std::map< QString, int > ConstTable
Maps SSL constants to their values.
std::map< QString, std::shared_ptr< InsNameElem > > indexrefmap
maps index names to instruction name-elements
SSL2::location location
RTLInstDict * m_dict
RegType m_regType = RegType::Invalid
Type of the last/current register encountered.
SharedExp result
std::map< QString, std::shared_ptr< Table > > TableDict
Maps table names to Tables.
Private Member Functions
bool scanBegin ()
void scanEnd ()
Private Attributes
std::string file
The name of the file being parsed.
bool trace_parsing
Whether to generate parser debug traces.
bool trace_scanning
Whether to generate scanner debug traces.
Detailed Description
Class for parsing an SSL specification file.
Definition at line 33 of file SSL2ParserDriver.h.
Constructor & Destructor Documentation
SSL2ParserDriver()
SSL2ParserDriver::SSL2ParserDriver (RTLInstDict * dict)
Definition at line 23 of file SSL2ParserDriver.cpp.
Member Function Documentation
expandTables()
bool SSL2ParserDriver::expandTables (const std::shared_ptr< InsNameElem > & iname, const std::shared_ptr< std::list< QString >> & params, SharedRTL o_rtlist, RTLInstDict * dict)
Expand tables in an RTL and save to dictionary.
Note
This may generate many entries
Parameters
iname Parser object representing the instruction name
params Parser object representing the instruction params
o_rtlist Original rtlist object (before expanding)
Dict Ref to the dictionary that will contain the results of the parse
Definition at line 148 of file SSL2ParserDriver.cpp.
References indexrefmap, and LOG_ERROR.
makeSuccessor()
SharedExp SSL2ParserDriver::makeSuccessor (SharedExp e)
Make the successor of the given expression, e.g.
given r[2], return succ(r[2]) (using opSuccessor). We can't do the successor operation here, because the parameters are not yet instantiated (still of the form param(rd)). Actual successor done in Exp::fixSuccessor()
Note
The given expression should be of the form r[const]
The parameter expresion is copied (not cloned) in the result
Parameters
e The expression to find the successor of
Returns
The modified expression
Definition at line 186 of file SSL2ParserDriver.cpp.
References opSuccessor.
parse()
int SSL2ParserDriver::parse (const std::string & fileName)
Parse the file with name eturn 0 on success.
Definition at line 36 of file SSL2ParserDriver.cpp.
References file, location, scanBegin(), scanEnd(), and trace_parsing.
scanBegin()
bool SSL2ParserDriver::scanBegin () private
Definition at line 3137 of file SSL2Scanner.cpp.
References file, LOG_ERROR, trace_scanning, yy_flex_debug, and yyin.
Referenced by parse().
scanEnd()
void SSL2ParserDriver::scanEnd () private
Definition at line 3152 of file SSL2Scanner.cpp.
References yyin, and yylex_destroy.
Referenced by parse().
strToOper()
OPER SSL2ParserDriver::strToOper (const QString & s)
Definition at line 54 of file SSL2ParserDriver.cpp.
References LOG_ERROR, opArcTan, opCos, opFround, opFsize, opFtoi, opItof, opLog10, opLog2, opLoge, opSgnEx, opSin, opSqrt, opTan, opTruncs, opTruncu, opWild, and opZfill.
Member Data Documentation
ConstTable
std::map<QString, int> SSL2ParserDriver::ConstTable
Maps SSL constants to their values.
Definition at line 57 of file SSL2ParserDriver.h.
file
std::string SSL2ParserDriver::file private
The name of the file being parsed.
Definition at line 73 of file SSL2ParserDriver.h.
Referenced by parse(), and scanBegin().
indexrefmap
std::map<QString, std::shared_ptr<InsNameElem> > SSL2ParserDriver::indexrefmap
maps index names to instruction name-elements
Definition at line 60 of file SSL2ParserDriver.h.
Referenced by expandTables().
location
SSL2::location SSL2ParserDriver::location
Definition at line 49 of file SSL2ParserDriver.h.
Referenced by parse().
m_dict
RTLInstDict* SSL2ParserDriver::m_dict
Definition at line 45 of file SSL2ParserDriver.h.
m_regType
RegType SSL2ParserDriver::m_regType = RegType::Invalid
Type of the last/current register encountered.
Definition at line 65 of file SSL2ParserDriver.h.
result
SharedExp SSL2ParserDriver::result
Definition at line 46 of file SSL2ParserDriver.h.
TableDict
std::map<QString, std::shared_ptr<Table> > SSL2ParserDriver::TableDict
Maps table names to Tables.
Definition at line 63 of file SSL2ParserDriver.h.
trace_parsing
bool SSL2ParserDriver::trace_parsing private
Whether to generate parser debug traces.
Definition at line 74 of file SSL2ParserDriver.h.
Referenced by parse().
trace_scanning
bool SSL2ParserDriver::trace_scanning private
Whether to generate scanner debug traces.
Definition at line 75 of file SSL2ParserDriver.h.
Referenced by scanBegin().
The documentation for this class was generated from the following files:
SSL2ParserDriver.h
SSL2ParserDriver.cpp
SSL2Scanner.cpp