Boomerang: ExpDotWriter Class Reference
ExpDotWriter Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/ExpDotWriter.h>
Public Member Functions
bool writeDotFile (const std::shared_ptr< class Exp > &exp, const QString &filename)
Private Member Functions
bool postVisit (const std::shared_ptr< Binary > &exp) override
bool postVisit (const std::shared_ptr< Location > &exp) override
bool postVisit (const std::shared_ptr< RefExp > &exp) override
bool postVisit (const std::shared_ptr< Ternary > &exp) override
bool postVisit (const std::shared_ptr< TypedExp > &exp) override
bool postVisit (const std::shared_ptr< Unary > &exp) override
bool visit (const std::shared_ptr< Const > &exp) override
bool visit (const std::shared_ptr< Terminal > &exp) override
Private Attributes
OStream * m_os
Detailed Description
Definition at line 20 of file ExpDotWriter.h.
Member Function Documentation
postVisit() [1/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< Binary > & exp) override private
Definition at line 69 of file ExpDotWriter.cpp.
References exp, m_os, and operToString().
postVisit() [2/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< Location > & exp) override private
Definition at line 170 of file ExpDotWriter.cpp.
References exp, postVisit(), and Unary.
postVisit() [3/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< RefExp > & exp) override private
Definition at line 164 of file ExpDotWriter.cpp.
References exp, postVisit(), and Unary.
postVisit() [4/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< Ternary > & exp) override private
Definition at line 88 of file ExpDotWriter.cpp.
References exp, m_os, and operToString().
postVisit() [5/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< TypedExp > & exp) override private
Definition at line 150 of file ExpDotWriter.cpp.
References exp, and m_os.
postVisit() [6/6]
bool ExpDotWriter::postVisit (const std::shared_ptr< Unary > & exp) override private
Definition at line 51 of file ExpDotWriter.cpp.
References exp, m_os, and operToString().
Referenced by postVisit().
visit() [1/2]
bool ExpDotWriter::visit (const std::shared_ptr< Const > & exp) override private
Definition at line 109 of file ExpDotWriter.cpp.
References exp, m_os, operToString(), opFltConst, opFuncConst, opIntConst, and opStrConst.
visit() [2/2]
bool ExpDotWriter::visit (const std::shared_ptr< Terminal > & exp) override private
Definition at line 131 of file ExpDotWriter.cpp.
References exp, m_os, operToString(), and opWild.
writeDotFile()
bool ExpDotWriter::writeDotFile (const std::shared_ptr< class Exp > & exp, const QString & filename)
Definition at line 27 of file ExpDotWriter.cpp.
References exp, LOG_ERROR, and m_os.
Member Data Documentation
m_os
OStream* ExpDotWriter::m_os private
Definition at line 51 of file ExpDotWriter.h.
Referenced by postVisit(), visit(), and writeDotFile().
The documentation for this class was generated from the following files:
ExpDotWriter.h
ExpDotWriter.cpp