Boomerang: ExpPrinter Class Reference
ExpPrinter Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/ExpPrinter.h>
Public Member Functions
void print (OStream &os, const SharedConstExp &exp) const
print exp to os
Private Member Functions
bool childNeedsParentheses (const SharedConstExp &exp, const SharedConstExp &child) const
Given an expression, and an immediate child expression, determine if the child expression needs to be parenthesized or not.
void printHTML (OStream &os, const SharedConstExp &exp) const
print exp to os
void printPlain (OStream &os, const SharedConstExp &exp) const
print exp to os
Detailed Description
Definition at line 21 of file ExpPrinter.h.
Member Function Documentation
childNeedsParentheses()
bool ExpPrinter::childNeedsParentheses (const SharedConstExp & exp, const SharedConstExp & child) const private
Given an expression, and an immediate child expression, determine if the child expression needs to be parenthesized or not.
Definition at line 293 of file ExpPrinter.cpp.
References exp, opBitNot, opFround, opFsize, opFtoi, opFtrunc, opItof, opList, opLNot, opSgnEx, opTruncs, opTruncu, and opZfill.
Referenced by printPlain().
print()
void ExpPrinter::print (OStream & os, const SharedConstExp & exp) const
print exp to os
Definition at line 127 of file ExpPrinter.cpp.
References exp, and printPlain().
Referenced by operator<<(), and printPlain().
printHTML()
void ExpPrinter::printHTML (OStream & os, const SharedConstExp & exp) const private
print exp to os
Definition at line 285 of file ExpPrinter.cpp.
References exp.
printPlain()
void ExpPrinter::printPlain (OStream & os, const SharedConstExp & exp) const private
print exp to os
Definition at line 133 of file ExpPrinter.cpp.
References childNeedsParentheses(), exp, g_syntaxTable, opFlagCall, opFltConst, opFuncConst, opGlobal, opIntConst, opList, opLocal, opLongConst, opMemberAccess, opParam, opRegOf, opStrConst, opSubscript, opTemp, opTypedExp, opWildStrConst, print(), and STMT_WILD.
Referenced by print().
The documentation for this class was generated from the following files:
ExpPrinter.h
ExpPrinter.cpp