Boomerang: IntervalMap< Key, Value > Class Template Reference
IntervalMap< Key, Value > Class Template Reference
A map that maps intervals of Key types to Value types.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/IntervalMap.h>
Public Types
typedef Data::const_iterator const_iterator
typedef Data::const_reverse_iterator const_reverse_iterator
typedef std::map< Interval< Key >, Value > Data
typedef Data::iterator iterator
typedef Data::reverse_iterator reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
void clear ()
Remove all elements from this map.
iterator end ()
const_iterator end () const
std::pair< iterator, iterator > equalRange (const Interval< Key > &interval)
std::pair< const_iterator, const_iterator > equalRange (const Interval< Key > &interval) const
std::pair< iterator, iterator > equalRange (const Key &lower, const Key &upper)
std::pair< const_iterator, const_iterator > equalRange (const Key &lower, const Key &upper) const
iterator erase (iterator it)
Erase the item referenced by it.
void eraseAll (const Interval< Key > &interval)
Remove all intervals overlapping with interval.
void eraseAll (const Key &key)
Remove all intervals containing key.
iterator find (const Key &key)
const_iterator find (const Key &key) const
Finds the mapped value at key.
iterator insert (const Interval< Key > &key, Value value)
Inserts an interval with a mapped value into this map.
iterator insert (const Key &lower, const Key &upper, Value value)
bool isEmpty () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
Private Attributes
std::map< Interval< Key >, Value, std::less< Interval< Key > > > m_data
Detailed Description
template<typename Key, typename Value>
class IntervalMap< Key, Value >
A map that maps intervals of Key types to Value types.
Intervals may overlap each other.
Definition at line 24 of file IntervalMap.h.
Member Typedef Documentation
const_iterator
template<typename Key , typename Value > typedef Data::const_iterator IntervalMap< Key, Value >::const_iterator
Definition at line 30 of file IntervalMap.h.
const_reverse_iterator
template<typename Key , typename Value > typedef Data::const_reverse_iterator IntervalMap< Key, Value >::const_reverse_iterator
Definition at line 32 of file IntervalMap.h.
Data
template<typename Key , typename Value > typedef std::map<Interval<Key>, Value> IntervalMap< Key, Value >::Data
Definition at line 27 of file IntervalMap.h.
iterator
template<typename Key , typename Value > typedef Data::iterator IntervalMap< Key, Value >::iterator
Definition at line 29 of file IntervalMap.h.
reverse_iterator
template<typename Key , typename Value > typedef Data::reverse_iterator IntervalMap< Key, Value >::reverse_iterator
Definition at line 31 of file IntervalMap.h.
Member Function Documentation
begin() [1/2]
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::begin () inline
Definition at line 35 of file IntervalMap.h.
Referenced by IntervalMap< Address, VariantHolder >::equalRange(), and IntervalMap< Address, VariantHolder >::find().
begin() [2/2]
template<typename Key , typename Value > const_iterator IntervalMap< Key, Value >::begin () const inline
Definition at line 37 of file IntervalMap.h.
clear()
template<typename Key , typename Value > void IntervalMap< Key, Value >::clear () inline
Remove all elements from this map.
Definition at line 49 of file IntervalMap.h.
end() [1/2]
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::end () inline
Definition at line 36 of file IntervalMap.h.
Referenced by BinarySectionImpl::attributeInRange(), IntervalMap< Address, VariantHolder >::equalRange(), IntervalMap< Address, VariantHolder >::erase(), IntervalMap< Address, VariantHolder >::eraseAll(), IntervalMap< Address, VariantHolder >::find(), BinarySectionImpl::getAttributesForRange(), and IntervalMap< Address, VariantHolder >::insert().
end() [2/2]
template<typename Key , typename Value > const_iterator IntervalMap< Key, Value >::end () const inline
Definition at line 38 of file IntervalMap.h.
equalRange() [1/4]
template<typename Key , typename Value > std::pair<iterator, iterator> IntervalMap< Key, Value >::equalRange (const Interval< Key > & interval) inline
Definition at line 186 of file IntervalMap.h.
equalRange() [2/4]
template<typename Key , typename Value > std::pair<const_iterator, const_iterator> IntervalMap< Key, Value >::equalRange (const Interval< Key > & interval) const inline
Definition at line 160 of file IntervalMap.h.
equalRange() [3/4]
template<typename Key , typename Value > std::pair<iterator, iterator> IntervalMap< Key, Value >::equalRange (const Key & lower, const Key & upper) inline
Definition at line 181 of file IntervalMap.h.
equalRange() [4/4]
template<typename Key , typename Value > std::pair<const_iterator, const_iterator> IntervalMap< Key, Value >::equalRange (const Key & lower, const Key & upper) const inline
Returns
an iterator range containing all intervals between lower and upper. If there are no intervals between lower and upper, the function returns (end(), end).
Definition at line 155 of file IntervalMap.h.
Referenced by IntervalMap< Address, VariantHolder >::equalRange(), IntervalMap< Address, VariantHolder >::eraseAll(), and BinarySectionImpl::getAttributesForRange().
erase()
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::erase (iterator it) inline
Erase the item referenced by it.
Returns
an iterator to the element immediately after the deleted element
Definition at line 70 of file IntervalMap.h.
Referenced by IntervalMap< Address, VariantHolder >::eraseAll().
eraseAll() [1/2]
template<typename Key , typename Value > void IntervalMap< Key, Value >::eraseAll (const Interval< Key > & interval) inline
Remove all intervals overlapping with interval.
Definition at line 91 of file IntervalMap.h.
eraseAll() [2/2]
template<typename Key , typename Value > void IntervalMap< Key, Value >::eraseAll (const Key & key) inline
Remove all intervals containing key.
Definition at line 77 of file IntervalMap.h.
find() [1/2]
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::find (const Key & key) inline
Definition at line 129 of file IntervalMap.h.
find() [2/2]
template<typename Key , typename Value > const_iterator IntervalMap< Key, Value >::find (const Key & key) const inline
Finds the mapped value at key.
If there are muliple candidate intervals, the interval with the lowest lower bound is retrieved.
Definition at line 107 of file IntervalMap.h.
Referenced by BinarySectionImpl::attributeInRange(), and IntervalMap< Address, VariantHolder >::eraseAll().
insert() [1/2]
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::insert (const Interval< Key > & key, Value value) inline
Inserts an interval with a mapped value into this map.
Definition at line 52 of file IntervalMap.h.
Referenced by IntervalMap< Address, VariantHolder >::insert(), and BinarySectionImpl::setAttributeForRange().
insert() [2/2]
template<typename Key , typename Value > iterator IntervalMap< Key, Value >::insert (const Key & lower, const Key & upper, Value value) inline
Definition at line 63 of file IntervalMap.h.
isEmpty()
template<typename Key , typename Value > bool IntervalMap< Key, Value >::isEmpty () const inline
Returns
true if the map does not contain any elements.
Definition at line 46 of file IntervalMap.h.
rbegin() [1/2]
template<typename Key , typename Value > reverse_iterator IntervalMap< Key, Value >::rbegin () inline
Definition at line 39 of file IntervalMap.h.
rbegin() [2/2]
template<typename Key , typename Value > const_reverse_iterator IntervalMap< Key, Value >::rbegin () const inline
Definition at line 41 of file IntervalMap.h.
rend() [1/2]
template<typename Key , typename Value > reverse_iterator IntervalMap< Key, Value >::rend () inline
Definition at line 40 of file IntervalMap.h.
rend() [2/2]
template<typename Key , typename Value > const_reverse_iterator IntervalMap< Key, Value >::rend () const inline
Definition at line 42 of file IntervalMap.h.
Member Data Documentation
m_data
template<typename Key , typename Value > std::map<Interval<Key>, Value, std::less<Interval<Key> > > IntervalMap< Key, Value >::m_data private
Definition at line 221 of file IntervalMap.h.
Referenced by IntervalMap< Address, VariantHolder >::begin(), IntervalMap< Address, VariantHolder >::clear(), IntervalMap< Address, VariantHolder >::end(), IntervalMap< Address, VariantHolder >::erase(), IntervalMap< Address, VariantHolder >::insert(), IntervalMap< Address, VariantHolder >::isEmpty(), IntervalMap< Address, VariantHolder >::rbegin(), and IntervalMap< Address, VariantHolder >::rend().
The documentation for this class was generated from the following file:
IntervalMap.h