Boomerang: StmtCastInserter Class Reference
StmtCastInserter Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/stmtvisitor/StmtCastInserter.h>
Public Member Functions
bool common (const Assignment *stmt)
StmtCastInserter ()=default
virtual bool visit (const Assign *stmt) override
virtual bool visit (const BoolAssign *stmt) override
virtual bool visit (const ImplicitAssign *stmt) override
virtual bool visit (const PhiAssign *stmt) override
virtual ~StmtCastInserter ()=default
Detailed Description
Definition at line 25 of file StmtCastInserter.h.
Constructor & Destructor Documentation
StmtCastInserter()
StmtCastInserter::StmtCastInserter () default
~StmtCastInserter()
virtual StmtCastInserter::~StmtCastInserter () virtual default
Member Function Documentation
common()
bool StmtCastInserter::common (const Assignment * stmt)
Definition at line 44 of file StmtCastInserter.cpp.
References ExpCastInserter::checkMemofType(), and stmt.
Referenced by visit().
visit() [1/4]
bool StmtCastInserter::visit (const Assign * stmt) override virtual
Definition at line 20 of file StmtCastInserter.cpp.
References common(), and stmt.
visit() [2/4]
bool StmtCastInserter::visit (const BoolAssign * stmt) override virtual
Definition at line 38 of file StmtCastInserter.cpp.
References common(), and stmt.
visit() [3/4]
bool StmtCastInserter::visit (const ImplicitAssign * stmt) override virtual
Definition at line 32 of file StmtCastInserter.cpp.
References common(), and stmt.
visit() [4/4]
bool StmtCastInserter::visit (const PhiAssign * stmt) override virtual
Definition at line 26 of file StmtCastInserter.cpp.
References common(), and stmt.
The documentation for this class was generated from the following files:
StmtCastInserter.h
StmtCastInserter.cpp