Boomerang: AssignRemovalPass Class Reference
AssignRemovalPass Class Reference final
Removes unused or tautological assignments.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/passes/middle/AssignRemovalPass.h>
Public Member Functions
AssignRemovalPass ()
bool execute (UserProc *proc) override
Run this pass, updating proc.
Public Member Functions inherited from IPass
const QString & getName () const
PassID getType () const
IPass (const QString &name, PassID type)
virtual bool isProcLocal () const
virtual ~IPass ()=default
Private Member Functions
bool removeMatchingAssigns (UserProc *proc, SharedExp exp)
bool removeSpAssigns (UserProc *proc)
Preservations only for the stack pointer.
Detailed Description
Removes unused or tautological assignments.
Definition at line 21 of file AssignRemovalPass.h.
Constructor & Destructor Documentation
AssignRemovalPass()
AssignRemovalPass::AssignRemovalPass ()
Definition at line 24 of file AssignRemovalPass.cpp.
References AssignRemoval.
Member Function Documentation
execute()
bool AssignRemovalPass::execute (UserProc * proc) override virtual
Run this pass, updating proc.
Returns
true iff any change
Implements IPass.
Definition at line 30 of file AssignRemovalPass.cpp.
References opPC, opTemp, opWildStrConst, removeMatchingAssigns(), and removeSpAssigns().
removeMatchingAssigns()
bool AssignRemovalPass::removeMatchingAssigns (UserProc * proc, SharedExp exp) private
Definition at line 94 of file AssignRemovalPass.cpp.
References a, Assign, LOG_VERBOSE, PhiAssign, and stmt.
Referenced by execute().
removeSpAssigns()
bool AssignRemovalPass::removeSpAssigns (UserProc * proc) private
Preservations only for the stack pointer.
Definition at line 40 of file AssignRemovalPass.cpp.
References a, Assign, Util::getStackRegisterIndex(), and stmt.
Referenced by execute().
The documentation for this class was generated from the following files:
AssignRemovalPass.h
AssignRemovalPass.cpp