Boomerang: Interval< T > Class Template Reference
Interval< T > Class Template Reference
Class for right-open intervals.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/Interval.h>
Public Member Functions
bool canMergeWith (const Interval< T > &other) const
bool contains (const T &value) const
Checks if value is contained in this interval.
bool containsInterval (const Interval< T > &other) const
Interval (const Interval< T > &other)
Interval (const T &_lower, const T &_upper)
Construct a right-open interval.
Interval (Interval< T > &&other)
const T & lower () const
const Interval< T > & operator+= (const Interval< T > &other)
bool operator< (const Interval< T > &other) const
Compare this interval to another interval by its lower bound.
bool operator< (const T &value) const
Compare the lower bound of this interval to a single value.
const Interval< T > & operator= (const Interval< T > &other)
const Interval< T > & operator= (Interval< T > &&other)
const T & upper () const
~Interval ()=default
Private Attributes
T m_lower
Lower bound of the interval.
T m_upper
Upper bound of the interval.
Detailed Description
template<typename T>
class Interval< T >
Class for right-open intervals.
Definition at line 17 of file Interval.h.
Constructor & Destructor Documentation
Interval() [1/3]
template<typename T > Interval< T >::Interval (const T & _lower, const T & _upper) inline explicit
Construct a right-open interval.
Definition at line 21 of file Interval.h.
~Interval()
template<typename T > Interval< T >::~Interval () default
Interval() [2/3]
template<typename T > Interval< T >::Interval (const Interval< T > & other) inline
Definition at line 29 of file Interval.h.
Interval() [3/3]
template<typename T > Interval< T >::Interval (Interval< T > && other) inline
Definition at line 35 of file Interval.h.
Member Function Documentation
canMergeWith()
template<typename T > bool Interval< T >::canMergeWith (const Interval< T > & other) const inline
Returns
true if this and the other interval are adjacent or partially contained within each other. i.e. there is no "hole" between the two intervals.
Definition at line 72 of file Interval.h.
References Interval< T >::lower(), and Interval< T >::upper().
Referenced by Interval< T >::operator+=().
contains()
template<typename T > bool Interval< T >::contains (const T & value) const inline
Checks if value is contained in this interval.
Returns false for the upper bound (since it is a right-open interval).
Definition at line 65 of file Interval.h.
References Util::value.
containsInterval()
template<typename T > bool Interval< T >::containsInterval (const Interval< T > & other) const inline
Returns
whether the other interval is fully contained within this interval, i.e. other - *this == empty
Definition at line 79 of file Interval.h.
References Interval< T >::lower(), and Interval< T >::upper().
lower()
template<typename T > const T& Interval< T >::lower () const inline
Returns
the lower bound of the interval.
Definition at line 57 of file Interval.h.
References Interval< T >::m_lower.
Referenced by Interval< T >::canMergeWith(), Interval< T >::containsInterval(), IntervalSet< Address >::equalRange(), IntervalMap< Address, VariantHolder >::equalRange(), IntervalSet< Address >::insert(), IntervalMap< Address, VariantHolder >::insert(), Interval< T >::operator+=(), and Interval< T >::operator=().
operator+=()
template<typename T > const Interval<T>& Interval< T >::operator+= (const Interval< T > & other) inline
Definition at line 96 of file Interval.h.
References Interval< T >::canMergeWith(), Interval< T >::lower(), Interval< T >::m_lower, Interval< T >::m_upper, and Interval< T >::upper().
operator<() [1/2]
template<typename T > bool Interval< T >::operator< (const Interval< T > & other) const inline
Compare this interval to another interval by its lower bound.
Returns
whether this->lower() < other.lower()
Definition at line 88 of file Interval.h.
References Interval< T >::m_lower.
operator<() [2/2]
template<typename T > bool Interval< T >::operator< (const T & value) const inline
Compare the lower bound of this interval to a single value.
Returns
whether this->lower() < value
Definition at line 94 of file Interval.h.
References Interval< T >::m_lower, and Util::value.
operator=() [1/2]
template<typename T > const Interval<T>& Interval< T >::operator= (const Interval< T > & other) inline
Definition at line 41 of file Interval.h.
References Interval< T >::lower(), Interval< T >::m_lower, Interval< T >::m_upper, and Interval< T >::upper().
operator=() [2/2]
template<typename T > const Interval<T>& Interval< T >::operator= (Interval< T > && other) inline
Definition at line 48 of file Interval.h.
References Interval< T >::m_lower, and Interval< T >::m_upper.
upper()
template<typename T > const T& Interval< T >::upper () const inline
Returns
the upper bound of the interval.
Definition at line 59 of file Interval.h.
References Interval< T >::m_upper.
Referenced by Interval< T >::canMergeWith(), Interval< T >::containsInterval(), IntervalSet< Address >::equalRange(), IntervalMap< Address, VariantHolder >::equalRange(), IntervalSet< Address >::insert(), IntervalMap< Address, VariantHolder >::insert(), Interval< T >::operator+=(), and Interval< T >::operator=().
Member Data Documentation
m_lower
template<typename T > T Interval< T >::m_lower private
Lower bound of the interval.
Definition at line 105 of file Interval.h.
Referenced by Interval< T >::lower(), Interval< T >::operator+=(), Interval< T >::operator<(), and Interval< T >::operator=().
m_upper
template<typename T > T Interval< T >::m_upper private
Upper bound of the interval.
Definition at line 106 of file Interval.h.
Referenced by Interval< T >::operator+=(), Interval< T >::operator=(), and Interval< T >::upper().
The documentation for this class was generated from the following file:
Interval.h