Boomerang: Console Class Reference
Console Class Reference
Console for interactive mode.
#include </home/ceeac/Projects/code/boomerang/src/boomerang-cli/Console.h>
Public Member Functions
bool commandSucceeded (CommandStatus status)
Console (Project *project)
CommandStatus handleCommand (const QString &command)
CommandStatus replayFile (const QString &file)
Execute the commands in file line by line.
~Console ()=default
Private Member Functions
CommandType commandNameToType (const QString &command)
CommandStatus handleAdd (const QStringList &args)
CommandStatus handleCodegen (const QStringList &args)
CommandStatus handleDecode (const QStringList &args)
CommandStatus handleDecompile (const QStringList &args)
CommandStatus handleDelete (const QStringList &args)
CommandStatus handleExit (const QStringList &args)
CommandStatus handleHelp (const QStringList &args)
CommandStatus handleInfo (const QStringList &args)
CommandStatus handleMove (const QStringList &args)
CommandStatus handlePrint (const QStringList &args)
CommandStatus handleRename (const QStringList &args)
CommandStatus handleReplay (const QStringList &args)
CommandStatus processCommand (const QString &command, const QStringList &args)
CommandStatus splitCommand (const QString &commandWithArgs, QString &command, QStringList &args)
Split commandWithArgs into command and args.
Private Attributes
QMap< QString, CommandType > m_commandTypes
QMap< class UserProc *, int > m_dfgCounts
Project * m_project
Detailed Description
Console for interactive mode.
Parses arguments and passes them to libboomerang to be executed.
Definition at line 53 of file Console.h.
Constructor & Destructor Documentation
Console()
Console::Console (Project * project)
Definition at line 31 of file Console.cpp.
References CT_add, CT_codegen, CT_decode, CT_decompile, CT_delete, CT_exit, CT_help, CT_info, CT_move, CT_print, CT_rename, CT_replay, and m_commandTypes.
~Console()
Console::~Console () default
Member Function Documentation
commandNameToType()
CommandType Console::commandNameToType (const QString & command) private
Definition at line 181 of file Console.cpp.
References CT_unknown, and m_commandTypes.
Referenced by processCommand().
commandSucceeded()
bool Console::commandSucceeded (CommandStatus status) inline
Definition at line 65 of file Console.h.
References AsyncSuccess, and Success.
Referenced by handleCommand(), and replayFile().
handleAdd()
CommandStatus Console::handleAdd (const QStringList & args) private
Definition at line 376 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handleCodegen()
CommandStatus Console::handleCodegen (const QStringList & args) private
Definition at line 262 of file Console.cpp.
References Failure, m_project, and Success.
Referenced by processCommand().
handleCommand()
CommandStatus Console::handleCommand (const QString & command)
Definition at line 50 of file Console.cpp.
References commandSucceeded(), Failure, processCommand(), and splitCommand().
Referenced by replayFile().
handleDecode()
CommandStatus Console::handleDecode (const QStringList & args) private
Definition at line 188 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handleDecompile()
CommandStatus Console::handleDecompile (const QStringList & args) private
Definition at line 216 of file Console.cpp.
References Failure, m_project, and Success.
Referenced by processCommand().
handleDelete()
CommandStatus Console::handleDelete (const QStringList & args) private
Definition at line 432 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handleExit()
CommandStatus Console::handleExit (const QStringList & args) private
Definition at line 847 of file Console.cpp.
References ExitProgram, and ParseError.
Referenced by processCommand().
handleHelp()
CommandStatus Console::handleHelp (const QStringList & args) private
Definition at line 859 of file Console.cpp.
References ParseError, and Success.
Referenced by processCommand().
handleInfo()
CommandStatus Console::handleInfo (const QStringList & args) private
Definition at line 548 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handleMove()
CommandStatus Console::handleMove (const QStringList & args) private
Definition at line 309 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handlePrint()
CommandStatus Console::handlePrint (const QStringList & args) private
Definition at line 680 of file Console.cpp.
References Failure, m_dfgCounts, m_project, ParseError, and Success.
Referenced by processCommand().
handleRename()
CommandStatus Console::handleRename (const QStringList & args) private
Definition at line 481 of file Console.cpp.
References Failure, m_project, ParseError, and Success.
Referenced by processCommand().
handleReplay()
CommandStatus Console::handleReplay (const QStringList & args) private
Definition at line 297 of file Console.cpp.
References ParseError, and replayFile().
Referenced by processCommand().
processCommand()
CommandStatus Console::processCommand (const QString & command, const QStringList & args) private
Definition at line 157 of file Console.cpp.
References commandNameToType(), CT_add, CT_codegen, CT_decode, CT_decompile, CT_delete, CT_exit, CT_help, CT_info, CT_move, CT_print, CT_rename, CT_replay, handleAdd(), handleCodegen(), handleDecode(), handleDecompile(), handleDelete(), handleExit(), handleHelp(), handleInfo(), handleMove(), handlePrint(), handleRename(), handleReplay(), and ParseError.
Referenced by handleCommand().
replayFile()
CommandStatus Console::replayFile (const QString & file)
Execute the commands in file line by line.
Definition at line 63 of file Console.cpp.
References commandSucceeded(), ExitProgram, Failure, handleCommand(), and Success.
Referenced by handleReplay().
splitCommand()
CommandStatus Console::splitCommand (const QString & commandWithArgs, QString & command, QStringList & args) private
Split commandWithArgs into command and args.
Returns
Success or ParseError
extract arguments
Definition at line 101 of file Console.cpp.
References ParseError, and Success.
Referenced by handleCommand().
Member Data Documentation
m_commandTypes
QMap<QString, CommandType> Console::m_commandTypes private
Definition at line 97 of file Console.h.
Referenced by commandNameToType(), and Console().
m_dfgCounts
QMap<class UserProc *, int> Console::m_dfgCounts private
Definition at line 100 of file Console.h.
Referenced by handlePrint().
m_project
Project* Console::m_project private
Definition at line 98 of file Console.h.
Referenced by handleAdd(), handleCodegen(), handleDecode(), handleDecompile(), handleDelete(), handleInfo(), handleMove(), handlePrint(), and handleRename().
The documentation for this class was generated from the following files:
Console.h
Console.cpp