Boomerang: DfaLocalMapper Class Reference
DfaLocalMapper Class Reference
This class is an ExpModifier because although most of the time it merely maps expressions to locals, in one case, where sp-K is found, we replace it with a[m[sp-K]] so the back end emits it as &localX.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/expmodifier/DFALocalMapper.h>
Public Member Functions
DfaLocalMapper (UserProc *proc)
Map expressions to locals, using the (so far DFA based) type analysis information Basically, descend types, and when you get to m[...] compare with the local high level pattern; when at a sum or difference, check for the address of locals high level pattern that is a pointer.
SharedExp preModify (const std::shared_ptr< Binary > &exp, bool &visitChildren) override
SharedExp preModify (const std::shared_ptr< Location > &exp, bool &visitChildren) override
SharedExp preModify (const std::shared_ptr< TypedExp > &exp, bool &visitChildren) override
virtual ~DfaLocalMapper ()=default
Public Attributes
bool change = false
Private Member Functions
bool processExp (const SharedExp &e)
Common processing for the two main cases (visiting a Location or a Binary)
Private Attributes
UserProc * m_proc = nullptr
Prog * m_prog = nullptr
std::shared_ptr< Signature > m_sig
Look up once (from proc) for speed.
Detailed Description
This class is an ExpModifier because although most of the time it merely maps expressions to locals, in one case, where sp-K is found, we replace it with a[m[sp-K]] so the back end emits it as &localX.
FIXME: this is probably no longer necessary, since the back end no longer maps anything!
Definition at line 27 of file DFALocalMapper.h.
Constructor & Destructor Documentation
DfaLocalMapper()
DfaLocalMapper::DfaLocalMapper (UserProc * proc)
Map expressions to locals, using the (so far DFA based) type analysis information Basically, descend types, and when you get to m[...] compare with the local high level pattern; when at a sum or difference, check for the address of locals high level pattern that is a pointer.
Definition at line 21 of file DFALocalMapper.cpp.
~DfaLocalMapper()
virtual DfaLocalMapper::~DfaLocalMapper () virtual default
Member Function Documentation
preModify() [1/3]
SharedExp DfaLocalMapper::preModify (const std::shared_ptr< Binary > & exp, bool & visitChildren) override
To look for sp -+ K
Definition at line 62 of file DFALocalMapper.cpp.
References exp, m_proc, opAddrOf, and processExp().
preModify() [2/3]
SharedExp DfaLocalMapper::preModify (const std::shared_ptr< Location > & exp, bool & visitChildren) override
To process m[X]
Definition at line 49 of file DFALocalMapper.cpp.
References exp, m_proc, and processExp().
preModify() [3/3]
SharedExp DfaLocalMapper::preModify (const std::shared_ptr< TypedExp > & exp, bool & visitChildren) override
To prevent processing TypedExps more than once
Definition at line 84 of file DFALocalMapper.cpp.
References exp.
processExp()
bool DfaLocalMapper::processExp (const SharedExp & e) private
Common processing for the two main cases (visiting a Location or a Binary)
Definition at line 29 of file DFALocalMapper.cpp.
References change, exp, Util::getStackRegisterIndex(), m_proc, m_prog, and m_sig.
Referenced by preModify().
Member Data Documentation
change
bool DfaLocalMapper::change = false
Definition at line 53 of file DFALocalMapper.h.
Referenced by LocalAndParamMapPass::execute(), and processExp().
m_proc
UserProc* DfaLocalMapper::m_proc = nullptr private
Definition at line 56 of file DFALocalMapper.h.
Referenced by preModify(), and processExp().
m_prog
Prog* DfaLocalMapper::m_prog = nullptr private
Definition at line 57 of file DFALocalMapper.h.
Referenced by processExp().
m_sig
std::shared_ptr<Signature> DfaLocalMapper::m_sig private
Look up once (from proc) for speed.
Definition at line 58 of file DFALocalMapper.h.
Referenced by processExp().
The documentation for this class was generated from the following files:
DFALocalMapper.h
DFALocalMapper.cpp