Boomerang: Decompiler Class Reference
Decompiler Class Reference
Interface between libboomerang and the GUI.
#include </home/ceeac/Projects/code/boomerang/src/boomerang-gui/Decompiler.h>
Public Slots
void addEntryPoint (Address entryAddr, const QString &name)
void decode ()
void decompile ()
void generateCode ()
void loadInputFile (const QString &inputFile, const QString &outputPath)
void removeEntryPoint (Address entryAddr)
void rereadLibSignatures ()
void stopWaiting ()
Signals
void debugPointHit (const QString &name, const QString &description)
void decodeCompleted ()
void decodingStarted ()
void decompileCompleted ()
void decompilingStarted ()
void entryPointAdded (Address entryAddr, const QString &name)
void functionAddedToModule (const QString &functionName, const QString &moduleName)
void generateCodeCompleted ()
void generatingCodeStarted ()
void libProcCreated (const QString &name, const QString &params)
void libProcRemoved (const QString &name)
void loadCompleted ()
void loadingStarted ()
void machineTypeChanged (const QString &machine)
void moduleCreated (const QString &name)
void procDecompileStarted (const QString &procName)
void procDiscovered (const QString &callerName, const QString &procName)
void sectionAdded (const QString &sectionName, Address start, Address end)
void userProcCreated (const QString &name, Address entryAddr)
void userProcRemoved (const QString &name, Address entryAddr)
Public Member Functions
Decompiler ()
QString getClusterFile (const QString &name)
void getCompoundMembers (const QString &name, QTableWidget *tbl)
Project * getProject ()
bool getRTLForProc (const QString &name, QString &rtl)
QString getSigFilePath (const QString &name)
virtual void onDecompileDebugPoint (UserProc *proc, const char *description) override
IWatcher interface.
virtual void onDecompileInProgress (UserProc *function) override
virtual void onFunctionCreated (Function *function) override
virtual void onFunctionDiscovered (Function *function) override
virtual void onFunctionRemoved (Function *function) override
virtual void onSignatureUpdated (Function *function) override
void renameProc (const QString &oldName, const QString &newName)
void setDebugEnabled (bool debug)
~Decompiler ()
Protected Attributes
bool m_debugging = false
Project m_project
std::vector< Address > m_userEntrypoints
bool m_waiting = false
Private Member Functions
void moduleAndChildrenUpdated (Module *root)
After code generation, update the list of modules.
Detailed Description
Interface between libboomerang and the GUI.
Definition at line 32 of file Decompiler.h.
Constructor & Destructor Documentation
Decompiler()
Decompiler::Decompiler ()
Definition at line 31 of file Decompiler.cpp.
References m_project.
~Decompiler()
Decompiler::~Decompiler ()
Definition at line 42 of file Decompiler.cpp.
Member Function Documentation
addEntryPoint
void Decompiler::addEntryPoint (Address entryAddr, const QString & name) slot
Definition at line 47 of file Decompiler.cpp.
References m_project, and m_userEntrypoints.
debugPointHit
void Decompiler::debugPointHit (const QString & name, const QString & description) signal
Referenced by MainWindow::MainWindow(), and onDecompileDebugPoint().
decode
void Decompiler::decode () slot
Definition at line 104 of file Decompiler.cpp.
References decodeCompleted(), decodingStarted(), LOG_MSG, m_project, and machineTypeChanged().
decodeCompleted
void Decompiler::decodeCompleted () signal
Referenced by decode(), and MainWindow::MainWindow().
decodingStarted
void Decompiler::decodingStarted () signal
Referenced by decode(), and MainWindow::MainWindow().
decompile
void Decompiler::decompile () slot
Definition at line 121 of file Decompiler.cpp.
References decompileCompleted(), decompilingStarted(), LOG_MSG, and m_project.
decompileCompleted
void Decompiler::decompileCompleted () signal
Referenced by decompile(), and MainWindow::MainWindow().
decompilingStarted
void Decompiler::decompilingStarted () signal
Referenced by decompile(), and MainWindow::MainWindow().
entryPointAdded
void Decompiler::entryPointAdded (Address entryAddr, const QString & name) signal
Referenced by loadInputFile(), and MainWindow::MainWindow().
functionAddedToModule
void Decompiler::functionAddedToModule (const QString & functionName, const QString & moduleName) signal
Referenced by generateCode(), and MainWindow::MainWindow().
generateCode
void Decompiler::generateCode () slot
Definition at line 143 of file Decompiler.cpp.
References functionAddedToModule(), generateCodeCompleted(), generatingCodeStarted(), LOG_MSG, m_project, and moduleAndChildrenUpdated().
generateCodeCompleted
void Decompiler::generateCodeCompleted () signal
Referenced by generateCode(), and MainWindow::MainWindow().
generatingCodeStarted
void Decompiler::generatingCodeStarted () signal
Referenced by generateCode(), and MainWindow::MainWindow().
getClusterFile()
QString Decompiler::getClusterFile (const QString & name)
Definition at line 278 of file Decompiler.cpp.
References m_project.
Referenced by MainWindow::on_twModuleTree_itemDoubleClicked().
getCompoundMembers()
void Decompiler::getCompoundMembers (const QString & name, QTableWidget * tbl)
Definition at line 301 of file Decompiler.cpp.
Referenced by MainWindow::on_edtStructName_returnPressed().
getProject()
Project* Decompiler::getProject () inline
Definition at line 97 of file Decompiler.h.
getRTLForProc()
bool Decompiler::getRTLForProc (const QString & name, QString & rtl)
Definition at line 229 of file Decompiler.cpp.
References m_project.
Referenced by RTLEditor::updateContents().
getSigFilePath()
QString Decompiler::getSigFilePath (const QString & name)
Definition at line 266 of file Decompiler.cpp.
References m_project.
Referenced by MainWindow::on_tblLibProcs_cellDoubleClicked().
libProcCreated
void Decompiler::libProcCreated (const QString & name, const QString & params) signal
Referenced by MainWindow::MainWindow(), and onFunctionCreated().
libProcRemoved
void Decompiler::libProcRemoved (const QString & name) signal
Referenced by MainWindow::MainWindow(), and onFunctionRemoved().
loadCompleted
void Decompiler::loadCompleted () signal
Referenced by loadInputFile(), and MainWindow::MainWindow().
loadingStarted
void Decompiler::loadingStarted () signal
Referenced by loadInputFile(), and MainWindow::MainWindow().
loadInputFile
void Decompiler::loadInputFile (const QString & inputFile, const QString & outputPath) slot
Definition at line 66 of file Decompiler.cpp.
References entryPointAdded(), INVALID, loadCompleted(), loadingStarted(), m_project, m_userEntrypoints, machineTypeChanged(), PENTIUM, PPC, sectionAdded(), SPARC, ST20, and UNKNOWN.
machineTypeChanged
void Decompiler::machineTypeChanged (const QString & machine) signal
Referenced by decode(), loadInputFile(), and MainWindow::MainWindow().
moduleAndChildrenUpdated()
void Decompiler::moduleAndChildrenUpdated (Module * root) private
After code generation, update the list of modules.
Definition at line 133 of file Decompiler.cpp.
References moduleCreated().
Referenced by generateCode().
moduleCreated
void Decompiler::moduleCreated (const QString & name) signal
Referenced by MainWindow::MainWindow(), and moduleAndChildrenUpdated().
onDecompileDebugPoint()
void Decompiler::onDecompileDebugPoint (UserProc * proc, const char * description) override virtual
IWatcher interface.
Definition at line 245 of file Decompiler.cpp.
References debugPointHit(), LOG_VERBOSE, m_debugging, and m_waiting.
onDecompileInProgress()
void Decompiler::onDecompileInProgress (UserProc * function) override virtual
Definition at line 177 of file Decompiler.cpp.
References procDecompileStarted().
onFunctionCreated()
void Decompiler::onFunctionCreated (Function * function) override virtual
Definition at line 183 of file Decompiler.cpp.
References libProcCreated(), and userProcCreated().
Referenced by onSignatureUpdated().
onFunctionDiscovered()
void Decompiler::onFunctionDiscovered (Function * function) override virtual
Definition at line 171 of file Decompiler.cpp.
References procDiscovered().
onFunctionRemoved()
void Decompiler::onFunctionRemoved (Function * function) override virtual
Definition at line 212 of file Decompiler.cpp.
References libProcRemoved(), and userProcRemoved().
onSignatureUpdated()
void Decompiler::onSignatureUpdated (Function * function) override virtual
Definition at line 223 of file Decompiler.cpp.
References onFunctionCreated().
procDecompileStarted
void Decompiler::procDecompileStarted (const QString & procName) signal
Referenced by MainWindow::MainWindow(), and onDecompileInProgress().
procDiscovered
void Decompiler::procDiscovered (const QString & callerName, const QString & procName) signal
Referenced by MainWindow::MainWindow(), and onFunctionDiscovered().
removeEntryPoint
void Decompiler::removeEntryPoint (Address entryAddr) slot
Definition at line 54 of file Decompiler.cpp.
References m_userEntrypoints.
renameProc()
void Decompiler::renameProc (const QString & oldName, const QString & newName)
Definition at line 291 of file Decompiler.cpp.
References m_project.
Referenced by MainWindow::on_tblUserProcs_cellChanged().
rereadLibSignatures
void Decompiler::rereadLibSignatures () slot
Definition at line 285 of file Decompiler.cpp.
References m_project.
sectionAdded
void Decompiler::sectionAdded (const QString & sectionName, Address start, Address end) signal
Referenced by loadInputFile(), and MainWindow::MainWindow().
setDebugEnabled()
void Decompiler::setDebugEnabled (bool debug) inline
Definition at line 96 of file Decompiler.h.
Referenced by MainWindow::on_actDebugEnabled_toggled().
stopWaiting
void Decompiler::stopWaiting () slot
Definition at line 260 of file Decompiler.cpp.
References m_waiting.
Referenced by MainWindow::on_actDebugEnabled_toggled(), and MainWindow::on_actDebugStep_triggered().
userProcCreated
void Decompiler::userProcCreated (const QString & name, Address entryAddr) signal
Referenced by MainWindow::MainWindow(), and onFunctionCreated().
userProcRemoved
void Decompiler::userProcRemoved (const QString & name, Address entryAddr) signal
Referenced by MainWindow::MainWindow(), and onFunctionRemoved().
Member Data Documentation
m_debugging
bool Decompiler::m_debugging = false protected
Definition at line 104 of file Decompiler.h.
Referenced by onDecompileDebugPoint().
m_project
Project Decompiler::m_project protected
Definition at line 107 of file Decompiler.h.
Referenced by addEntryPoint(), decode(), decompile(), Decompiler(), generateCode(), getClusterFile(), getRTLForProc(), getSigFilePath(), loadInputFile(), renameProc(), and rereadLibSignatures().
m_userEntrypoints
std::vector<Address> Decompiler::m_userEntrypoints protected
Definition at line 109 of file Decompiler.h.
Referenced by addEntryPoint(), loadInputFile(), and removeEntryPoint().
m_waiting
bool Decompiler::m_waiting = false protected
Definition at line 105 of file Decompiler.h.
Referenced by onDecompileDebugPoint(), and stopWaiting().
The documentation for this class was generated from the following files:
Decompiler.h
Decompiler.cpp