Boomerang: BranchAnalysisPass Class Reference
BranchAnalysisPass Class Reference final
Simplifies branch condions.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/passes/late/BranchAnalysisPass.h>
Public Member Functions
BranchAnalysisPass ()
bool execute (UserProc *proc) override
Run this pass, updating proc.
Public Member Functions inherited from IPass
const QString & getName () const
PassID getType () const
IPass (const QString &name, PassID type)
virtual bool isProcLocal () const
virtual ~IPass ()=default
Private Member Functions
bool doBranchAnalysis (UserProc *proc)
Look for short circuit branching.
void fixUglyBranches (UserProc *proc)
Fix any ugly branch statements (from propagating too much)
bool isOnlyBranch (BasicBlock *bb) const
Detailed Description
Simplifies branch condions.
Example: if (cond1) { if (cond2) { ... } } -> if (cond1 && cond2) { ... }
Definition at line 29 of file BranchAnalysisPass.h.
Constructor & Destructor Documentation
BranchAnalysisPass()
BranchAnalysisPass::BranchAnalysisPass ()
Definition at line 21 of file BranchAnalysisPass.cpp.
References BranchAnalysis.
Member Function Documentation
doBranchAnalysis()
bool BranchAnalysisPass::doBranchAnalysis (UserProc * proc) private
Look for short circuit branching.
Returns
true if any change
Definition at line 43 of file BranchAnalysisPass.cpp.
References a, BELSE, BTHEN, isOnlyBranch(), opAnd, opLNot, opOr, and Twoway.
Referenced by execute().
execute()
bool BranchAnalysisPass::execute (UserProc * proc) override virtual
Run this pass, updating proc.
Returns
true iff any change
Implements IPass.
Definition at line 27 of file BranchAnalysisPass.cpp.
References BlockVarRename, doBranchAnalysis(), Dominators, fixUglyBranches(), and PhiPlacement.
fixUglyBranches()
void BranchAnalysisPass::fixUglyBranches (UserProc * proc) private
Fix any ugly branch statements (from propagating too much)
Definition at line 141 of file BranchAnalysisPass.cpp.
References a, Assign, opGtrEq, opMinus, PhiAssign, and stmt.
Referenced by execute().
isOnlyBranch()
bool BranchAnalysisPass::isOnlyBranch (BasicBlock * bb) const private
Returns
true if the BB only contains a branch statement
Definition at line 182 of file BranchAnalysisPass.cpp.
Referenced by doBranchAnalysis().
The documentation for this class was generated from the following files:
BranchAnalysisPass.h
BranchAnalysisPass.cpp