Boomerang: CFGCompressor Class Reference
CFGCompressor Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/decomp/CFGCompressor.h>
Public Member Functions
bool compressCFG (ProcCFG *cfg)
Given a well-formed ProcCFG, optimizations are performed on the graph to reduce the number of basic blocks and edges.
Private Member Functions
bool removeEmptyJumps (ProcCFG *cfg)
Removes empty jumps and empty BBs.
bool removeOrphanBBs (ProcCFG *cfg)
Removes BBs that are not reachable from the entry BB.
Detailed Description
Definition at line 17 of file CFGCompressor.h.
Member Function Documentation
compressCFG()
bool CFGCompressor::compressCFG (ProcCFG * cfg)
Given a well-formed ProcCFG, optimizations are performed on the graph to reduce the number of basic blocks and edges.
Assumes that cfg is well-formed.
Optimizations performed are:
Removal of redundant jumps (e.g. remove J in A->J->B if J only contains a jump)
Removal of empty BBs (not containing any semantics), if possible
Removal of BBs not reachable from the entry BB.
See also
ProcCFG::isWellFormed
Returns
true if the ProcCFG was changed.
Definition at line 21 of file CFGCompressor.cpp.
References removeEmptyJumps(), and removeOrphanBBs().
Referenced by StatementInitPass::execute().
removeEmptyJumps()
bool CFGCompressor::removeEmptyJumps (ProcCFG * cfg) private
Removes empty jumps and empty BBs.
Definition at line 38 of file CFGCompressor.cpp.
Referenced by compressCFG().
removeOrphanBBs()
bool CFGCompressor::removeOrphanBBs (ProcCFG * cfg) private
Removes BBs that are not reachable from the entry BB.
Definition at line 84 of file CFGCompressor.cpp.
References Ret.
Referenced by compressCFG().
The documentation for this class was generated from the following files:
CFGCompressor.h
CFGCompressor.cpp