Boomerang: MainWindow Class Reference
MainWindow Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang-gui/MainWindow.h>
Public Slots
void closeCurrentTab ()
void currentTabTextChanged ()
void decodeComplete ()
void decompileComplete ()
void generateCodeComplete ()
void loadComplete ()
void on_actAboutBoomerang_triggered ()
void on_actAboutQt_triggered ()
void on_actBoomerangWebsite_triggered ()
void on_actCloseProject_triggered ()
void on_actCopy_triggered ()
void on_actCut_triggered ()
void on_actDebugEnabled_toggled (bool b)
void on_actDebugStep_triggered ()
void on_actDecode_triggered ()
void on_actDecompile_triggered ()
void on_actDelete_triggered ()
void on_actFind_triggered ()
void on_actFindNext_triggered ()
void on_actGenerateCode_triggered ()
void on_actGoTo_triggered ()
void on_actLoad_triggered ()
void on_actNewProject_triggered ()
void on_actPaste_triggered ()
void on_actSaveProject_triggered ()
void on_actSelectAll_triggered ()
void on_actStructs_triggered ()
void on_btnEntryPointAdd_pressed ()
void on_btnEntryPointRemove_pressed ()
void on_btnInputFileBrowse_clicked ()
void on_btnOutputPathBrowse_clicked ()
void on_cbInputFile_currentIndexChanged (const QString &text)
void on_cbOutputPath_currentIndexChanged (const QString &text)
void on_edtStructName_returnPressed ()
void on_tabWidget_currentChanged (int index)
void on_tblEntryPoints_currentItemChanged (QTableWidgetItem *current, QTableWidgetItem *previous)
void on_tblLibProcs_cellDoubleClicked (int row, int column)
void on_tblUserProcs_cellChanged (int row, int column)
void on_tblUserProcs_cellDoubleClicked (int row, int column)
void on_twModuleTree_itemDoubleClicked (QTreeWidgetItem *item, int column)
void on_twProcTree_itemDoubleClicked (QTreeWidgetItem *item, int column)
void onUserProcsHorizontalHeaderSectionClicked (int logicalIndex)
void showConsideringProc (const QString &parent, const QString &name)
void showDebuggingPoint (const QString &name, const QString &description)
void showDecodePage ()
void showDecompilePage ()
void showDecompilingProc (const QString &name)
void showGenerateCodePage ()
void showLoadPage ()
void showMachineType (const QString &machine)
void showNewCluster (const QString &name)
void showNewEntrypoint (Address addr, const QString &name)
void showNewLibProc (const QString &name, const QString &params)
void showNewProcInCluster (const QString &name, const QString &cluster)
void showNewSection (const QString &name, Address start, Address end)
void showNewUserProc (const QString &name, Address addr)
void showRemoveLibProc (const QString &name)
void showRemoveUserProc (const QString &name, Address addr)
void showRTLEditor (const QString &name)
Signals
void entryPointAdded (Address entryAddr, const QString &name)
void entryPointRemoved (Address entryAddr)
void librarySignaturesOutdated ()
Public Member Functions
void errorLoadingFile ()
MainWindow (QWidget *parent=nullptr)
~MainWindow ()
Protected Member Functions
void saveSettings ()
void showInitPage ()
Private Slots
void on_actSettings_triggered ()
Private Attributes
QToolButton * m_debugStep = nullptr
Decompiler * m_decompiler = nullptr
QThread m_decompilerThread
bool m_loadingSettings = false
int m_numCodeGenProcs = 0
int m_numDecompiledProcs = 0
std::map< QWidget *, QString > m_openFiles
std::set< QWidget * > m_signatureFiles
QWidget * m_structsView = nullptr
Ui::MainWindow * ui = nullptr
Detailed Description
Definition at line 33 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Definition at line 27 of file MainWindow.cpp.
References closeCurrentTab(), Decompiler::debugPointHit(), decodeComplete(), Decompiler::decodeCompleted(), Decompiler::decodingStarted(), decompileComplete(), Decompiler::decompileCompleted(), Decompiler::decompilingStarted(), entryPointAdded(), Decompiler::entryPointAdded(), entryPointRemoved(), Decompiler::functionAddedToModule(), generateCodeComplete(), Decompiler::generateCodeCompleted(), Decompiler::generatingCodeStarted(), Decompiler::libProcCreated(), Decompiler::libProcRemoved(), librarySignaturesOutdated(), loadComplete(), Decompiler::loadCompleted(), Decompiler::loadingStarted(), m_decompiler, m_decompilerThread, m_loadingSettings, m_structsView, Decompiler::machineTypeChanged(), Decompiler::moduleCreated(), onUserProcsHorizontalHeaderSectionClicked(), Decompiler::procDecompileStarted(), Decompiler::procDiscovered(), Decompiler::sectionAdded(), showConsideringProc(), showDebuggingPoint(), showDecodePage(), showDecompilePage(), showDecompilingProc(), showGenerateCodePage(), showInitPage(), showLoadPage(), showMachineType(), showNewCluster(), showNewEntrypoint(), showNewLibProc(), showNewProcInCluster(), showNewSection(), showNewUserProc(), showRemoveLibProc(), showRemoveUserProc(), ui, Decompiler::userProcCreated(), and Decompiler::userProcRemoved().
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 138 of file MainWindow.cpp.
References m_decompiler, m_decompilerThread, and ui.
Member Function Documentation
closeCurrentTab
void MainWindow::closeCurrentTab () slot
Definition at line 255 of file MainWindow.cpp.
References m_openFiles, on_actCloseProject_triggered(), and ui.
Referenced by MainWindow().
currentTabTextChanged
void MainWindow::currentTabTextChanged () slot
Definition at line 266 of file MainWindow.cpp.
References ui.
Referenced by on_tblLibProcs_cellDoubleClicked(), and on_twModuleTree_itemDoubleClicked().
decodeComplete
void MainWindow::decodeComplete () slot
Definition at line 437 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
decompileComplete
void MainWindow::decompileComplete () slot
Definition at line 452 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
entryPointAdded
void MainWindow::entryPointAdded (Address entryAddr, const QString & name) signal
Referenced by MainWindow(), and on_btnEntryPointAdd_pressed().
entryPointRemoved
void MainWindow::entryPointRemoved (Address entryAddr) signal
Referenced by MainWindow(), and on_btnEntryPointRemove_pressed().
errorLoadingFile()
void MainWindow::errorLoadingFile ()
Definition at line 299 of file MainWindow.cpp.
generateCodeComplete
void MainWindow::generateCodeComplete () slot
Definition at line 467 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
librarySignaturesOutdated
void MainWindow::librarySignaturesOutdated () signal
Referenced by MainWindow().
loadComplete
void MainWindow::loadComplete () slot
Definition at line 403 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
on_actAboutBoomerang_triggered
void MainWindow::on_actAboutBoomerang_triggered () slot
Definition at line 1039 of file MainWindow.cpp.
on_actAboutQt_triggered
void MainWindow::on_actAboutQt_triggered () slot
Definition at line 1049 of file MainWindow.cpp.
on_actBoomerangWebsite_triggered
void MainWindow::on_actBoomerangWebsite_triggered () slot
Definition at line 1033 of file MainWindow.cpp.
on_actCloseProject_triggered
void MainWindow::on_actCloseProject_triggered () slot
Definition at line 288 of file MainWindow.cpp.
Referenced by closeCurrentTab().
on_actCopy_triggered
void MainWindow::on_actCopy_triggered () slot
Definition at line 926 of file MainWindow.cpp.
References ui.
on_actCut_triggered
void MainWindow::on_actCut_triggered () slot
Definition at line 914 of file MainWindow.cpp.
References ui.
on_actDebugEnabled_toggled
void MainWindow::on_actDebugEnabled_toggled (bool b) slot
Definition at line 776 of file MainWindow.cpp.
References m_debugStep, m_decompiler, Decompiler::setDebugEnabled(), Decompiler::stopWaiting(), and ui.
on_actDebugStep_triggered
void MainWindow::on_actDebugStep_triggered () slot
Definition at line 803 of file MainWindow.cpp.
References m_decompiler, Decompiler::stopWaiting(), and ui.
Referenced by showDebuggingPoint().
on_actDecode_triggered
void MainWindow::on_actDecode_triggered () slot
Definition at line 996 of file MainWindow.cpp.
References showDecodePage().
on_actDecompile_triggered
void MainWindow::on_actDecompile_triggered () slot
Definition at line 1002 of file MainWindow.cpp.
References showDecompilePage().
on_actDelete_triggered
void MainWindow::on_actDelete_triggered () slot
Definition at line 950 of file MainWindow.cpp.
References ui.
on_actFind_triggered
void MainWindow::on_actFind_triggered () slot
Definition at line 962 of file MainWindow.cpp.
on_actFindNext_triggered
void MainWindow::on_actFindNext_triggered () slot
Definition at line 967 of file MainWindow.cpp.
on_actGenerateCode_triggered
void MainWindow::on_actGenerateCode_triggered () slot
Definition at line 1008 of file MainWindow.cpp.
References showGenerateCodePage().
on_actGoTo_triggered
void MainWindow::on_actGoTo_triggered () slot
Definition at line 972 of file MainWindow.cpp.
on_actLoad_triggered
void MainWindow::on_actLoad_triggered () slot
Definition at line 989 of file MainWindow.cpp.
References saveSettings(), and showLoadPage().
on_actNewProject_triggered
void MainWindow::on_actNewProject_triggered () slot
Definition at line 276 of file MainWindow.cpp.
on_actPaste_triggered
void MainWindow::on_actPaste_triggered () slot
Definition at line 938 of file MainWindow.cpp.
References ui.
on_actSaveProject_triggered
void MainWindow::on_actSaveProject_triggered () slot
Definition at line 282 of file MainWindow.cpp.
on_actSelectAll_triggered
void MainWindow::on_actSelectAll_triggered () slot
Definition at line 977 of file MainWindow.cpp.
References ui.
on_actSettings_triggered
void MainWindow::on_actSettings_triggered () private slot
Definition at line 1100 of file MainWindow.cpp.
References m_decompiler.
on_actStructs_triggered
void MainWindow::on_actStructs_triggered () slot
Definition at line 1014 of file MainWindow.cpp.
References m_structsView, and ui.
on_btnEntryPointAdd_pressed
void MainWindow::on_btnEntryPointAdd_pressed () slot
Definition at line 1061 of file MainWindow.cpp.
References a, entryPointAdded(), and ui.
on_btnEntryPointRemove_pressed
void MainWindow::on_btnEntryPointRemove_pressed () slot
Definition at line 1085 of file MainWindow.cpp.
References a, entryPointRemoved(), and ui.
on_btnInputFileBrowse_clicked
void MainWindow::on_btnInputFileBrowse_clicked () slot
Definition at line 178 of file MainWindow.cpp.
References saveSettings(), and ui.
on_btnOutputPathBrowse_clicked
void MainWindow::on_btnOutputPathBrowse_clicked () slot
Definition at line 217 of file MainWindow.cpp.
References saveSettings(), and ui.
on_cbInputFile_currentIndexChanged
void MainWindow::on_cbInputFile_currentIndexChanged (const QString & text) slot
Definition at line 243 of file MainWindow.cpp.
References saveSettings().
on_cbOutputPath_currentIndexChanged
void MainWindow::on_cbOutputPath_currentIndexChanged (const QString & text) slot
Definition at line 249 of file MainWindow.cpp.
References saveSettings().
on_edtStructName_returnPressed
void MainWindow::on_edtStructName_returnPressed () slot
Definition at line 1027 of file MainWindow.cpp.
References Decompiler::getCompoundMembers(), m_decompiler, and ui.
on_tabWidget_currentChanged
void MainWindow::on_tabWidget_currentChanged (int index) slot
Definition at line 294 of file MainWindow.cpp.
on_tblEntryPoints_currentItemChanged
void MainWindow::on_tblEntryPoints_currentItemChanged (QTableWidgetItem * current, QTableWidgetItem * previous) slot
Definition at line 1055 of file MainWindow.cpp.
References ui.
on_tblLibProcs_cellDoubleClicked
void MainWindow::on_tblLibProcs_cellDoubleClicked (int row, int column) slot
Definition at line 826 of file MainWindow.cpp.
References currentTabTextChanged(), Decompiler::getSigFilePath(), m_decompiler, m_openFiles, m_signatureFiles, and ui.
on_tblUserProcs_cellChanged
void MainWindow::on_tblUserProcs_cellChanged (int row, int column) slot
Definition at line 711 of file MainWindow.cpp.
References m_decompiler, Decompiler::renameProc(), and ui.
on_tblUserProcs_cellDoubleClicked
void MainWindow::on_tblUserProcs_cellDoubleClicked (int row, int column) slot
Definition at line 704 of file MainWindow.cpp.
References showRTLEditor(), and ui.
on_twModuleTree_itemDoubleClicked
void MainWindow::on_twModuleTree_itemDoubleClicked (QTreeWidgetItem * item, int column) slot
Definition at line 726 of file MainWindow.cpp.
References currentTabTextChanged(), Decompiler::getClusterFile(), m_decompiler, m_openFiles, and ui.
on_twProcTree_itemDoubleClicked
void MainWindow::on_twProcTree_itemDoubleClicked (QTreeWidgetItem * item, int column) slot
Definition at line 769 of file MainWindow.cpp.
References showRTLEditor().
onUserProcsHorizontalHeaderSectionClicked
void MainWindow::onUserProcsHorizontalHeaderSectionClicked (int logicalIndex) slot
Definition at line 810 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
saveSettings()
void MainWindow::saveSettings () protected
Definition at line 148 of file MainWindow.cpp.
References m_loadingSettings, and ui.
Referenced by on_actLoad_triggered(), on_btnInputFileBrowse_clicked(), on_btnOutputPathBrowse_clicked(), on_cbInputFile_currentIndexChanged(), and on_cbOutputPath_currentIndexChanged().
showConsideringProc
void MainWindow::showConsideringProc (const QString & parent, const QString & name) slot
Definition at line 483 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showDebuggingPoint
void MainWindow::showDebuggingPoint (const QString & name, const QString & description) slot
Definition at line 658 of file MainWindow.cpp.
References on_actDebugStep_triggered(), showRTLEditor(), and ui.
Referenced by MainWindow().
showDecodePage
void MainWindow::showDecodePage () slot
Definition at line 348 of file MainWindow.cpp.
References ui.
Referenced by MainWindow(), and on_actDecode_triggered().
showDecompilePage
void MainWindow::showDecompilePage () slot
Definition at line 372 of file MainWindow.cpp.
References ui.
Referenced by MainWindow(), and on_actDecompile_triggered().
showDecompilingProc
void MainWindow::showDecompilingProc (const QString & name) slot
Definition at line 510 of file MainWindow.cpp.
References m_numDecompiledProcs, and ui.
Referenced by MainWindow().
showGenerateCodePage
void MainWindow::showGenerateCodePage () slot
Definition at line 388 of file MainWindow.cpp.
References ui.
Referenced by MainWindow(), and on_actGenerateCode_triggered().
showInitPage()
void MainWindow::showInitPage () protected
Definition at line 304 of file MainWindow.cpp.
References m_numCodeGenProcs, m_numDecompiledProcs, and ui.
Referenced by MainWindow().
showLoadPage
void MainWindow::showLoadPage () slot
Definition at line 333 of file MainWindow.cpp.
References ui.
Referenced by MainWindow(), and on_actLoad_triggered().
showMachineType
void MainWindow::showMachineType (const QString & machine) slot
Definition at line 419 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showNewCluster
void MainWindow::showNewCluster (const QString & name) slot
Definition at line 629 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showNewEntrypoint
void MainWindow::showNewEntrypoint (Address addr, const QString & name) slot
Definition at line 425 of file MainWindow.cpp.
References addr, and ui.
Referenced by MainWindow().
showNewLibProc
void MainWindow::showNewLibProc (const QString & name, const QString & params) slot
Definition at line 561 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showNewProcInCluster
void MainWindow::showNewProcInCluster (const QString & name, const QString & cluster) slot
Definition at line 640 of file MainWindow.cpp.
References m_numCodeGenProcs, and ui.
Referenced by MainWindow().
showNewSection
void MainWindow::showNewSection (const QString & name, Address start, Address end) slot
Definition at line 615 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showNewUserProc
void MainWindow::showNewUserProc (const QString & name, Address addr) slot
Definition at line 527 of file MainWindow.cpp.
References addr, and ui.
Referenced by MainWindow().
showRemoveLibProc
void MainWindow::showRemoveLibProc (const QString & name) slot
Definition at line 599 of file MainWindow.cpp.
References ui.
Referenced by MainWindow().
showRemoveUserProc
void MainWindow::showRemoveUserProc (const QString & name, Address addr) slot
Definition at line 580 of file MainWindow.cpp.
References addr, and ui.
Referenced by MainWindow().
showRTLEditor
void MainWindow::showRTLEditor (const QString & name) slot
Definition at line 681 of file MainWindow.cpp.
References m_decompiler, ui, and RTLEditor::updateContents().
Referenced by on_tblUserProcs_cellDoubleClicked(), on_twProcTree_itemDoubleClicked(), and showDebuggingPoint().
Member Data Documentation
m_debugStep
QToolButton* MainWindow::m_debugStep = nullptr private
Definition at line 137 of file MainWindow.h.
Referenced by on_actDebugEnabled_toggled().
m_decompiler
Decompiler* MainWindow::m_decompiler = nullptr private
Definition at line 128 of file MainWindow.h.
Referenced by MainWindow(), on_actDebugEnabled_toggled(), on_actDebugStep_triggered(), on_actSettings_triggered(), on_edtStructName_returnPressed(), on_tblLibProcs_cellDoubleClicked(), on_tblUserProcs_cellChanged(), on_twModuleTree_itemDoubleClicked(), showRTLEditor(), and ~MainWindow().
m_decompilerThread
QThread MainWindow::m_decompilerThread private
Definition at line 127 of file MainWindow.h.
Referenced by MainWindow(), and ~MainWindow().
m_loadingSettings
bool MainWindow::m_loadingSettings = false private
Definition at line 130 of file MainWindow.h.
Referenced by MainWindow(), and saveSettings().
m_numCodeGenProcs
int MainWindow::m_numCodeGenProcs = 0 private
Definition at line 132 of file MainWindow.h.
Referenced by showInitPage(), and showNewProcInCluster().
m_numDecompiledProcs
int MainWindow::m_numDecompiledProcs = 0 private
Definition at line 131 of file MainWindow.h.
Referenced by showDecompilingProc(), and showInitPage().
m_openFiles
std::map<QWidget *, QString> MainWindow::m_openFiles private
Definition at line 134 of file MainWindow.h.
Referenced by closeCurrentTab(), on_tblLibProcs_cellDoubleClicked(), and on_twModuleTree_itemDoubleClicked().
m_signatureFiles
std::set<QWidget *> MainWindow::m_signatureFiles private
Definition at line 135 of file MainWindow.h.
Referenced by on_tblLibProcs_cellDoubleClicked().
m_structsView
QWidget* MainWindow::m_structsView = nullptr private
Definition at line 138 of file MainWindow.h.
Referenced by MainWindow(), and on_actStructs_triggered().
ui
Ui::MainWindow* MainWindow::ui = nullptr private
Definition at line 125 of file MainWindow.h.
Referenced by closeCurrentTab(), currentTabTextChanged(), decodeComplete(), decompileComplete(), generateCodeComplete(), loadComplete(), MainWindow(), on_actCopy_triggered(), on_actCut_triggered(), on_actDebugEnabled_toggled(), on_actDebugStep_triggered(), on_actDelete_triggered(), on_actPaste_triggered(), on_actSelectAll_triggered(), on_actStructs_triggered(), on_btnEntryPointAdd_pressed(), on_btnEntryPointRemove_pressed(), on_btnInputFileBrowse_clicked(), on_btnOutputPathBrowse_clicked(), on_edtStructName_returnPressed(), on_tblEntryPoints_currentItemChanged(), on_tblLibProcs_cellDoubleClicked(), on_tblUserProcs_cellChanged(), on_tblUserProcs_cellDoubleClicked(), on_twModuleTree_itemDoubleClicked(), onUserProcsHorizontalHeaderSectionClicked(), saveSettings(), showConsideringProc(), showDebuggingPoint(), showDecodePage(), showDecompilePage(), showDecompilingProc(), showGenerateCodePage(), showInitPage(), showLoadPage(), showMachineType(), showNewCluster(), showNewEntrypoint(), showNewLibProc(), showNewProcInCluster(), showNewSection(), showNewUserProc(), showRemoveLibProc(), showRemoveUserProc(), showRTLEditor(), and ~MainWindow().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp