Boomerang: StmtSet< T, Sorter, Enabler > Class Template Reference
StmtSet< T, Sorter, Enabler > Class Template Reference
This class implements an ordered or unordered set of statements.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/StatementSet.h>
Public Types
typedef Set::const_iterator const_iterator
typedef Set::iterator iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
void clear ()
bool contains (T *stmt) const
bool definesLoc (SharedExp loc) const
bool empty () const
iterator end ()
const_iterator end () const
void insert (T *stmt)
bool isSubSetOf (const StmtSet &other)
template<typename = std::enable_if<std::is_base_of<Assign, T>::value>>
Assign * lookupLoc (SharedExp loc)
Find a definition for loc on the LHS of each assignment in this set.
void makeDiff (const StmtSet &other)
Set difference: this = this - other.
void makeIsect (const StmtSet &other)
Set intersection: this = this intersect other.
void makeUnion (const StmtSet &other)
Set union: this = this union other.
bool remove (T *s)
Remove this Statement.
int size () const
Private Types
using Set = typename std::conditional< std::is_void< Sorter >::value, std::unordered_set< T * >, std::set< T *, Sorter > >::type
Private Attributes
Set m_set
Detailed Description
template<typename T, typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>>
class StmtSet< T, Sorter, Enabler >
This class implements an ordered or unordered set of statements.
Template Parameters
T Statement type (Statement, Assign, CallStatement etc.)
Sorter Binary functor type that defines the sorting order. If Sorter == void, the set is unordered.
Definition at line 31 of file StatementSet.h.
Member Typedef Documentation
const_iterator
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> typedef Set::const_iterator StmtSet< T, Sorter, Enabler >::const_iterator
Definition at line 38 of file StatementSet.h.
iterator
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> typedef Set::iterator StmtSet< T, Sorter, Enabler >::iterator
Definition at line 37 of file StatementSet.h.
Set
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> using StmtSet< T, Sorter, Enabler >::Set = typename std::conditional<std::is_void<Sorter>::value, std::unordered_set<T *>, std::set<T *, Sorter> >::type private
Definition at line 34 of file StatementSet.h.
Member Function Documentation
begin() [1/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> iterator StmtSet< T, Sorter, Enabler >::begin () inline
Definition at line 41 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
begin() [2/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> const_iterator StmtSet< T, Sorter, Enabler >::begin () const inline
Definition at line 44 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
clear()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> void StmtSet< T, Sorter, Enabler >::clear () inline
Definition at line 49 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
contains()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> bool StmtSet< T, Sorter, Enabler >::contains (T * stmt) const inline
Definition at line 70 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set, and stmt.
Referenced by StmtSet< T, Sorter, Enabler >::isSubSetOf(), StmtSet< T, Sorter, Enabler >::makeIsect(), and StmtSet< T, Sorter, Enabler >::remove().
definesLoc()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> bool StmtSet< T, Sorter, Enabler >::definesLoc (SharedExp loc) const inline
Returns
true if any statement in this set defines loc
Definition at line 74 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set, and stmt.
empty()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> bool StmtSet< T, Sorter, Enabler >::empty () const inline
Definition at line 48 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
end() [1/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> iterator StmtSet< T, Sorter, Enabler >::end () inline
Definition at line 42 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
Referenced by StmtSet< T, Sorter, Enabler >::lookupLoc().
end() [2/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> const_iterator StmtSet< T, Sorter, Enabler >::end () const inline
Definition at line 45 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
insert()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> void StmtSet< T, Sorter, Enabler >::insert (T * stmt) inline
Definition at line 52 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set, and stmt.
Referenced by UnusedStatementRemovalPass::remUnusedStmtEtc().
isSubSetOf()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> bool StmtSet< T, Sorter, Enabler >::isSubSetOf (const StmtSet< T, Sorter, Enabler > & other) inline
Returns
true if this set is a subset of other
Definition at line 85 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::contains(), StmtSet< T, Sorter, Enabler >::m_set, and stmt.
lookupLoc()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> template<typename = std::enable_if<std::is_base_of<Assign, T>::value>> Assign* StmtSet< T, Sorter, Enabler >::lookupLoc (SharedExp loc) inline
Find a definition for loc on the LHS of each assignment in this set.
If found, return pointer to the Assign with that LHS (else return nullptr)
Definition at line 138 of file StatementSet.h.
References Assign, StmtSet< T, Sorter, Enabler >::end(), StmtSet< T, Sorter, Enabler >::m_set, and opWild.
makeDiff()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> void StmtSet< T, Sorter, Enabler >::makeDiff (const StmtSet< T, Sorter, Enabler > & other) inline
Set difference: this = this - other.
Definition at line 123 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set, and stmt.
makeIsect()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> void StmtSet< T, Sorter, Enabler >::makeIsect (const StmtSet< T, Sorter, Enabler > & other) inline
Set intersection: this = this intersect other.
Definition at line 109 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::contains(), and StmtSet< T, Sorter, Enabler >::m_set.
makeUnion()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> void StmtSet< T, Sorter, Enabler >::makeUnion (const StmtSet< T, Sorter, Enabler > & other) inline
Set union: this = this union other.
Definition at line 101 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set, and stmt.
remove()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> bool StmtSet< T, Sorter, Enabler >::remove (T * s) inline
Remove this Statement.
Returns
true if removed, false if not found
Definition at line 60 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::contains(), and StmtSet< T, Sorter, Enabler >::m_set.
size()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> int StmtSet< T, Sorter, Enabler >::size () const inline
Definition at line 50 of file StatementSet.h.
References StmtSet< T, Sorter, Enabler >::m_set.
Member Data Documentation
m_set
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Statement, T>::value>> Set StmtSet< T, Sorter, Enabler >::m_set private
Definition at line 151 of file StatementSet.h.
Referenced by StmtSet< T, Sorter, Enabler >::begin(), StmtSet< T, Sorter, Enabler >::clear(), StmtSet< T, Sorter, Enabler >::contains(), StmtSet< T, Sorter, Enabler >::definesLoc(), StmtSet< T, Sorter, Enabler >::empty(), StmtSet< T, Sorter, Enabler >::end(), StmtSet< T, Sorter, Enabler >::insert(), StmtSet< T, Sorter, Enabler >::isSubSetOf(), StmtSet< T, Sorter, Enabler >::lookupLoc(), StmtSet< T, Sorter, Enabler >::makeDiff(), StmtSet< T, Sorter, Enabler >::makeIsect(), StmtSet< T, Sorter, Enabler >::makeUnion(), StmtSet< T, Sorter, Enabler >::remove(), and StmtSet< T, Sorter, Enabler >::size().
The documentation for this class was generated from the following file:
StatementSet.h