Boomerang: InterferenceFinder Class Reference
InterferenceFinder Class Reference
Finds the interferences generated by more than one version of a variable being live at the same program point.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/decomp/InterferenceFinder.h>
Public Member Functions
void findInterferences (ConnectionGraph &interferences)
InterferenceFinder (ProcCFG *cfg)
Private Member Functions
void appendBBs (std::list< BasicBlock * > &worklist, std::set< BasicBlock * > &workset)
void updateWorkListRev (BasicBlock *currBB, std::list< BasicBlock * > &workList, std::set< BasicBlock * > &workSet)
Private Attributes
ProcCFG * m_cfg
LivenessAnalyzer m_livenessAna
Detailed Description
Finds the interferences generated by more than one version of a variable being live at the same program point.
Definition at line 26 of file InterferenceFinder.h.
Constructor & Destructor Documentation
InterferenceFinder()
InterferenceFinder::InterferenceFinder (ProcCFG * cfg)
Definition at line 21 of file InterferenceFinder.cpp.
Member Function Documentation
appendBBs()
void InterferenceFinder::appendBBs (std::list< BasicBlock * > & worklist, std::set< BasicBlock * > & workset) private
Definition at line 78 of file InterferenceFinder.cpp.
References m_cfg.
Referenced by findInterferences().
findInterferences()
void InterferenceFinder::findInterferences (ConnectionGraph & interferences)
Definition at line 27 of file InterferenceFinder.cpp.
References appendBBs(), LivenessAnalyzer::calcLiveness(), LOG_MSG, m_cfg, m_livenessAna, and updateWorkListRev().
Referenced by FromSSAFormPass::execute().
updateWorkListRev()
void InterferenceFinder::updateWorkListRev (BasicBlock * currBB, std::list< BasicBlock * > & workList, std::set< BasicBlock * > & workSet) private
Definition at line 65 of file InterferenceFinder.cpp.
Referenced by findInterferences().
Member Data Documentation
m_cfg
ProcCFG* InterferenceFinder::m_cfg private
Definition at line 41 of file InterferenceFinder.h.
Referenced by appendBBs(), and findInterferences().
m_livenessAna
LivenessAnalyzer InterferenceFinder::m_livenessAna private
Definition at line 42 of file InterferenceFinder.h.
Referenced by findInterferences().
The documentation for this class was generated from the following files:
InterferenceFinder.h
InterferenceFinder.cpp