Boomerang: ExpSimplifier Class Reference
ExpSimplifier Class Reference
Simplifies expressions into a canonical form.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/expmodifier/ExpSimplifier.h>
Public Member Functions
ExpSimplifier ()=default
SharedExp postModify (const std::shared_ptr< Binary > &exp) override
SharedExp postModify (const std::shared_ptr< Location > &exp) override
SharedExp postModify (const std::shared_ptr< RefExp > &exp) override
SharedExp postModify (const std::shared_ptr< Ternary > &exp) override
SharedExp postModify (const std::shared_ptr< Unary > &exp) override
SharedExp preModify (const std::shared_ptr< TypedExp > &exp, bool &visitChildren) override
virtual ~ExpSimplifier ()=default
Detailed Description
Simplifies expressions into a canonical form.
Non-exhaustive list of transformations applied:
Integer and boolean constant folding
Swapping commutative expressions such that the constant is on the RHS
Folding of always-true or always-false expressions
Folding of constant ternary expressions
Replacing left/right shift by multiplication/division
Read the code and the tests for full details.
See also
Exp::simplify
Definition at line 28 of file ExpSimplifier.h.
Constructor & Destructor Documentation
ExpSimplifier()
ExpSimplifier::ExpSimplifier () default
~ExpSimplifier()
virtual ExpSimplifier::~ExpSimplifier () virtual default
Member Function Documentation
postModify() [1/5]
SharedExp ExpSimplifier::postModify (const std::shared_ptr< Binary > & exp) override
Definition at line 118 of file ExpSimplifier.cpp.
References a, exp, Util::getLowerBitMask(), Util::inRange(), opAnd, opBitAnd, opBitOr, opBitXor, opDiv, opDivs, opEquals, opFalse, opFMinus, opFNeg, opGtr, opGtrEq, opGtrEqUns, opGtrUns, opIntConst, opLess, opLessEq, opLessEqUns, opLessUns, opLNot, opMinus, opMod, opMods, opMult, opMults, opNeg, opNotEqual, opOr, opPlus, opShL, opShR, opShRA, and opTrue.
postModify() [2/5]
SharedExp ExpSimplifier::postModify (const std::shared_ptr< Location > & exp) override
Definition at line 830 of file ExpSimplifier.cpp.
References exp.
postModify() [3/5]
SharedExp ExpSimplifier::postModify (const std::shared_ptr< RefExp > & exp) override
Definition at line 843 of file ExpSimplifier.cpp.
References exp, and opDF.
postModify() [4/5]
SharedExp ExpSimplifier::postModify (const std::shared_ptr< Ternary > & exp) override
sign-extend constant value
Definition at line 660 of file ExpSimplifier.cpp.
References exp, Util::getLowerBitMask(), LOG_VERBOSE, opAt, opEquals, opFsize, opItof, opNotEqual, opSgnEx, opTern, opTruncs, opTruncu, and opZfill.
postModify() [5/5]
SharedExp ExpSimplifier::postModify (const std::shared_ptr< Unary > & exp) override
Definition at line 25 of file ExpSimplifier.cpp.
References exp, opAnd, opBitAnd, opBitNot, opBitOr, opEquals, opGtr, opGtrEq, opGtrEqUns, opGtrUns, opLess, opLessEq, opLessEqUns, opLessUns, opLNot, opNeg, opNotEqual, and opOr.
preModify()
SharedExp ExpSimplifier::preModify (const std::shared_ptr< TypedExp > & exp, bool & visitChildren) override
Definition at line 816 of file ExpSimplifier.cpp.
References exp.
The documentation for this class was generated from the following files:
ExpSimplifier.h
ExpSimplifier.cpp