Boomerang: CallingConvention::Win32TcSignature Class Reference
CallingConvention::Win32TcSignature Class Reference
Win32Signature is for __stdcall calling convention: parameters pushed right-to-left, return value in eax register.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/db/signature/Win32Signature.h>
Public Member Functions
virtual std::shared_ptr< Signature > clone () const override
virtual SharedExp getArgumentExp (int n) const override
virtual CallConv getConvention () const override
virtual SharedExp getProven (SharedExp left) const override
Win32TcSignature (const QString &name)
Win32TcSignature (Signature &old)
Detailed Description
Win32Signature is for __stdcall calling convention: parameters pushed right-to-left, return value in eax register.
Win32TcSignature is for "thiscall" signatures, i.e. those that have register ecx as the first parameter. Only needs to override a few member functions; the rest can inherit from Win32Signature
Definition at line 77 of file Win32Signature.h.
Constructor & Destructor Documentation
Win32TcSignature() [1/2]
CallingConvention::Win32TcSignature::Win32TcSignature (const QString & name) explicit
Definition at line 39 of file Win32Signature.cpp.
References REG_PENT_ECX.
Referenced by clone().
Win32TcSignature() [2/2]
CallingConvention::Win32TcSignature::Win32TcSignature (Signature & old) explicit
Definition at line 47 of file Win32Signature.cpp.
Member Function Documentation
clone()
std::shared_ptr< Signature > CallingConvention::Win32TcSignature::clone () const override virtual
Definition at line 68 of file Win32Signature.cpp.
References Util::clone(), and Win32TcSignature().
getArgumentExp()
SharedExp CallingConvention::Win32TcSignature::getArgumentExp (int n) const override virtual
Definition at line 164 of file Win32Signature.cpp.
References opPlus, REG_PENT_ECX, and REG_PENT_ESP.
getConvention()
virtual CallConv CallingConvention::Win32TcSignature::getConvention () const inline override virtual
Definition at line 94 of file Win32Signature.h.
References ThisCall.
getProven()
SharedExp CallingConvention::Win32TcSignature::getProven (SharedExp left) const override virtual
Definition at line 264 of file Win32Signature.cpp.
References opPlus, and REG_PENT_ESP.
The documentation for this class was generated from the following files:
Win32Signature.h
Win32Signature.cpp