Boomerang: IntervalSet< T > Class Template Reference
IntervalSet< T > Class Template Reference
An IntervalSet implements a set as a set of intervals, merging adjoining intervals.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/IntervalSet.h>
Public Types
typedef Data::const_iterator const_iterator
typedef Data::const_reverse_iterator const_reverse_iterator
typedef std::set< Interval< T >, std::less< Interval< T > > > Data
typedef Data::iterator iterator
typedef Data::reverse_iterator reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
void clear ()
Removes all intervals from the set.
iterator end ()
const_iterator end () const
std::pair< iterator, iterator > equalRange (const Interval< T > &interval)
std::pair< iterator, iterator > equalRange (const T &lower, const T &upper)
Returns an iterator range containing all intervals between lower and upper.
iterator insert (const Interval< T > &interval)
iterator insert (const T &from, const T &to)
bool isContained (const T &value) const
bool isEmpty () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
Private Attributes
Data m_data
Detailed Description
template<typename T>
class IntervalSet< T >
An IntervalSet implements a set as a set of intervals, merging adjoining intervals.
Definition at line 22 of file IntervalSet.h.
Member Typedef Documentation
const_iterator
template<typename T > typedef Data::const_iterator IntervalSet< T >::const_iterator
Definition at line 28 of file IntervalSet.h.
const_reverse_iterator
template<typename T > typedef Data::const_reverse_iterator IntervalSet< T >::const_reverse_iterator
Definition at line 30 of file IntervalSet.h.
Data
template<typename T > typedef std::set<Interval<T>, std::less<Interval<T> > > IntervalSet< T >::Data
Definition at line 25 of file IntervalSet.h.
iterator
template<typename T > typedef Data::iterator IntervalSet< T >::iterator
Definition at line 27 of file IntervalSet.h.
reverse_iterator
template<typename T > typedef Data::reverse_iterator IntervalSet< T >::reverse_iterator
Definition at line 29 of file IntervalSet.h.
Member Function Documentation
begin() [1/2]
template<typename T > iterator IntervalSet< T >::begin () inline
Definition at line 33 of file IntervalSet.h.
Referenced by IntervalSet< Address >::equalRange().
begin() [2/2]
template<typename T > const_iterator IntervalSet< T >::begin () const inline
Definition at line 35 of file IntervalSet.h.
clear()
template<typename T > void IntervalSet< T >::clear () inline
Removes all intervals from the set.
Definition at line 47 of file IntervalSet.h.
Referenced by BinarySectionImpl::clearDefinedArea().
end() [1/2]
template<typename T > iterator IntervalSet< T >::end () inline
Definition at line 34 of file IntervalSet.h.
Referenced by IntervalSet< Address >::equalRange(), IntervalSet< Address >::insert(), and IntervalSet< Address >::isContained().
end() [2/2]
template<typename T > const_iterator IntervalSet< T >::end () const inline
Definition at line 36 of file IntervalSet.h.
equalRange() [1/2]
template<typename T > std::pair<iterator, iterator> IntervalSet< T >::equalRange (const Interval< T > & interval) inline
Definition at line 83 of file IntervalSet.h.
equalRange() [2/2]
template<typename T > std::pair<iterator, iterator> IntervalSet< T >::equalRange (const T & lower, const T & upper) inline
Returns an iterator range containing all intervals between lower and upper.
Definition at line 78 of file IntervalSet.h.
Referenced by IntervalSet< Address >::equalRange(), and IntervalSet< Address >::insert().
insert() [1/2]
template<typename T > iterator IntervalSet< T >::insert (const Interval< T > & interval) inline
Definition at line 50 of file IntervalSet.h.
insert() [2/2]
template<typename T > iterator IntervalSet< T >::insert (const T & from, const T & to) inline
Definition at line 49 of file IntervalSet.h.
Referenced by BinarySectionImpl::addDefinedArea(), and IntervalSet< Address >::insert().
isContained()
template<typename T > bool IntervalSet< T >::isContained (const T & value) const inline
Returns
true if value is contained in any interval of this set.
Definition at line 118 of file IntervalSet.h.
Referenced by BinarySectionImpl::isAddressBss().
isEmpty()
template<typename T > bool IntervalSet< T >::isEmpty () const inline
Returns
true if the set does not contain any elements.
Definition at line 44 of file IntervalSet.h.
Referenced by BinarySectionImpl::isAddressBss(), and IntervalSet< Address >::isContained().
rbegin() [1/2]
template<typename T > reverse_iterator IntervalSet< T >::rbegin () inline
Definition at line 37 of file IntervalSet.h.
rbegin() [2/2]
template<typename T > const_reverse_iterator IntervalSet< T >::rbegin () const inline
Definition at line 39 of file IntervalSet.h.
rend() [1/2]
template<typename T > reverse_iterator IntervalSet< T >::rend () inline
Definition at line 38 of file IntervalSet.h.
rend() [2/2]
template<typename T > const_reverse_iterator IntervalSet< T >::rend () const inline
Definition at line 40 of file IntervalSet.h.
Member Data Documentation
m_data
template<typename T > Data IntervalSet< T >::m_data private
Definition at line 140 of file IntervalSet.h.
Referenced by IntervalSet< Address >::begin(), IntervalSet< Address >::clear(), IntervalSet< Address >::end(), IntervalSet< Address >::insert(), IntervalSet< Address >::isContained(), IntervalSet< Address >::isEmpty(), IntervalSet< Address >::rbegin(), and IntervalSet< Address >::rend().
The documentation for this class was generated from the following file:
IntervalSet.h