Boomerang: Plugin Class Reference
Plugin Class Reference
Class for managing an interface plugin.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/core/plugin/Plugin.h>
Public Member Functions
template<typename IFC >
IFC * getIfc ()
template<typename IFC >
const IFC * getIfc () const
const PluginInfo * getInfo () const
Get information about the plugin.
Plugin & operator= (const Plugin &other)=delete
Plugin & operator= (Plugin &&other)=default
Plugin (const Plugin &other)=delete
Plugin (Plugin &&other)=default
Plugin (Project *project, const QString &pluginPath)
Create a plugin from a dynamic library file.
~Plugin ()
Private Types
using PluginDeinitFunction = void(*)()
using PluginInfoFunction = const PluginInfo *(*)()
using PluginInitFunction = void *(*)(Project *)
Private Member Functions
bool deinit ()
De-initialize the plugin.
template<class FuncPtr >
FuncPtr getFunction (const char *name) const
Given a non-mangled function name (e.g.
bool init (Project *project)
Initialize the plugin.
Private Attributes
void * m_ifc
Interface pointer (e.g. IDecoder * for decoder plugins)
PluginHandle m_pluginHandle
handle to the dynamic library
Detailed Description
Class for managing an interface plugin.
The plugin must define the following functions (with extern "C" linkage):
IFC* initPlugin(): to initialize the plugin class and allocate resources etc. You must ensure the returned pointer is valid until deinitPlugin() is called.
void deinitPlugin(): to deinitialize the plugin and free resources.
const PluginInfo* getInfo(): To get information about the plugin. May be called before initPlugin().
Definition at line 40 of file Plugin.h.
Member Typedef Documentation
PluginDeinitFunction
using Plugin::PluginDeinitFunction = void (*)() private
Definition at line 43 of file Plugin.h.
PluginInfoFunction
using Plugin::PluginInfoFunction = const PluginInfo *(*)() private
Definition at line 44 of file Plugin.h.
PluginInitFunction
using Plugin::PluginInitFunction = void *(*)(Project *) private
Definition at line 42 of file Plugin.h.
Constructor & Destructor Documentation
Plugin() [1/3]
Plugin::Plugin (Project * project, const QString & pluginPath) explicit
Create a plugin from a dynamic library file.
Parameters
pluginPath path to the library file.
Definition at line 13 of file Plugin.cpp.
References init().
Plugin() [2/3]
Plugin::Plugin (const Plugin & other) delete
Plugin() [3/3]
Plugin::Plugin (Plugin && other) default
~Plugin()
Plugin::~Plugin ()
Definition at line 23 of file Plugin.cpp.
References deinit().
Member Function Documentation
deinit()
bool Plugin::deinit () private
De-initialize the plugin.
Definition at line 60 of file Plugin.cpp.
References m_ifc.
Referenced by ~Plugin().
getFunction()
template<class FuncPtr > FuncPtr Plugin::getFunction (const char * name) const inline private
Given a non-mangled function name (e.g.
initPlugin), get the function pointer for the function exported by this plugin.
Definition at line 85 of file Plugin.h.
References PluginHandle::getSymbol(), and m_pluginHandle.
getIfc() [1/2]
template<typename IFC > IFC* Plugin::getIfc () inline
Definition at line 64 of file Plugin.h.
References m_ifc.
getIfc() [2/2]
template<typename IFC > const IFC* Plugin::getIfc () const inline
Definition at line 70 of file Plugin.h.
References m_ifc.
getInfo()
const PluginInfo * Plugin::getInfo () const
Get information about the plugin.
Definition at line 30 of file Plugin.cpp.
Referenced by init().
init()
bool Plugin::init (Project * project) private
Initialize the plugin.
Definition at line 42 of file Plugin.cpp.
References getInfo(), and m_ifc.
Referenced by Plugin().
operator=() [1/2]
Plugin& Plugin::operator= (const Plugin & other) delete
operator=() [2/2]
Plugin& Plugin::operator= (Plugin && other) default
Member Data Documentation
m_ifc
void* Plugin::m_ifc private
Interface pointer (e.g. IDecoder * for decoder plugins)
Definition at line 99 of file Plugin.h.
Referenced by deinit(), getIfc(), and init().
m_pluginHandle
PluginHandle Plugin::m_pluginHandle private
handle to the dynamic library
Definition at line 98 of file Plugin.h.
Referenced by getFunction().
The documentation for this class was generated from the following files:
Plugin.h
Plugin.cpp