Boomerang: BinarySectionImpl Class Reference
BinarySectionImpl Class Reference
Public Member Functions
void addDefinedArea (Address from, Address to)
QVariant attributeInRange (const QString &attrib, Address from, Address to) const
void clearDefinedArea ()
QVariantMap getAttributesForRange (Address from, Address to)
bool isAddressBss (Address a) const
void setAttributeForRange (const QString &name, const QVariant &val, Address from, Address to)
Public Attributes
IntervalMap< Address, VariantHolder > m_attributeMap
IntervalSet< Address > m_hasDefinedValue
Detailed Description
Definition at line 33 of file BinarySection.cpp.
Member Function Documentation
addDefinedArea()
void BinarySectionImpl::addDefinedArea (Address from, Address to) inline
Definition at line 38 of file BinarySection.cpp.
References IntervalSet< T >::insert(), and m_hasDefinedValue.
attributeInRange()
QVariant BinarySectionImpl::attributeInRange (const QString & attrib, Address from, Address to) const inline
Definition at line 57 of file BinarySection.cpp.
References IntervalMap< Key, Value >::end(), IntervalMap< Key, Value >::find(), and m_attributeMap.
clearDefinedArea()
void BinarySectionImpl::clearDefinedArea () inline
Definition at line 36 of file BinarySection.cpp.
References IntervalSet< T >::clear(), and m_hasDefinedValue.
getAttributesForRange()
QVariantMap BinarySectionImpl::getAttributesForRange (Address from, Address to) inline
Definition at line 81 of file BinarySection.cpp.
References IntervalMap< Key, Value >::end(), IntervalMap< Key, Value >::equalRange(), and m_attributeMap.
isAddressBss()
bool BinarySectionImpl::isAddressBss (Address a) const inline
Definition at line 40 of file BinarySection.cpp.
References a, IntervalSet< T >::isContained(), IntervalSet< T >::isEmpty(), and m_hasDefinedValue.
setAttributeForRange()
void BinarySectionImpl::setAttributeForRange (const QString & name, const QVariant & val, Address from, Address to) inline
Definition at line 48 of file BinarySection.cpp.
References IntervalMap< Key, Value >::insert(), and m_attributeMap.
Member Data Documentation
m_attributeMap
IntervalMap<Address, VariantHolder> BinarySectionImpl::m_attributeMap
Definition at line 99 of file BinarySection.cpp.
Referenced by attributeInRange(), getAttributesForRange(), and setAttributeForRange().
m_hasDefinedValue
IntervalSet<Address> BinarySectionImpl::m_hasDefinedValue
Definition at line 98 of file BinarySection.cpp.
Referenced by addDefinedArea(), clearDefinedArea(), and isAddressBss().
The documentation for this class was generated from the following file:
BinarySection.cpp