Boomerang: Exp.h File Reference
Exp.h File Reference
#include "boomerang/ssl/exp/ExpHelp.h"
#include "boomerang/ssl/exp/Operator.h"
#include "boomerang/util/OStream.h"
#include <QString>
#include <cassert>
#include <list>
#include <memory>
#include <set>
#include <vector>
Macros
#define REG_PENT_AH RegNum(12)
#define REG_PENT_AL RegNum(8)
#define REG_PENT_AX RegNum(0)
#define REG_PENT_BH RegNum(15)
#define REG_PENT_BL RegNum(11)
#define REG_PENT_BP RegNum(5)
#define REG_PENT_BX RegNum(3)
#define REG_PENT_CH RegNum(13)
#define REG_PENT_CL RegNum(9)
#define REG_PENT_CS RegNum(17)
#define REG_PENT_CX RegNum(1)
#define REG_PENT_DH RegNum(14)
#define REG_PENT_DI RegNum(7)
#define REG_PENT_DL RegNum(10)
#define REG_PENT_DS RegNum(18)
#define REG_PENT_DX RegNum(2)
#define REG_PENT_EAX RegNum(24)
#define REG_PENT_EBP RegNum(29)
#define REG_PENT_EBX RegNum(27)
#define REG_PENT_ECX RegNum(25)
#define REG_PENT_EDI RegNum(31)
#define REG_PENT_EDX RegNum(26)
#define REG_PENT_ES RegNum(19)
#define REG_PENT_ESI RegNum(30)
#define REG_PENT_ESP RegNum(28)
#define REG_PENT_FCW RegNum(42)
#define REG_PENT_FS RegNum(20)
#define REG_PENT_FSTP RegNum(41)
#define REG_PENT_FSW RegNum(40)
#define REG_PENT_GS RegNum(21)
#define REG_PENT_SI RegNum(6)
#define REG_PENT_SP RegNum(4)
#define REG_PENT_SS RegNum(16)
#define REG_PENT_ST0 RegNum(32)
#define REG_PENT_ST1 RegNum(33)
#define REG_PENT_ST2 RegNum(34)
#define REG_PENT_ST3 RegNum(35)
#define REG_PENT_ST4 RegNum(36)
#define REG_PENT_ST5 RegNum(37)
#define REG_PENT_ST6 RegNum(38)
#define REG_PENT_ST7 RegNum(39)
#define REG_PPC_CR0 RegNum(100)
#define REG_PPC_CTR RegNum(301)
#define REG_PPC_F0 RegNum(32)
#define REG_PPC_G0 RegNum(0)
#define REG_PPC_G1 RegNum(1)
#define REG_PPC_G10 RegNum(10)
#define REG_PPC_G11 RegNum(11)
#define REG_PPC_G12 RegNum(12)
#define REG_PPC_G13 RegNum(13)
#define REG_PPC_G2 RegNum(2)
#define REG_PPC_G3 RegNum(3)
#define REG_PPC_G31 RegNum(31)
#define REG_PPC_G4 RegNum(4)
#define REG_PPC_G5 RegNum(5)
#define REG_PPC_G6 RegNum(6)
#define REG_PPC_G7 RegNum(7)
#define REG_PPC_G8 RegNum(8)
#define REG_PPC_G9 RegNum(9)
#define REG_PPC_LR RegNum(300)
#define REG_PPC_SP RegNum(1)
#define REG_PPC_VR0 RegNum(64)
#define REG_SPARC_CWP RegNum(101)
#define REG_SPARC_F0 RegNum(32)
#define REG_SPARC_F0TO1 RegNum(64)
#define REG_SPARC_F0TO3 RegNum(80)
#define REG_SPARC_F28TO31 RegNum(87)
#define REG_SPARC_F31 RegNum(63)
#define REG_SPARC_FP RegNum(30)
#define REG_SPARC_FSR RegNum(105)
#define REG_SPARC_G0 RegNum(0)
#define REG_SPARC_G1 RegNum(1)
#define REG_SPARC_G2 RegNum(2)
#define REG_SPARC_G3 RegNum(3)
#define REG_SPARC_G4 RegNum(4)
#define REG_SPARC_G5 RegNum(5)
#define REG_SPARC_G6 RegNum(6)
#define REG_SPARC_G7 RegNum(7)
#define REG_SPARC_I0 RegNum(24)
#define REG_SPARC_I1 RegNum(25)
#define REG_SPARC_I2 RegNum(26)
#define REG_SPARC_I3 RegNum(27)
#define REG_SPARC_I4 RegNum(28)
#define REG_SPARC_I5 RegNum(29)
#define REG_SPARC_I6 RegNum(30)
#define REG_SPARC_I7 RegNum(31)
#define REG_SPARC_ICC RegNum(200)
#define REG_SPARC_L0 RegNum(16)
#define REG_SPARC_L1 RegNum(17)
#define REG_SPARC_L2 RegNum(18)
#define REG_SPARC_L3 RegNum(19)
#define REG_SPARC_L4 RegNum(20)
#define REG_SPARC_L5 RegNum(21)
#define REG_SPARC_L6 RegNum(22)
#define REG_SPARC_L7 RegNum(23)
#define REG_SPARC_O0 RegNum(8)
#define REG_SPARC_O1 RegNum(9)
#define REG_SPARC_O2 RegNum(10)
#define REG_SPARC_O3 RegNum(11)
#define REG_SPARC_O4 RegNum(12)
#define REG_SPARC_O5 RegNum(13)
#define REG_SPARC_O6 RegNum(14)
#define REG_SPARC_O7 RegNum(15)
#define REG_SPARC_PSR RegNum(104)
#define REG_SPARC_SP RegNum(14)
#define REG_SPARC_TBR RegNum(102)
#define REG_SPARC_WIM RegNum(103)
#define REG_SPARC_Y RegNum(100)
#define REG_ST20_A RegNum(0)
#define REG_ST20_B RegNum(1)
#define REG_ST20_C RegNum(2)
#define REG_ST20_SP RegNum(3)
Typedefs
typedef std::shared_ptr< const Exp > SharedConstExp
typedef std::shared_ptr< const Type > SharedConstType
typedef std::shared_ptr< Exp > SharedExp
typedef std::shared_ptr< Type > SharedType
typedef std::unique_ptr< Exp > UniqExp
Functions
class __attribute__((visibility("default"))) Exp __attribute__ ((visibility("default"))) OStream &operator<<(OStream &os
Prints the Exp pointed to by p to os.
Variables
class __attribute__((visibility("default"))) Exp const SharedConstExp & exp
Macro Definition Documentation
REG_PENT_AH
#define REG_PENT_AH RegNum(12)
Definition at line 546 of file Exp.h.
REG_PENT_AL
#define REG_PENT_AL RegNum(8)
Definition at line 542 of file Exp.h.
REG_PENT_AX
#define REG_PENT_AX RegNum(0)
Definition at line 534 of file Exp.h.
REG_PENT_BH
#define REG_PENT_BH RegNum(15)
Definition at line 549 of file Exp.h.
REG_PENT_BL
#define REG_PENT_BL RegNum(11)
Definition at line 545 of file Exp.h.
REG_PENT_BP
#define REG_PENT_BP RegNum(5)
Definition at line 539 of file Exp.h.
REG_PENT_BX
#define REG_PENT_BX RegNum(3)
Definition at line 537 of file Exp.h.
REG_PENT_CH
#define REG_PENT_CH RegNum(13)
Definition at line 547 of file Exp.h.
REG_PENT_CL
#define REG_PENT_CL RegNum(9)
Definition at line 543 of file Exp.h.
REG_PENT_CS
#define REG_PENT_CS RegNum(17)
Definition at line 552 of file Exp.h.
REG_PENT_CX
#define REG_PENT_CX RegNum(1)
Definition at line 535 of file Exp.h.
REG_PENT_DH
#define REG_PENT_DH RegNum(14)
Definition at line 548 of file Exp.h.
REG_PENT_DI
#define REG_PENT_DI RegNum(7)
Definition at line 541 of file Exp.h.
REG_PENT_DL
#define REG_PENT_DL RegNum(10)
Definition at line 544 of file Exp.h.
REG_PENT_DS
#define REG_PENT_DS RegNum(18)
Definition at line 553 of file Exp.h.
REG_PENT_DX
#define REG_PENT_DX RegNum(2)
Definition at line 536 of file Exp.h.
REG_PENT_EAX
#define REG_PENT_EAX RegNum(24)
Definition at line 558 of file Exp.h.
REG_PENT_EBP
#define REG_PENT_EBP RegNum(29)
Definition at line 563 of file Exp.h.
REG_PENT_EBX
#define REG_PENT_EBX RegNum(27)
Definition at line 561 of file Exp.h.
REG_PENT_ECX
#define REG_PENT_ECX RegNum(25)
Definition at line 559 of file Exp.h.
REG_PENT_EDI
#define REG_PENT_EDI RegNum(31)
Definition at line 565 of file Exp.h.
REG_PENT_EDX
#define REG_PENT_EDX RegNum(26)
Definition at line 560 of file Exp.h.
REG_PENT_ES
#define REG_PENT_ES RegNum(19)
Definition at line 554 of file Exp.h.
REG_PENT_ESI
#define REG_PENT_ESI RegNum(30)
Definition at line 564 of file Exp.h.
REG_PENT_ESP
#define REG_PENT_ESP RegNum(28)
Definition at line 562 of file Exp.h.
REG_PENT_FCW
#define REG_PENT_FCW RegNum(42)
Definition at line 577 of file Exp.h.
REG_PENT_FS
#define REG_PENT_FS RegNum(20)
Definition at line 555 of file Exp.h.
REG_PENT_FSTP
#define REG_PENT_FSTP RegNum(41)
Definition at line 576 of file Exp.h.
REG_PENT_FSW
#define REG_PENT_FSW RegNum(40)
Definition at line 575 of file Exp.h.
REG_PENT_GS
#define REG_PENT_GS RegNum(21)
Definition at line 556 of file Exp.h.
REG_PENT_SI
#define REG_PENT_SI RegNum(6)
Definition at line 540 of file Exp.h.
REG_PENT_SP
#define REG_PENT_SP RegNum(4)
Definition at line 538 of file Exp.h.
REG_PENT_SS
#define REG_PENT_SS RegNum(16)
Definition at line 551 of file Exp.h.
REG_PENT_ST0
#define REG_PENT_ST0 RegNum(32)
Definition at line 567 of file Exp.h.
REG_PENT_ST1
#define REG_PENT_ST1 RegNum(33)
Definition at line 568 of file Exp.h.
REG_PENT_ST2
#define REG_PENT_ST2 RegNum(34)
Definition at line 569 of file Exp.h.
REG_PENT_ST3
#define REG_PENT_ST3 RegNum(35)
Definition at line 570 of file Exp.h.
REG_PENT_ST4
#define REG_PENT_ST4 RegNum(36)
Definition at line 571 of file Exp.h.
REG_PENT_ST5
#define REG_PENT_ST5 RegNum(37)
Definition at line 572 of file Exp.h.
REG_PENT_ST6
#define REG_PENT_ST6 RegNum(38)
Definition at line 573 of file Exp.h.
REG_PENT_ST7
#define REG_PENT_ST7 RegNum(39)
Definition at line 574 of file Exp.h.
REG_PPC_CR0
#define REG_PPC_CR0 RegNum(100)
Definition at line 655 of file Exp.h.
REG_PPC_CTR
#define REG_PPC_CTR RegNum(301)
Definition at line 658 of file Exp.h.
REG_PPC_F0
#define REG_PPC_F0 RegNum(32)
Definition at line 651 of file Exp.h.
REG_PPC_G0
#define REG_PPC_G0 RegNum(0)
Definition at line 635 of file Exp.h.
REG_PPC_G1
#define REG_PPC_G1 RegNum(1)
Definition at line 636 of file Exp.h.
REG_PPC_G10
#define REG_PPC_G10 RegNum(10)
Definition at line 645 of file Exp.h.
REG_PPC_G11
#define REG_PPC_G11 RegNum(11)
Definition at line 646 of file Exp.h.
REG_PPC_G12
#define REG_PPC_G12 RegNum(12)
Definition at line 647 of file Exp.h.
REG_PPC_G13
#define REG_PPC_G13 RegNum(13)
Definition at line 648 of file Exp.h.
REG_PPC_G2
#define REG_PPC_G2 RegNum(2)
Definition at line 637 of file Exp.h.
REG_PPC_G3
#define REG_PPC_G3 RegNum(3)
Definition at line 638 of file Exp.h.
REG_PPC_G31
#define REG_PPC_G31 RegNum(31)
Definition at line 649 of file Exp.h.
REG_PPC_G4
#define REG_PPC_G4 RegNum(4)
Definition at line 639 of file Exp.h.
REG_PPC_G5
#define REG_PPC_G5 RegNum(5)
Definition at line 640 of file Exp.h.
REG_PPC_G6
#define REG_PPC_G6 RegNum(6)
Definition at line 641 of file Exp.h.
REG_PPC_G7
#define REG_PPC_G7 RegNum(7)
Definition at line 642 of file Exp.h.
REG_PPC_G8
#define REG_PPC_G8 RegNum(8)
Definition at line 643 of file Exp.h.
REG_PPC_G9
#define REG_PPC_G9 RegNum(9)
Definition at line 644 of file Exp.h.
REG_PPC_LR
#define REG_PPC_LR RegNum(300)
Definition at line 657 of file Exp.h.
REG_PPC_SP
#define REG_PPC_SP RegNum(1)
Definition at line 633 of file Exp.h.
REG_PPC_VR0
#define REG_PPC_VR0 RegNum(64)
Definition at line 653 of file Exp.h.
REG_SPARC_CWP
#define REG_SPARC_CWP RegNum(101)
Definition at line 624 of file Exp.h.
REG_SPARC_F0
#define REG_SPARC_F0 RegNum(32)
Definition at line 617 of file Exp.h.
REG_SPARC_F0TO1
#define REG_SPARC_F0TO1 RegNum(64)
Definition at line 619 of file Exp.h.
REG_SPARC_F0TO3
#define REG_SPARC_F0TO3 RegNum(80)
Definition at line 621 of file Exp.h.
REG_SPARC_F28TO31
#define REG_SPARC_F28TO31 RegNum(87)
Definition at line 620 of file Exp.h.
REG_SPARC_F31
#define REG_SPARC_F31 RegNum(63)
Definition at line 618 of file Exp.h.
REG_SPARC_FP
#define REG_SPARC_FP RegNum(30)
Definition at line 615 of file Exp.h.
REG_SPARC_FSR
#define REG_SPARC_FSR RegNum(105)
Definition at line 628 of file Exp.h.
REG_SPARC_G0
#define REG_SPARC_G0 RegNum(0)
Definition at line 581 of file Exp.h.
REG_SPARC_G1
#define REG_SPARC_G1 RegNum(1)
Definition at line 582 of file Exp.h.
REG_SPARC_G2
#define REG_SPARC_G2 RegNum(2)
Definition at line 583 of file Exp.h.
REG_SPARC_G3
#define REG_SPARC_G3 RegNum(3)
Definition at line 584 of file Exp.h.
REG_SPARC_G4
#define REG_SPARC_G4 RegNum(4)
Definition at line 585 of file Exp.h.
REG_SPARC_G5
#define REG_SPARC_G5 RegNum(5)
Definition at line 586 of file Exp.h.
REG_SPARC_G6
#define REG_SPARC_G6 RegNum(6)
Definition at line 587 of file Exp.h.
REG_SPARC_G7
#define REG_SPARC_G7 RegNum(7)
Definition at line 588 of file Exp.h.
REG_SPARC_I0
#define REG_SPARC_I0 RegNum(24)
Definition at line 605 of file Exp.h.
REG_SPARC_I1
#define REG_SPARC_I1 RegNum(25)
Definition at line 606 of file Exp.h.
REG_SPARC_I2
#define REG_SPARC_I2 RegNum(26)
Definition at line 607 of file Exp.h.
REG_SPARC_I3
#define REG_SPARC_I3 RegNum(27)
Definition at line 608 of file Exp.h.
REG_SPARC_I4
#define REG_SPARC_I4 RegNum(28)
Definition at line 609 of file Exp.h.
REG_SPARC_I5
#define REG_SPARC_I5 RegNum(29)
Definition at line 610 of file Exp.h.
REG_SPARC_I6
#define REG_SPARC_I6 RegNum(30)
Definition at line 611 of file Exp.h.
REG_SPARC_I7
#define REG_SPARC_I7 RegNum(31)
Definition at line 612 of file Exp.h.
REG_SPARC_ICC
#define REG_SPARC_ICC RegNum(200)
Definition at line 630 of file Exp.h.
REG_SPARC_L0
#define REG_SPARC_L0 RegNum(16)
Definition at line 597 of file Exp.h.
REG_SPARC_L1
#define REG_SPARC_L1 RegNum(17)
Definition at line 598 of file Exp.h.
REG_SPARC_L2
#define REG_SPARC_L2 RegNum(18)
Definition at line 599 of file Exp.h.
REG_SPARC_L3
#define REG_SPARC_L3 RegNum(19)
Definition at line 600 of file Exp.h.
REG_SPARC_L4
#define REG_SPARC_L4 RegNum(20)
Definition at line 601 of file Exp.h.
REG_SPARC_L5
#define REG_SPARC_L5 RegNum(21)
Definition at line 602 of file Exp.h.
REG_SPARC_L6
#define REG_SPARC_L6 RegNum(22)
Definition at line 603 of file Exp.h.
REG_SPARC_L7
#define REG_SPARC_L7 RegNum(23)
Definition at line 604 of file Exp.h.
REG_SPARC_O0
#define REG_SPARC_O0 RegNum(8)
Definition at line 589 of file Exp.h.
REG_SPARC_O1
#define REG_SPARC_O1 RegNum(9)
Definition at line 590 of file Exp.h.
REG_SPARC_O2
#define REG_SPARC_O2 RegNum(10)
Definition at line 591 of file Exp.h.
REG_SPARC_O3
#define REG_SPARC_O3 RegNum(11)
Definition at line 592 of file Exp.h.
REG_SPARC_O4
#define REG_SPARC_O4 RegNum(12)
Definition at line 593 of file Exp.h.
REG_SPARC_O5
#define REG_SPARC_O5 RegNum(13)
Definition at line 594 of file Exp.h.
REG_SPARC_O6
#define REG_SPARC_O6 RegNum(14)
Definition at line 595 of file Exp.h.
REG_SPARC_O7
#define REG_SPARC_O7 RegNum(15)
Definition at line 596 of file Exp.h.
REG_SPARC_PSR
#define REG_SPARC_PSR RegNum(104)
Definition at line 627 of file Exp.h.
REG_SPARC_SP
#define REG_SPARC_SP RegNum(14)
Definition at line 614 of file Exp.h.
REG_SPARC_TBR
#define REG_SPARC_TBR RegNum(102)
Definition at line 625 of file Exp.h.
REG_SPARC_WIM
#define REG_SPARC_WIM RegNum(103)
Definition at line 626 of file Exp.h.
REG_SPARC_Y
#define REG_SPARC_Y RegNum(100)
Definition at line 623 of file Exp.h.
REG_ST20_A
#define REG_ST20_A RegNum(0)
Definition at line 662 of file Exp.h.
REG_ST20_B
#define REG_ST20_B RegNum(1)
Definition at line 663 of file Exp.h.
REG_ST20_C
#define REG_ST20_C RegNum(2)
Definition at line 664 of file Exp.h.
REG_ST20_SP
#define REG_ST20_SP RegNum(3)
Definition at line 665 of file Exp.h.
Typedef Documentation
SharedConstExp
typedef std::shared_ptr<const Exp> SharedConstExp
Definition at line 39 of file Exp.h.
SharedConstType
typedef std::shared_ptr<const Type> SharedConstType
Definition at line 41 of file Exp.h.
SharedExp
typedef std::shared_ptr<Exp> SharedExp
Definition at line 38 of file Exp.h.
SharedType
typedef std::shared_ptr<Type> SharedType
Definition at line 40 of file Exp.h.
UniqExp
typedef std::unique_ptr<Exp> UniqExp
Definition at line 35 of file Exp.h.
Function Documentation
__attribute__()
__attribute__ ((visibility("default"))) &
Prints the Exp pointed to by p to os.
Variable Documentation
exp
class __attribute__ ((visibility("default"))) Exp const SharedConstExp& exp
Definition at line 528 of file Exp.h.
Referenced by __attribute__(), checkForOverlap(), ExpPrinter::childNeedsParentheses(), ExpSet< T, Sorter, Enabler >::contains(), ExpSet< T, Sorter, Enabler >::insert(), ExpSet< T, Sorter, Enabler >::makeDiff(), ExpSet< T, Sorter, Enabler >::makeUnion(), operator<<(), ExpArithSimplifier::postModify(), ExpPropagator::postModify(), CallBypasser::postModify(), ImplicitConverter::postModify(), Localiser::postModify(), ExpSSAXformer::postModify(), ExpSimplifier::postModify(), ExpCastInserter::postModify(), SimpExpModifier::postModify(), ExpDotWriter::postVisit(), ExpAddressSimplifier::preModify(), SimpExpModifier::preModify(), ExpArithSimplifier::preModify(), Localiser::preModify(), ConstGlobalConverter::preModify(), ExpSimplifier::preModify(), ExpCastInserter::preModify(), DfaLocalMapper::preModify(), BadMemofFinder::preVisit(), ExpDestCounter::preVisit(), UsedLocalFinder::preVisit(), UsedLocsFinder::preVisit(), ComplexityFinder::preVisit(), ExpPrinter::print(), ExpPrinter::printHTML(), ExpPrinter::printPlain(), DfaLocalMapper::processExp(), StmtImplicitConverter::visit(), UsedLocsFinder::visit(), UsedLocalFinder::visit(), ExpDotWriter::visit(), and ExpDotWriter::writeDotFile().