Boomerang: Util Namespace Reference
Util Namespace Reference
Functions
__attribute__ ((visibility("default"))) SWord normEndian(SWord value
Normalize endianness of a value.
OStream & alignStream (OStream &str, int align)
template<class Container >
void clone (const Container &from, Container &to)
QString escapeStr (const char *inp)
const QString & getCallConvName (CallConv cc)
QWord getLowerBitMask (DWord bitCount)
return a bit mask with exactly bitCount of the lowest bits set to 1.
int getStackOffset (SharedConstExp e, int sp)
int getStackRegisterIndex (const Prog *prog)
template<class T , class U1 , class U2 >
bool inRange (const T &value, const U1 &rangeStart, const U2 &rangeEnd)
Check if value is in [rangeStart, rangeEnd)
template<typename Cont , typename T >
bool isContained (const Cont &cont, const T &value)
Check if a value is in a container.
DWord normEndian (DWord value, Endian srcEndian)
QWord normEndian (QWord value, Endian srcEndian)
SWord normEndian (SWord value, Endian srcEndian)
Byte readByte (const void *src)
DWord readDWord (const void *src, Endian srcEndian)
QWord readQWord (const void *src, Endian srcEndian)
SWord readWord (const void *src, Endian srcEndian)
template<typename TgtType = int, typename SrcType >
TgtType signExtend (const SrcType &src, std::size_t numSrcBits=8 *sizeof(SrcType))
Sign-extend src into TgtType.
DWord swapEndian (DWord value)
QWord swapEndian (QWord value)
SWord swapEndian (SWord value)
bool testMagic (const Byte *buf, const std::initializer_list< Byte > &magic)
void writeByte (void *dst, Byte value)
void writeDWord (void *dst, DWord value, Endian dstEndian)
void writeQWord (void *dst, QWord value, Endian dstEndian)
void writeWord (void *dst, SWord value, Endian dstEndian)
Variables
SWord Endian dstEndian
const std::initializer_list< Byte > & magic
Endian srcEndian
Byte value
Function Documentation
__attribute__()
Util::__attribute__ ((visibility("default")))
Normalize endianness of a value.
Return the internal index of the stack register of an architecture, or -1 if the architecture does not have a stack register.
Escape strings properly for code generation.
Tests if data starts with a specific byte sequence.
Write values to dst, respecting endianness.
Read values, respecting endianness.
Swaps bytes of value if the endianness of the source, indicated by srcEndian, is different from the endianness of the host.
See also
normEndian
Note
The size of data must not be smaller than magic.
Returns
true if data matches the bytes in magic
Turns things like newline, return, tab into
, \r, \t etc
Note
Assumes a C or C++ back end
alignStream()
OStream & Util::alignStream (OStream & str, int align)
Definition at line 63 of file Util.cpp.
clone()
template<class Container > void Util::clone (const Container & from, Container & to)
Definition at line 56 of file Util.h.
Referenced by __attribute__(), and CallingConvention::Win32TcSignature::clone().
escapeStr()
QString Util::escapeStr (const char * inp)
Definition at line 26 of file Util.cpp.
getCallConvName()
const QString & Util::getCallConvName (CallConv cc)
Definition at line 27 of file SigEnum.cpp.
References g_callConvNames.
getLowerBitMask()
QWord Util::getLowerBitMask (DWord bitCount) inline
return a bit mask with exactly bitCount of the lowest bits set to 1.
(example: 16 -> 0xFFFF)
Definition at line 32 of file ByteUtil.h.
Referenced by ExpSimplifier::postModify().
getStackOffset()
int Util::getStackOffset (SharedConstExp e, int sp)
Definition at line 70 of file Util.cpp.
References opMinus, and opPlus.
getStackRegisterIndex()
int Util::getStackRegisterIndex (const Prog * prog)
Definition at line 103 of file Util.cpp.
References PENTIUM, PPC, REG_PENT_ESP, REG_PPC_G1, REG_SPARC_SP, REG_ST20_SP, SPARC, and ST20.
Referenced by SPPreservationPass::execute(), DfaLocalMapper::processExp(), AssignRemovalPass::removeSpAssigns(), and DFATypeAnalyzer::visitAssignment().
inRange()
template<class T , class U1 , class U2 > bool Util::inRange (const T & value, const U1 & rangeStart, const U2 & rangeEnd)
Check if value is in [rangeStart, rangeEnd)
Definition at line 41 of file Util.h.
References value.
Referenced by ExpSimplifier::postModify().
isContained()
template<typename Cont , typename T > bool Util::isContained (const Cont & cont, const T & value)
Check if a value is in a container.
Definition at line 49 of file Util.h.
References value.
normEndian() [1/3]
DWord Util::normEndian (DWord value, Endian srcEndian)
Definition at line 24 of file ByteUtil.cpp.
References srcEndian, swapEndian(), and value.
normEndian() [2/3]
QWord Util::normEndian (QWord value, Endian srcEndian)
Definition at line 31 of file ByteUtil.cpp.
References srcEndian, swapEndian(), and value.
normEndian() [3/3]
SWord Util::normEndian (SWord value, Endian srcEndian)
Definition at line 17 of file ByteUtil.cpp.
References srcEndian, swapEndian(), and value.
Referenced by readDWord(), readQWord(), readWord(), writeDWord(), writeQWord(), and writeWord().
readByte()
Byte Util::readByte (const void * src)
Definition at line 38 of file ByteUtil.cpp.
readDWord()
DWord Util::readDWord (const void * src, Endian srcEndian)
Definition at line 52 of file ByteUtil.cpp.
References normEndian(), and srcEndian.
readQWord()
QWord Util::readQWord (const void * src, Endian srcEndian)
Definition at line 59 of file ByteUtil.cpp.
References normEndian(), and srcEndian.
readWord()
SWord Util::readWord (const void * src, Endian srcEndian)
Definition at line 45 of file ByteUtil.cpp.
References normEndian(), and srcEndian.
signExtend()
template<typename TgtType = int, typename SrcType > TgtType Util::signExtend (const SrcType & src, std::size_t numSrcBits = 8 * sizeof(SrcType))
Sign-extend src into TgtType.
Example: signExtend<int>((unsigned char)0xFF) == -1
Parameters
src number to sign-extend
numSrcBits Number of Bits in the source type (Mainly to counter int-promotion in (blabla & 0xFF))
Definition at line 100 of file ByteUtil.h.
References value.
swapEndian() [1/3]
DWord Util::swapEndian (DWord value) inline
Definition at line 48 of file ByteUtil.h.
References value.
swapEndian() [2/3]
QWord Util::swapEndian (QWord value) inline
Definition at line 56 of file ByteUtil.h.
References value.
swapEndian() [3/3]
SWord Util::swapEndian (SWord value) inline
Definition at line 41 of file ByteUtil.h.
References value.
Referenced by normEndian().
testMagic()
bool Util::testMagic (const Byte * buf, const std::initializer_list< Byte > & magic)
Definition at line 94 of file ByteUtil.cpp.
References magic.
writeByte()
void Util::writeByte (void * dst, Byte value)
Definition at line 66 of file ByteUtil.cpp.
References value.
writeDWord()
void Util::writeDWord (void * dst, DWord value, Endian dstEndian)
Definition at line 80 of file ByteUtil.cpp.
References dstEndian, normEndian(), and value.
writeQWord()
void Util::writeQWord (void * dst, QWord value, Endian dstEndian)
Definition at line 87 of file ByteUtil.cpp.
References dstEndian, normEndian(), and value.
writeWord()
void Util::writeWord (void * dst, SWord value, Endian dstEndian)
Definition at line 73 of file ByteUtil.cpp.
References dstEndian, normEndian(), and value.
Variable Documentation
dstEndian
QWord Endian Util::dstEndian
Definition at line 85 of file ByteUtil.h.
Referenced by writeDWord(), writeQWord(), and writeWord().
magic
const std::initializer_list<Byte>& Util::magic
Definition at line 117 of file ByteUtil.h.
Referenced by testMagic().
srcEndian
Endian Util::srcEndian
Definition at line 71 of file ByteUtil.h.
Referenced by normEndian(), readDWord(), readQWord(), and readWord().
value
QWord Util::value
Definition at line 84 of file ByteUtil.h.
Referenced by __attribute__(), Interval< T >::contains(), GlobalConstReplacePass::execute(), inRange(), IntervalMap< Address, VariantHolder >::insert(), isContained(), IntervalSet< Address >::isContained(), normEndian(), Interval< T >::operator<(), ConstGlobalConverter::preModify(), signExtend(), swapEndian(), writeByte(), writeDWord(), writeQWord(), and writeWord().