Boomerang: UnusedStatementRemovalPass Class Reference
UnusedStatementRemovalPass Class Reference final
Remove unused statements.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/passes/late/UnusedStatementRemovalPass.h>
Public Member Functions
bool execute (UserProc *proc) override
Run this pass, updating proc.
UnusedStatementRemovalPass ()
Public Member Functions inherited from IPass
const QString & getName () const
PassID getType () const
IPass (const QString &name, PassID type)
virtual bool isProcLocal () const
virtual ~IPass ()=default
Private Types
typedef std::map< SharedStmt, int > RefCounter
Private Member Functions
bool removeNullStatements (UserProc *proc)
Remove statements of the form x := x.
void remUnusedStmtEtc (UserProc *proc, RefCounter &refCounts)
void updateRefCounts (UserProc *proc, RefCounter &refCounts)
Count references to the things that are under SSA control.
Detailed Description
Remove unused statements.
Definition at line 20 of file UnusedStatementRemovalPass.h.
Member Typedef Documentation
RefCounter
typedef std::map<SharedStmt, int> UnusedStatementRemovalPass::RefCounter private
Definition at line 22 of file UnusedStatementRemovalPass.h.
Constructor & Destructor Documentation
UnusedStatementRemovalPass()
UnusedStatementRemovalPass::UnusedStatementRemovalPass ()
Definition at line 22 of file UnusedStatementRemovalPass.cpp.
References UnusedStatementRemoval.
Member Function Documentation
execute()
bool UnusedStatementRemovalPass::execute (UserProc * proc) override virtual
Run this pass, updating proc.
Returns
true iff any change
Implements IPass.
Definition at line 28 of file UnusedStatementRemovalPass.cpp.
References removeNullStatements(), remUnusedStmtEtc(), and updateRefCounts().
removeNullStatements()
bool UnusedStatementRemovalPass::removeNullStatements (UserProc * proc) private
Remove statements of the form x := x.
Definition at line 193 of file UnusedStatementRemovalPass.cpp.
References LOG_VERBOSE.
Referenced by execute().
remUnusedStmtEtc()
void UnusedStatementRemovalPass::remUnusedStmtEtc (UserProc * proc, RefCounter & refCounts) private
Definition at line 98 of file UnusedStatementRemovalPass.cpp.
References BlockVarRename, CallLivenessRemoval, FinalDone, StmtSet< T, Sorter, Enabler >::insert(), LOG_MSG, and opGlobal.
Referenced by execute().
updateRefCounts()
void UnusedStatementRemovalPass::updateRefCounts (UserProc * proc, RefCounter & refCounts) private
Count references to the things that are under SSA control.
For each SSA subscripting, increment a counter for that definition
Definition at line 48 of file UnusedStatementRemovalPass.cpp.
References LOG_MSG.
Referenced by execute().
The documentation for this class was generated from the following files:
UnusedStatementRemovalPass.h
UnusedStatementRemovalPass.cpp