Boomerang: GraphNode< Derived > Class Template Reference
GraphNode< Derived > Class Template Reference
Base class for all nodes/vertices in a directed graph.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/db/GraphNode.h>
Public Member Functions
void addPredecessor (Derived *pred)
Add a predecessor to this node.
void addSuccessor (Derived *succ)
Add a successor to this node.
int getNumPredecessors () const
int getNumSuccessors () const
Derived * getPredecessor (int i)
const Derived * getPredecessor (int i) const
const std::vector< Derived * > & getPredecessors () const
Derived * getSuccessor (int i)
const Derived * getSuccessor (int i) const
const std::vector< Derived * > & getSuccessors () const
bool isPredecessorOf (const Derived *node) const
bool isSuccessorOf (const Derived *node) const
void removeAllPredecessors ()
removes all predecessor nodes.
void removeAllSuccessors ()
Removes all successor nodes.
void removePredecessor (Derived *pred)
Remove a predecessor node.
void removeSuccessor (Derived *succ)
Remove a successor node.
void setPredecessor (int i, Derived *pred)
Change the i-th predecessor of this node.
void setSuccessor (int i, Derived *succ)
Change the i-th successor of this node.
Private Attributes
std::vector< Derived * > m_predecessors
Vector of in-edges.
std::vector< Derived * > m_successors
Vector of out-edges.
Detailed Description
template<typename Derived>
class GraphNode< Derived >
Base class for all nodes/vertices in a directed graph.
Definition at line 24 of file GraphNode.h.
Member Function Documentation
addPredecessor()
template<typename Derived > void GraphNode< Derived >::addPredecessor (Derived * pred) inline
Add a predecessor to this node.
Definition at line 79 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
addSuccessor()
template<typename Derived > void GraphNode< Derived >::addSuccessor (Derived * succ) inline
Add a successor to this node.
Definition at line 82 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
getNumPredecessors()
template<typename Derived > int GraphNode< Derived >::getNumPredecessors () const inline
Definition at line 27 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
Referenced by GraphNode< Derived >::getPredecessor(), and GraphNode< Derived >::setPredecessor().
getNumSuccessors()
template<typename Derived > int GraphNode< Derived >::getNumSuccessors () const inline
Definition at line 28 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
Referenced by GraphNode< Derived >::getSuccessor(), and GraphNode< Derived >::setSuccessor().
getPredecessor() [1/2]
template<typename Derived > Derived* GraphNode< Derived >::getPredecessor (int i) inline
Returns
the i-th predecessor of this node. Returns nullptr if i is out of range.
Definition at line 38 of file GraphNode.h.
References GraphNode< Derived >::getNumPredecessors(), Util::inRange(), and GraphNode< Derived >::m_predecessors.
getPredecessor() [2/2]
template<typename Derived > const Derived* GraphNode< Derived >::getPredecessor (int i) const inline
Returns
the i-th predecessor of this node. Returns nullptr if i is out of range.
Definition at line 45 of file GraphNode.h.
References GraphNode< Derived >::getNumPredecessors(), Util::inRange(), and GraphNode< Derived >::m_predecessors.
getPredecessors()
template<typename Derived > const std::vector<Derived *>& GraphNode< Derived >::getPredecessors () const inline
Returns
all predecessors of this node.
Definition at line 31 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
getSuccessor() [1/2]
template<typename Derived > Derived* GraphNode< Derived >::getSuccessor (int i) inline
Returns
the i-th successor of this node. Returns nullptr if i is out of range.
Definition at line 52 of file GraphNode.h.
References GraphNode< Derived >::getNumSuccessors(), Util::inRange(), and GraphNode< Derived >::m_successors.
getSuccessor() [2/2]
template<typename Derived > const Derived* GraphNode< Derived >::getSuccessor (int i) const inline
Definition at line 57 of file GraphNode.h.
References GraphNode< Derived >::getNumSuccessors(), Util::inRange(), and GraphNode< Derived >::m_successors.
getSuccessors()
template<typename Derived > const std::vector<Derived *>& GraphNode< Derived >::getSuccessors () const inline
Returns
all successors of this node.
Definition at line 34 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
isPredecessorOf()
template<typename Derived > bool GraphNode< Derived >::isPredecessorOf (const Derived * node) const inline
Returns
true if this node is a (direct) predecessor of node, i.e. there is an edge from this node to node
Definition at line 117 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
isSuccessorOf()
template<typename Derived > bool GraphNode< Derived >::isSuccessorOf (const Derived * node) const inline
Returns
true if this node is a (direct) successor of node, i.e. there is an edge from node to this node.
Definition at line 124 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
removeAllPredecessors()
template<typename Derived > void GraphNode< Derived >::removeAllPredecessors () inline
removes all predecessor nodes.
Definition at line 113 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
removeAllSuccessors()
template<typename Derived > void GraphNode< Derived >::removeAllSuccessors () inline
Removes all successor nodes.
Called when noreturn call is found
Definition at line 110 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
removePredecessor()
template<typename Derived > void GraphNode< Derived >::removePredecessor (Derived * pred) inline
Remove a predecessor node.
Definition at line 85 of file GraphNode.h.
References GraphNode< Derived >::m_predecessors.
removeSuccessor()
template<typename Derived > void GraphNode< Derived >::removeSuccessor (Derived * succ) inline
Remove a successor node.
Definition at line 97 of file GraphNode.h.
References GraphNode< Derived >::m_successors.
setPredecessor()
template<typename Derived > void GraphNode< Derived >::setPredecessor (int i, Derived * pred) inline
Change the i-th predecessor of this node.
Parameters
i index (0-based)
Definition at line 64 of file GraphNode.h.
References GraphNode< Derived >::getNumPredecessors(), Util::inRange(), and GraphNode< Derived >::m_predecessors.
setSuccessor()
template<typename Derived > void GraphNode< Derived >::setSuccessor (int i, Derived * succ) inline
Change the i-th successor of this node.
Parameters
i index (0-based)
Definition at line 72 of file GraphNode.h.
References GraphNode< Derived >::getNumSuccessors(), Util::inRange(), and GraphNode< Derived >::m_successors.
Member Data Documentation
m_predecessors
template<typename Derived > std::vector<Derived *> GraphNode< Derived >::m_predecessors private
Vector of in-edges.
Definition at line 132 of file GraphNode.h.
Referenced by GraphNode< Derived >::addPredecessor(), GraphNode< Derived >::getNumPredecessors(), GraphNode< Derived >::getPredecessor(), GraphNode< Derived >::getPredecessors(), GraphNode< Derived >::isSuccessorOf(), GraphNode< Derived >::removeAllPredecessors(), GraphNode< Derived >::removePredecessor(), and GraphNode< Derived >::setPredecessor().
m_successors
template<typename Derived > std::vector<Derived *> GraphNode< Derived >::m_successors private
Vector of out-edges.
Definition at line 133 of file GraphNode.h.
Referenced by GraphNode< Derived >::addSuccessor(), GraphNode< Derived >::getNumSuccessors(), GraphNode< Derived >::getSuccessor(), GraphNode< Derived >::getSuccessors(), GraphNode< Derived >::isPredecessorOf(), GraphNode< Derived >::removeAllSuccessors(), GraphNode< Derived >::removeSuccessor(), and GraphNode< Derived >::setSuccessor().
The documentation for this class was generated from the following file:
GraphNode.h