Boomerang: DFATypeAnalyzer Class Reference
DFATypeAnalyzer Class Reference
This modifier traverses all statements and propagates type information about them.
#include </home/ceeac/Projects/code/boomerang/src/boomerang-plugins/type/dfa/DFATypeAnalyzer.h>
Public Member Functions
DFATypeAnalyzer ()
bool hasChanged () const
void resetChanged ()
void visit (const std::shared_ptr< Assign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< BoolAssign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< BranchStatement > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< CallStatement > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< ImplicitAssign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< PhiAssign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< ReturnStatement > &stmt, bool &visitChildren) override
virtual ~DFATypeAnalyzer ()=default
Private Member Functions
void visitAssignment (const std::shared_ptr< Assignment > &stmt, bool &visitChildren)
Code common to DFA type recovery of assignments.
Private Attributes
bool m_changed = false
Detailed Description
This modifier traverses all statements and propagates type information about them.
Definition at line 23 of file DFATypeAnalyzer.h.
Constructor & Destructor Documentation
DFATypeAnalyzer()
DFATypeAnalyzer::DFATypeAnalyzer ()
Definition at line 31 of file DFATypeAnalyzer.cpp.
~DFATypeAnalyzer()
virtual DFATypeAnalyzer::~DFATypeAnalyzer () virtual default
Member Function Documentation
hasChanged()
bool DFATypeAnalyzer::hasChanged () const inline
Definition at line 30 of file DFATypeAnalyzer.h.
References m_changed.
resetChanged()
void DFATypeAnalyzer::resetChanged () inline
Definition at line 31 of file DFATypeAnalyzer.h.
References m_changed.
visit() [1/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< Assign > & stmt, bool & visitChildren) override
Definition at line 130 of file DFATypeAnalyzer.cpp.
References m_changed, stmt, and visitAssignment().
visit() [2/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< BoolAssign > & stmt, bool & visitChildren) override
Definition at line 154 of file DFATypeAnalyzer.cpp.
References stmt, and visitAssignment().
visit() [3/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< BranchStatement > & stmt, bool & visitChildren) override
Definition at line 161 of file DFATypeAnalyzer.cpp.
References m_changed, and stmt.
visit() [4/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< CallStatement > & stmt, bool & visitChildren) override
Definition at line 172 of file DFATypeAnalyzer.cpp.
References Assign, m_changed, and visit().
visit() [5/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< ImplicitAssign > & stmt, bool & visitChildren) override
Definition at line 239 of file DFATypeAnalyzer.cpp.
References stmt, and visitAssignment().
visit() [6/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< PhiAssign > & stmt, bool & visitChildren) override
For x0 := phi(x1, x2, ...) want Tx0 := Tx0 meet (Tx1 meet Tx2 meet ...) Tx1 := Tx1 meet Tx0 Tx2 := Tx2 meet Tx0
Definition at line 75 of file DFATypeAnalyzer.cpp.
References m_changed, stmt, and visitAssignment().
Referenced by visit().
visit() [7/7]
void DFATypeAnalyzer::visit (const std::shared_ptr< ReturnStatement > & stmt, bool & visitChildren) override
Definition at line 245 of file DFATypeAnalyzer.cpp.
References stmt, and visitAssignment().
visitAssignment()
void DFATypeAnalyzer::visitAssignment (const std::shared_ptr< Assignment > & stmt, bool & visitChildren) private
Code common to DFA type recovery of assignments.
Definition at line 37 of file DFATypeAnalyzer.cpp.
References addr, Util::getStackRegisterIndex(), m_changed, and stmt.
Referenced by visit().
Member Data Documentation
m_changed
bool DFATypeAnalyzer::m_changed = false private
Definition at line 64 of file DFATypeAnalyzer.h.
Referenced by hasChanged(), resetChanged(), visit(), and visitAssignment().
The documentation for this class was generated from the following files:
DFATypeAnalyzer.h
DFATypeAnalyzer.cpp