Boomerang: LivenessAnalyzer Class Reference
LivenessAnalyzer Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/decomp/LivenessAnalyzer.h>
Public Member Functions
bool calcLiveness (IRFragment *frag, ConnectionGraph &ig, UserProc *proc)
void getLiveOut (IRFragment *frag, LocationSet &live, LocationSet &phiLocs)
Locations that are live at the end of this BB are the union of the locations that are live at the start of its successors.
LivenessAnalyzer ()=default
Private Attributes
std::unordered_map< IRFragment *, LocationSet > m_liveIn
< Set of locations live at fragment start
Detailed Description
Definition at line 23 of file LivenessAnalyzer.h.
Constructor & Destructor Documentation
LivenessAnalyzer()
LivenessAnalyzer::LivenessAnalyzer () default
Member Function Documentation
calcLiveness()
bool LivenessAnalyzer::calcLiveness (IRFragment * frag, ConnectionGraph & ig, UserProc * proc)
Definition at line 64 of file LivenessAnalyzer.cpp.
References checkForOverlap(), getLiveOut(), LOG_MSG, and m_liveIn.
Referenced by InterferenceFinder::findInterferences().
getLiveOut()
void LivenessAnalyzer::getLiveOut (IRFragment * frag, LocationSet & live, LocationSet & phiLocs)
Locations that are live at the end of this BB are the union of the locations that are live at the start of its successors.
live gets all the livenesses, and phiLocs gets a subset of these, which are due to phi statements at the top of successors
Definition at line 124 of file LivenessAnalyzer.cpp.
References LOG_MSG, LOG_WARN, m_liveIn, and PhiAssign.
Referenced by calcLiveness().
Member Data Documentation
m_liveIn
std::unordered_map<IRFragment *, LocationSet> LivenessAnalyzer::m_liveIn private
< Set of locations live at fragment start
Definition at line 38 of file LivenessAnalyzer.h.
Referenced by calcLiveness(), and getLiveOut().
The documentation for this class was generated from the following files:
LivenessAnalyzer.h
LivenessAnalyzer.cpp