Boomerang: ExpCastInserter Class Reference
ExpCastInserter Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/expmodifier/ExpCastInserter.h>
Public Member Functions
ExpCastInserter ()=default
SharedExp postModify (const std::shared_ptr< Binary > &exp) override
SharedExp postModify (const std::shared_ptr< Const > &exp) override
SharedExp postModify (const std::shared_ptr< RefExp > &exp) override
SharedExp preModify (const std::shared_ptr< TypedExp > &exp, bool &visitChildren) override
virtual ~ExpCastInserter ()=default
Static Public Member Functions
static void checkMemofType (const SharedExp &memof, SharedType memofType)
Check the type of the address expression of memof to make sure it is compatible with the given memofType.
Detailed Description
Definition at line 24 of file ExpCastInserter.h.
Constructor & Destructor Documentation
ExpCastInserter()
ExpCastInserter::ExpCastInserter () default
~ExpCastInserter()
virtual ExpCastInserter::~ExpCastInserter () virtual default
Member Function Documentation
checkMemofType()
void ExpCastInserter::checkMemofType (const SharedExp & memof, SharedType memofType) static
Check the type of the address expression of memof to make sure it is compatible with the given memofType.
memof may be changed internally to include a TypedExp, which will emit as a cast
Definition at line 52 of file ExpCastInserter.cpp.
References addr.
Referenced by StmtCastInserter::common(), and postModify().
postModify() [1/3]
SharedExp ExpCastInserter::postModify (const std::shared_ptr< Binary > & exp) override
Definition at line 89 of file ExpCastInserter.cpp.
References checkSignedness(), exp, opGtr, opGtrEq, opGtrEqUns, opGtrUns, opLess, opLessEq, opLessEqUns, opLessUns, opShR, opShRA, Signed, and Unsigned.
postModify() [2/3]
SharedExp ExpCastInserter::postModify (const std::shared_ptr< Const > & exp) override
Definition at line 128 of file ExpCastInserter.cpp.
References exp, and Unsigned.
postModify() [3/3]
SharedExp ExpCastInserter::postModify (const std::shared_ptr< RefExp > & exp) override
Definition at line 68 of file ExpCastInserter.cpp.
References checkMemofType(), exp, and LOG_WARN.
preModify()
SharedExp ExpCastInserter::preModify (const std::shared_ptr< TypedExp > & exp, bool & visitChildren) override
Don't consider if already cast
Definition at line 45 of file ExpCastInserter.cpp.
References exp.
The documentation for this class was generated from the following files:
ExpCastInserter.h
ExpCastInserter.cpp