Boomerang: AnsiCParserDriver Class Reference
AnsiCParserDriver Class Reference
Class for parsing an SSL specification file.
#include </home/ceeac/Projects/code/boomerang/src/boomerang-plugins/symbol/c/parser/AnsiCParserDriver.h>
Public Member Functions
AnsiCParserDriver ()
int parse (const QString &fileName, Machine machine, CallConv cc)
Parse the file with name. return 0 on success.
Public Attributes
CallConv cc = CallConv::INVALID
AnsiC::location location
Machine plat = Machine::INVALID
std::list< std::shared_ptr< SymbolRef > > refs
std::list< std::shared_ptr< Signature > > signatures
std::list< std::shared_ptr< Symbol > > symbols
Private Member Functions
bool scanBegin ()
void scanEnd ()
Private Attributes
std::string file
The name of the file being parsed.
bool trace_parsing
Whether to generate parser debug traces.
bool trace_scanning
Whether to generate scanner debug traces.
Detailed Description
Class for parsing an SSL specification file.
Definition at line 27 of file AnsiCParserDriver.h.
Constructor & Destructor Documentation
AnsiCParserDriver()
AnsiCParserDriver::AnsiCParserDriver ()
Definition at line 17 of file AnsiCParserDriver.cpp.
Member Function Documentation
parse()
int AnsiCParserDriver::parse (const QString & fileName, Machine machine, CallConv cc)
Parse the file with name. return 0 on success.
Definition at line 24 of file AnsiCParserDriver.cpp.
References cc, file, location, plat, scanBegin(), scanEnd(), and trace_parsing.
scanBegin()
bool AnsiCParserDriver::scanBegin () private
Definition at line 2799 of file AnsiCScanner.cpp.
References AnsiC_flex_debug, AnsiCin, file, LOG_ERROR, and trace_scanning.
Referenced by parse().
scanEnd()
void AnsiCParserDriver::scanEnd () private
Definition at line 2814 of file AnsiCScanner.cpp.
References AnsiCin, and yylex_destroy.
Referenced by parse().
Member Data Documentation
cc
CallConv AnsiCParserDriver::cc = CallConv::INVALID
Definition at line 40 of file AnsiCParserDriver.h.
Referenced by parse().
file
std::string AnsiCParserDriver::file private
The name of the file being parsed.
Definition at line 52 of file AnsiCParserDriver.h.
Referenced by parse(), and scanBegin().
location
AnsiC::location AnsiCParserDriver::location
Definition at line 37 of file AnsiCParserDriver.h.
Referenced by parse().
plat
Machine AnsiCParserDriver::plat = Machine::INVALID
Definition at line 39 of file AnsiCParserDriver.h.
Referenced by parse().
refs
std::list<std::shared_ptr<SymbolRef> > AnsiCParserDriver::refs
Definition at line 44 of file AnsiCParserDriver.h.
signatures
std::list<std::shared_ptr<Signature> > AnsiCParserDriver::signatures
Definition at line 42 of file AnsiCParserDriver.h.
symbols
std::list<std::shared_ptr<Symbol> > AnsiCParserDriver::symbols
Definition at line 43 of file AnsiCParserDriver.h.
trace_parsing
bool AnsiCParserDriver::trace_parsing private
Whether to generate parser debug traces.
Definition at line 53 of file AnsiCParserDriver.h.
Referenced by parse().
trace_scanning
bool AnsiCParserDriver::trace_scanning private
Whether to generate scanner debug traces.
Definition at line 54 of file AnsiCParserDriver.h.
Referenced by scanBegin().
The documentation for this class was generated from the following files:
AnsiCParserDriver.h
AnsiCParserDriver.cpp
AnsiCScanner.cpp