Boomerang: UsedLocsVisitor Class Reference
UsedLocsVisitor Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/stmtexpvisitor/UsedLocsVisitor.h>
Public Member Functions
UsedLocsVisitor (ExpVisitor *v, bool countCols)
bool visit (const std::shared_ptr< Assign > &stmt, bool &visitChildren) override
bool visit (const std::shared_ptr< BoolAssign > &stmt, bool &visitChildren) override
bool visit (const std::shared_ptr< CallStatement > &stmt, bool &visitChildren) override
bool visit (const std::shared_ptr< ImplicitAssign > &stmt, bool &visitChildren) override
bool visit (const std::shared_ptr< PhiAssign > &stmt, bool &visitChildren) override
bool visit (const std::shared_ptr< ReturnStatement > &stmt, bool &visitChildren) override
virtual ~UsedLocsVisitor ()=default
Private Attributes
bool m_countCols
True to count uses in collectors.
Detailed Description
Definition at line 19 of file UsedLocsVisitor.h.
Constructor & Destructor Documentation
UsedLocsVisitor()
UsedLocsVisitor::UsedLocsVisitor (ExpVisitor * v, bool countCols)
Definition at line 22 of file UsedLocsVisitor.cpp.
~UsedLocsVisitor()
virtual UsedLocsVisitor::~UsedLocsVisitor () virtual default
Member Function Documentation
visit() [1/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< Assign > & stmt, bool & visitChildren) override
Needs special attention because the lhs of an assignment isn't used (except where it's m[blah], when blah is used)
Definition at line 29 of file UsedLocsVisitor.cpp.
References UsedLocsFinder::isMemOnly(), opAt, UsedLocsFinder::setMemOnly(), and stmt.
visit() [2/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< BoolAssign > & stmt, bool & visitChildren) override
A BoolAssign uses its condition expression, but not its destination (unless it's an m[x], in which case x is used and not m[x])
Definition at line 188 of file UsedLocsVisitor.cpp.
References UsedLocsFinder::isMemOnly(), UsedLocsFinder::setMemOnly(), and stmt.
visit() [3/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< CallStatement > & stmt, bool & visitChildren) override
Returns aren't used (again, except where m[blah] where blah is used), and there is special logic for when the pass is final
Definition at line 139 of file UsedLocsVisitor.cpp.
References Assign, m_countCols, and stmt.
visit() [4/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< ImplicitAssign > & stmt, bool & visitChildren) override
Definition at line 111 of file UsedLocsVisitor.cpp.
References UsedLocsFinder::isMemOnly(), UsedLocsFinder::setMemOnly(), and stmt.
visit() [5/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< PhiAssign > & stmt, bool & visitChildren) override
Definition at line 72 of file UsedLocsVisitor.cpp.
References UsedLocsFinder::isMemOnly(), UsedLocsFinder::setMemOnly(), and stmt.
visit() [6/6]
bool UsedLocsVisitor::visit (const std::shared_ptr< ReturnStatement > & stmt, bool & visitChildren) override
Only consider the first return when final
Definition at line 168 of file UsedLocsVisitor.cpp.
References m_countCols, and stmt.
Member Data Documentation
m_countCols
bool UsedLocsVisitor::m_countCols private
True to count uses in collectors.
Definition at line 52 of file UsedLocsVisitor.h.
Referenced by visit().
The documentation for this class was generated from the following files:
UsedLocsVisitor.h
UsedLocsVisitor.cpp