Boomerang: CommandlineDriver Class Reference
CommandlineDriver Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang-cli/CommandlineDriver.h>
Public Slots
void onCompilationTimeout ()
Public Member Functions
int applyCommandline (const QStringList &args)
Apply the list of command line arguments to the Settings.
CommandlineDriver (QObject *parent=nullptr)
int decompile ()
Do the whole works - Load, decode, decompile and generate code for a binary file.
const Project * getProject () const
int interactiveMain ()
Displays a command line and processes the commands entered.
Private Member Functions
int decompile (const QString &fname, const QString &pname)
The program will be subsequently be loaded, decoded, decompiled and written to a source file.
bool loadAndDecode (const QString &fname, const QString &pname)
Loads the executable file and decodes it.
Private Attributes
std::unique_ptr< Console > m_console
QTimer m_kill_timer
QString m_pathToBinary
std::unique_ptr< Project > m_project
int minsToStopAfter = 0
Detailed Description
Definition at line 21 of file CommandlineDriver.h.
Constructor & Destructor Documentation
CommandlineDriver()
CommandlineDriver::CommandlineDriver (QObject * parent = nullptr) explicit
Definition at line 26 of file CommandlineDriver.cpp.
References onCompilationTimeout().
Member Function Documentation
applyCommandline()
int CommandlineDriver::applyCommandline (const QStringList & args)
Apply the list of command line arguments to the Settings.
Returns
Zero if the binary file can be decompiled, non-zero to exit the program.
Definition at line 104 of file CommandlineDriver.cpp.
References addr, Fatal, help(), interactiveMain(), LOG_MSG, m_kill_timer, m_pathToBinary, m_project, minsToStopAfter, and Verbose2.
Referenced by main().
decompile() [1/2]
int CommandlineDriver::decompile ()
Do the whole works - Load, decode, decompile and generate code for a binary file.
applyCommandline must be called first.
Definition at line 487 of file CommandlineDriver.cpp.
References m_pathToBinary, and m_project.
Referenced by main().
decompile() [2/2]
int CommandlineDriver::decompile (const QString & fname, const QString & pname) private
The program will be subsequently be loaded, decoded, decompiled and written to a source file.
After decompilation the elapsed time is printed to LOG_STREAM().
Parameters
fname The name of the file to load.
pname The name that will be given to the Proc.
Returns
Zero on success, nonzero on faillure.
Definition at line 525 of file CommandlineDriver.cpp.
References loadAndDecode(), LOG_MSG, and m_project.
getProject()
const Project* CommandlineDriver::getProject () const inline
Definition at line 52 of file CommandlineDriver.h.
References m_project.
interactiveMain()
int CommandlineDriver::interactiveMain ()
Displays a command line and processes the commands entered.
Return values
0 stdin was closed.
2 The user typed exit or quit.
Definition at line 454 of file CommandlineDriver.cpp.
References ExitProgram, m_console, and m_project.
Referenced by applyCommandline().
loadAndDecode()
bool CommandlineDriver::loadAndDecode (const QString & fname, const QString & pname) private
Loads the executable file and decodes it.
Parameters
fname The name of the file to load.
pname How the Prog will be named.
Definition at line 507 of file CommandlineDriver.cpp.
References LOG_ERROR, and m_project.
Referenced by decompile().
onCompilationTimeout
void CommandlineDriver::onCompilationTimeout () slot
Definition at line 500 of file CommandlineDriver.cpp.
References LOG_WARN.
Referenced by CommandlineDriver().
Member Data Documentation
m_console
std::unique_ptr<Console> CommandlineDriver::m_console private
Definition at line 78 of file CommandlineDriver.h.
Referenced by interactiveMain().
m_kill_timer
QTimer CommandlineDriver::m_kill_timer private
Definition at line 80 of file CommandlineDriver.h.
Referenced by applyCommandline().
m_pathToBinary
QString CommandlineDriver::m_pathToBinary private
Definition at line 82 of file CommandlineDriver.h.
Referenced by applyCommandline(), and decompile().
m_project
std::unique_ptr<Project> CommandlineDriver::m_project private
Definition at line 77 of file CommandlineDriver.h.
Referenced by applyCommandline(), decompile(), getProject(), interactiveMain(), and loadAndDecode().
minsToStopAfter
int CommandlineDriver::minsToStopAfter = 0 private
Definition at line 81 of file CommandlineDriver.h.
Referenced by applyCommandline().
The documentation for this class was generated from the following files:
CommandlineDriver.h
CommandlineDriver.cpp