Boomerang: UniqueStack< T > Class Template Reference
UniqueStack< T > Class Template Reference
Stack where each element is present at most once.
Public Member Functions
bool empty () const
void erase (T val)
T pop ()
void push (T val)
Private Attributes
std::deque< T > m_stack
Detailed Description
template<typename T>
class UniqueStack< T >
Stack where each element is present at most once.
Definition at line 27 of file CFGCompressor.cpp.
Member Function Documentation
empty()
template<typename T > bool UniqueStack< T >::empty () const inline
Definition at line 30 of file CFGCompressor.cpp.
References UniqueStack< T >::m_stack.
Referenced by CFGCompressor::compressFallthroughs().
erase()
template<typename T > void UniqueStack< T >::erase (T val) inline
Definition at line 47 of file CFGCompressor.cpp.
References UniqueStack< T >::m_stack.
Referenced by CFGCompressor::compressFallthroughs().
pop()
template<typename T > T UniqueStack< T >::pop () inline
Definition at line 32 of file CFGCompressor.cpp.
References UniqueStack< T >::m_stack.
Referenced by CFGCompressor::compressFallthroughs().
push()
template<typename T > void UniqueStack< T >::push (T val) inline
Definition at line 40 of file CFGCompressor.cpp.
References UniqueStack< T >::m_stack.
Referenced by CFGCompressor::compressFallthroughs().
Member Data Documentation
m_stack
template<typename T > std::deque<T> UniqueStack< T >::m_stack private
Definition at line 56 of file CFGCompressor.cpp.
Referenced by UniqueStack< T >::empty(), UniqueStack< T >::erase(), UniqueStack< T >::pop(), and UniqueStack< T >::push().
The documentation for this class was generated from the following file:
CFGCompressor.cpp