Boomerang: ExpSet< T, Sorter, Enabler > Class Template Reference
ExpSet< T, Sorter, Enabler > Class Template Reference
A class ordered or unordered sets of expressions.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/util/ExpSet.h>
Public Types
typedef Set::const_iterator const_iterator
typedef Set::iterator iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
void clear ()
bool contains (const std::shared_ptr< const T > &exp) const
Return true if the expression exists in the set.
bool empty () const
iterator end ()
const_iterator end () const
iterator erase (iterator ll)
Remove location, given iterator.
ExpSet ()=default
ExpSet (const ExpSet &o)
ExpSet (const std::initializer_list< std::shared_ptr< T >> &exps)
ExpSet (ExpSet &&)=default
void insert (const std::shared_ptr< T > &exp)
Insert the given expression.
void makeDiff (const ExpSet &other)
Make this set the set difference of itself and other.
void makeUnion (const ExpSet &other)
Make this set the union of itself and other.
bool operator!= (const ExpSet &other) const
ExpSet & operator= (const ExpSet &o)
ExpSet & operator= (ExpSet &&)=default
bool operator== (const ExpSet &other) const
void print (OStream &os) const
void remove (const std::shared_ptr< T > &loc)
int size () const
Protected Types
using Set = typename std::conditional< std::is_void< Sorter >::value, std::unordered_set< std::shared_ptr< T > >, std::set< std::shared_ptr< T >, Sorter > >::type
Protected Attributes
Set m_set
Detailed Description
template<typename T, typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>>
class ExpSet< T, Sorter, Enabler >
A class ordered or unordered sets of expressions.
Template Parameters
T the type of expression to store in the set
Sorter Binary functor type that defines the sorting order. If Sorter == void, the set is unordered.
Definition at line 29 of file ExpSet.h.
Member Typedef Documentation
const_iterator
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> typedef Set::const_iterator ExpSet< T, Sorter, Enabler >::const_iterator
Definition at line 38 of file ExpSet.h.
iterator
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> typedef Set::iterator ExpSet< T, Sorter, Enabler >::iterator
Definition at line 37 of file ExpSet.h.
Set
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> using ExpSet< T, Sorter, Enabler >::Set = typename std::conditional<std::is_void<Sorter>::value, std::unordered_set<std::shared_ptr<T> >, std::set<std::shared_ptr<T>, Sorter> >::type protected
Definition at line 34 of file ExpSet.h.
Constructor & Destructor Documentation
ExpSet() [1/4]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet< T, Sorter, Enabler >::ExpSet () default
ExpSet() [2/4]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet< T, Sorter, Enabler >::ExpSet (const std::initializer_list< std::shared_ptr< T >> & exps) inline
Definition at line 42 of file ExpSet.h.
ExpSet() [3/4]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet< T, Sorter, Enabler >::ExpSet (const ExpSet< T, Sorter, Enabler > & o) inline
Definition at line 47 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set, and o.
ExpSet() [4/4]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet< T, Sorter, Enabler >::ExpSet (ExpSet< T, Sorter, Enabler > &&) default
Member Function Documentation
begin() [1/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> iterator ExpSet< T, Sorter, Enabler >::begin () inline
Definition at line 83 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
Referenced by ExpSet< T, Sorter, Enabler >::operator==(), and ExpSet< T, Sorter, Enabler >::print().
begin() [2/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> const_iterator ExpSet< T, Sorter, Enabler >::begin () const inline
Definition at line 85 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
clear()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::clear () inline
Definition at line 91 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
contains()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> bool ExpSet< T, Sorter, Enabler >::contains (const std::shared_ptr< const T > & exp) const inline
Return true if the expression exists in the set.
Definition at line 110 of file ExpSet.h.
References exp, and ExpSet< T, Sorter, Enabler >::m_set.
empty()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> bool ExpSet< T, Sorter, Enabler >::empty () const inline
Definition at line 89 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
end() [1/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> iterator ExpSet< T, Sorter, Enabler >::end () inline
Definition at line 84 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
Referenced by ExpSet< T, Sorter, Enabler >::operator==(), ExpSet< T, Sorter, Enabler >::print(), and ExpSet< T, Sorter, Enabler >::remove().
end() [2/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> const_iterator ExpSet< T, Sorter, Enabler >::end () const inline
Definition at line 86 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
erase()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> iterator ExpSet< T, Sorter, Enabler >::erase (iterator ll) inline
Remove location, given iterator.
Definition at line 107 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
insert()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::insert (const std::shared_ptr< T > & exp) inline
Insert the given expression.
Definition at line 94 of file ExpSet.h.
References exp, and ExpSet< T, Sorter, Enabler >::m_set.
makeDiff()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::makeDiff (const ExpSet< T, Sorter, Enabler > & other) inline
Make this set the set difference of itself and other.
Definition at line 124 of file ExpSet.h.
References exp, and ExpSet< T, Sorter, Enabler >::m_set.
makeUnion()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::makeUnion (const ExpSet< T, Sorter, Enabler > & other) inline
Make this set the union of itself and other.
Definition at line 116 of file ExpSet.h.
References exp, and ExpSet< T, Sorter, Enabler >::m_set.
operator!=()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> bool ExpSet< T, Sorter, Enabler >::operator!= (const ExpSet< T, Sorter, Enabler > & other) const inline
Definition at line 68 of file ExpSet.h.
operator=() [1/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet& ExpSet< T, Sorter, Enabler >::operator= (const ExpSet< T, Sorter, Enabler > & o) inline
Definition at line 55 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set, and o.
operator=() [2/2]
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> ExpSet& ExpSet< T, Sorter, Enabler >::operator= (ExpSet< T, Sorter, Enabler > &&) default
operator==()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> bool ExpSet< T, Sorter, Enabler >::operator== (const ExpSet< T, Sorter, Enabler > & other) const inline
Definition at line 69 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::begin(), ExpSet< T, Sorter, Enabler >::end(), and ExpSet< T, Sorter, Enabler >::size().
print()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::print (OStream & os) const inline
Definition at line 131 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::begin(), and ExpSet< T, Sorter, Enabler >::end().
remove()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> void ExpSet< T, Sorter, Enabler >::remove (const std::shared_ptr< T > & loc) inline
Parameters
loc is not modified, and could be const'd if not for std::set requirements
Definition at line 97 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::end(), and ExpSet< T, Sorter, Enabler >::m_set.
size()
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> int ExpSet< T, Sorter, Enabler >::size () const inline
Definition at line 90 of file ExpSet.h.
References ExpSet< T, Sorter, Enabler >::m_set.
Referenced by ExpSet< T, Sorter, Enabler >::operator==().
Member Data Documentation
m_set
template<typename T , typename Sorter = void, typename Enabler = std::enable_if<std::is_base_of<Exp, T>::value>> Set ExpSet< T, Sorter, Enabler >::m_set protected
Definition at line 143 of file ExpSet.h.
Referenced by ExpSet< T, Sorter, Enabler >::begin(), ExpSet< T, Sorter, Enabler >::clear(), ExpSet< T, Sorter, Enabler >::contains(), ExpSet< T, Sorter, Enabler >::empty(), ExpSet< T, Sorter, Enabler >::end(), ExpSet< T, Sorter, Enabler >::erase(), ExpSet< T, Sorter, Enabler >::ExpSet(), ExpSet< T, Sorter, Enabler >::insert(), ExpSet< T, Sorter, Enabler >::makeDiff(), ExpSet< T, Sorter, Enabler >::makeUnion(), ExpSet< T, Sorter, Enabler >::operator=(), ExpSet< T, Sorter, Enabler >::remove(), and ExpSet< T, Sorter, Enabler >::size().
The documentation for this class was generated from the following file:
ExpSet.h