Boomerang: ControlFlowAnalyzer Class Reference
ControlFlowAnalyzer Class Reference
Control flow analysis stuff, lifted from Doug Simon's honours thesis.
#include </home/ceeac/Projects/code/boomerang/src/boomerang-plugins/codegen/c/ControlFlowAnalyzer.h>
Public Member Functions
ControlFlowAnalyzer ()
const IRFragment * getCaseHead (const IRFragment *frag) const
const IRFragment * getCondFollow (const IRFragment *frag) const
CondType getCondType (const IRFragment *frag) const
const IRFragment * getLatchNode (const IRFragment *frag) const
const IRFragment * getLoopFollow (const IRFragment *frag) const
const IRFragment * getLoopHead (const IRFragment *frag) const
LoopType getLoopType (const IRFragment *frag) const
StructType getStructType (const IRFragment *frag) const
TravType getTravType (const IRFragment *frag) const
UnstructType getUnstructType (const IRFragment *frag) const
bool isBackEdge (const IRFragment *source, const IRFragment *dest) const
establish if source has a back edge to dest
bool isCaseOption (const IRFragment *frag) const
bool isLatchNode (const IRFragment *frag) const
void setStructType (const IRFragment *frag, StructType s)
void setTravType (const IRFragment *frag, TravType type)
void structureCFG (ProcCFG *cfg)
Structures the control flow graph.
Private Member Functions
void checkConds ()
This routine is called after all the other structuring has been done.
void determineLoopType (const IRFragment *header, bool *&loopNodes)
const IRFragment * findCommonPDom (const IRFragment *curImmPDom, const IRFragment *succImmPDom)
Finds the common post dominator of the current immediate post dominator and its successor's immediate post dominator.
IRFragment * findEntryFragment () const
IRFragment * findExitFragment () const
void findLoopFollow (const IRFragment *header, bool *&loopNodes)
const IRFragment * getImmPDom (const IRFragment *frag) const
int getPostOrdering (const IRFragment *frag) const
int getRevOrd (const IRFragment *frag) const
bool hasBackEdge (const IRFragment *frag) const
establish if this fragment is the source of any back edges leading FROM it
bool isAncestorOf (const IRFragment *frag, const IRFragment *other) const
bool isFragInLoop (const IRFragment *frag, const IRFragment *header, const IRFragment *latch) const
void setCaseHead (const IRFragment *frag, const IRFragment *head, const IRFragment *follow)
void setCondFollow (const IRFragment *frag, const IRFragment *follow)
void setCondType (const IRFragment *frag, CondType condType)
void setImmPDom (const IRFragment *frag, const IRFragment *immPDom)
void setLatchNode (const IRFragment *frag, const IRFragment *latch)
void setLoopFollow (const IRFragment *frag, const IRFragment *follow)
void setLoopHead (const IRFragment *frag, const IRFragment *head)
void setLoopType (const IRFragment *frag, LoopType loopType)
void setTimeStamps ()
void setUnstructType (const IRFragment *frag, UnstructType unstructType)
void structConds ()
Structures all conditional headers (i.e. nodes with more than one outedge)
void structLoops ()
void tagNodesInLoop (const IRFragment *header, bool *&loopNodes)
void unTraverse ()
void updateImmedPDom ()
Finds the immediate post dominator of each node in the CFG.
void updateLoopStamps (const IRFragment *frag, int &time)
void updateRevLoopStamps (const IRFragment *frag, int &time)
void updateRevOrder (const IRFragment *frag)
Private Attributes
ProcCFG * m_cfg = nullptr
std::unordered_map< const IRFragment *, FragStructInfo > m_info
mutable to allow using the map in const methods (might create entries).
std::vector< const IRFragment * > m_postOrdering
Post Ordering according to a DFS starting at the entry fragment.
std::vector< const IRFragment * > m_revPostOrdering
Post Ordering according to a DFS starting at the exit fragment (usually the return fragment).
Detailed Description
Control flow analysis stuff, lifted from Doug Simon's honours thesis.
Analyzes the control flow of a CFG and tags loop constructs etc.
Definition at line 133 of file ControlFlowAnalyzer.h.
Constructor & Destructor Documentation
ControlFlowAnalyzer()
ControlFlowAnalyzer::ControlFlowAnalyzer ()
Definition at line 24 of file ControlFlowAnalyzer.cpp.
Member Function Documentation
checkConds()
void ControlFlowAnalyzer::checkConds () private
This routine is called after all the other structuring has been done.
It detects conditionals that are in fact the head of a jump into/outof a loop or into a case body. Only forward jumps are considered as unstructured backward jumps will always be generated nicely.
Definition at line 400 of file ControlFlowAnalyzer.cpp.
References BELSE, BTHEN, Case, Cond, getCaseHead(), getCondFollow(), getCondType(), getLoopHead(), getStructType(), getUnstructType(), hasBackEdge(), IfElse, IfThen, isBackEdge(), JumpInOutLoop, JumpIntoCase, LoopCond, m_postOrdering, setCondFollow(), setCondType(), setUnstructType(), and Structured.
Referenced by structureCFG().
determineLoopType()
void ControlFlowAnalyzer::determineLoopType (const IRFragment * header, bool *& loopNodes) private
Precondition
The loop induced by (head,latch) has already had all its member nodes tagged
Postcondition
The type of loop has been deduced
Definition at line 184 of file ControlFlowAnalyzer.cpp.
References Endless, getCondFollow(), getLatchNode(), getPostOrdering(), LoopCond, PostTested, PreTested, setLoopType(), setStructType(), and Twoway.
Referenced by structLoops().
findCommonPDom()
const IRFragment * ControlFlowAnalyzer::findCommonPDom (const IRFragment * curImmPDom, const IRFragment * succImmPDom) private
Finds the common post dominator of the current immediate post dominator and its successor's immediate post dominator.
Definition at line 110 of file ControlFlowAnalyzer.cpp.
References getImmPDom(), getRevOrd(), GIVEUP, and LOG_VERBOSE.
Referenced by updateImmedPDom().
findEntryFragment()
IRFragment * ControlFlowAnalyzer::findEntryFragment () const private
Definition at line 743 of file ControlFlowAnalyzer.cpp.
References m_cfg.
Referenced by setTimeStamps().
findExitFragment()
IRFragment * ControlFlowAnalyzer::findExitFragment () const private
Definition at line 749 of file ControlFlowAnalyzer.cpp.
References m_cfg.
Referenced by setTimeStamps().
findLoopFollow()
void ControlFlowAnalyzer::findLoopFollow (const IRFragment * header, bool *& loopNodes) private
Precondition
The loop headed by header has been induced and all it's member nodes have been tagged
Postcondition
The follow of the loop has been determined.
Definition at line 220 of file ControlFlowAnalyzer.cpp.
References BELSE, BTHEN, Cond, getCondFollow(), getLatchNode(), getLoopHead(), getLoopType(), getPostOrdering(), getStructType(), Loop, LoopCond, m_postOrdering, PostTested, PreTested, and setLoopFollow().
Referenced by structLoops().
getCaseHead()
const IRFragment* ControlFlowAnalyzer::getCaseHead (const IRFragment * frag) const inline
Definition at line 176 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by checkConds(), isCaseOption(), setCaseHead(), and structLoops().
getCondFollow()
const IRFragment* ControlFlowAnalyzer::getCondFollow (const IRFragment * frag) const inline
Definition at line 171 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by checkConds(), determineLoopType(), findLoopFollow(), setCaseHead(), setStructType(), and structConds().
getCondType()
CondType ControlFlowAnalyzer::getCondType (const IRFragment * frag) const
Definition at line 696 of file ControlFlowAnalyzer.cpp.
References Cond, getStructType(), LoopCond, and m_info.
Referenced by checkConds(), and structConds().
getImmPDom()
const IRFragment* ControlFlowAnalyzer::getImmPDom (const IRFragment * frag) const inline private
Definition at line 236 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by findCommonPDom(), structConds(), and updateImmedPDom().
getLatchNode()
const IRFragment* ControlFlowAnalyzer::getLatchNode (const IRFragment * frag) const inline
Definition at line 156 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by determineLoopType(), findLoopFollow(), isFragInLoop(), isLatchNode(), setLoopType(), structLoops(), and tagNodesInLoop().
getLoopFollow()
const IRFragment* ControlFlowAnalyzer::getLoopFollow (const IRFragment * frag) const inline
Definition at line 166 of file ControlFlowAnalyzer.h.
References m_info.
getLoopHead()
const IRFragment* ControlFlowAnalyzer::getLoopHead (const IRFragment * frag) const inline
Definition at line 161 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by checkConds(), findLoopFollow(), isLatchNode(), and structLoops().
getLoopType()
LoopType ControlFlowAnalyzer::getLoopType (const IRFragment * frag) const
Definition at line 682 of file ControlFlowAnalyzer.cpp.
References getStructType(), Loop, LoopCond, and m_info.
Referenced by findLoopFollow().
getPostOrdering()
int ControlFlowAnalyzer::getPostOrdering (const IRFragment * frag) const inline private
Definition at line 233 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by determineLoopType(), findLoopFollow(), structLoops(), tagNodesInLoop(), and updateImmedPDom().
getRevOrd()
int ControlFlowAnalyzer::getRevOrd (const IRFragment * frag) const inline private
Definition at line 234 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by findCommonPDom(), and updateImmedPDom().
getStructType()
StructType ControlFlowAnalyzer::getStructType (const IRFragment * frag) const inline
Definition at line 182 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by checkConds(), findLoopFollow(), getCondType(), getLoopType(), setCondType(), setLoopType(), and structLoops().
getTravType()
TravType ControlFlowAnalyzer::getTravType (const IRFragment * frag) const inline
Definition at line 181 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by setCaseHead(), updateLoopStamps(), updateRevLoopStamps(), and updateRevOrder().
getUnstructType()
UnstructType ControlFlowAnalyzer::getUnstructType (const IRFragment * frag) const
Definition at line 657 of file ControlFlowAnalyzer.cpp.
References Cond, LoopCond, and m_info.
Referenced by checkConds().
hasBackEdge()
bool ControlFlowAnalyzer::hasBackEdge (const IRFragment * frag) const private
establish if this fragment is the source of any back edges leading FROM it
Definition at line 728 of file ControlFlowAnalyzer.cpp.
Referenced by checkConds(), and structConds().
isAncestorOf()
bool ControlFlowAnalyzer::isAncestorOf (const IRFragment * frag, const IRFragment * other) const private
Returns
true if frag is an ancestor of other
Definition at line 516 of file ControlFlowAnalyzer.cpp.
References m_info.
Referenced by isBackEdge().
isBackEdge()
bool ControlFlowAnalyzer::isBackEdge (const IRFragment * source, const IRFragment * dest) const
establish if source has a back edge to dest
Definition at line 494 of file ControlFlowAnalyzer.cpp.
References isAncestorOf().
Referenced by checkConds(), setCaseHead(), structLoops(), and updateImmedPDom().
isCaseOption()
bool ControlFlowAnalyzer::isCaseOption (const IRFragment * frag) const
Definition at line 500 of file ControlFlowAnalyzer.cpp.
References getCaseHead().
isFragInLoop()
bool ControlFlowAnalyzer::isFragInLoop (const IRFragment * frag, const IRFragment * header, const IRFragment * latch) const private
Definition at line 703 of file ControlFlowAnalyzer.cpp.
References getLatchNode(), and m_info.
Referenced by tagNodesInLoop().
isLatchNode()
bool ControlFlowAnalyzer::isLatchNode (const IRFragment * frag) const inline
Definition at line 146 of file ControlFlowAnalyzer.h.
References getLatchNode(), and getLoopHead().
setCaseHead()
void ControlFlowAnalyzer::setCaseHead (const IRFragment * frag, const IRFragment * head, const IRFragment * follow) private
Definition at line 590 of file ControlFlowAnalyzer.cpp.
References DFS_Case, getCaseHead(), getCondFollow(), getTravType(), isBackEdge(), m_info, Nway, and setTravType().
Referenced by structConds().
setCondFollow()
void ControlFlowAnalyzer::setCondFollow (const IRFragment * frag, const IRFragment * follow) inline private
Definition at line 220 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by checkConds(), and structConds().
setCondType()
void ControlFlowAnalyzer::setCondType (const IRFragment * frag, CondType condType) private
Definition at line 689 of file ControlFlowAnalyzer.cpp.
References Cond, getStructType(), LoopCond, and m_info.
Referenced by checkConds().
setImmPDom()
void ControlFlowAnalyzer::setImmPDom (const IRFragment * frag, const IRFragment * immPDom) inline private
Definition at line 238 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by updateImmedPDom().
setLatchNode()
void ControlFlowAnalyzer::setLatchNode (const IRFragment * frag, const IRFragment * latch) inline private
Definition at line 204 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by structLoops().
setLoopFollow()
void ControlFlowAnalyzer::setLoopFollow (const IRFragment * frag, const IRFragment * follow) inline private
Definition at line 215 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by findLoopFollow().
setLoopHead()
void ControlFlowAnalyzer::setLoopHead (const IRFragment * frag, const IRFragment * head) inline private
Definition at line 200 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by tagNodesInLoop().
setLoopType()
void ControlFlowAnalyzer::setLoopType (const IRFragment * frag, LoopType loopType) private
Definition at line 668 of file ControlFlowAnalyzer.cpp.
References getLatchNode(), getStructType(), Loop, LoopCond, m_info, PostTested, PreTested, and setStructType().
Referenced by determineLoopType().
setStructType()
void ControlFlowAnalyzer::setStructType (const IRFragment * frag, StructType s)
Definition at line 625 of file ControlFlowAnalyzer.cpp.
References BELSE, BTHEN, Case, Cond, getCondFollow(), IfElse, IfThen, IfThenElse, m_info, and Nway.
Referenced by determineLoopType(), setLoopType(), structConds(), and structLoops().
setTimeStamps()
void ControlFlowAnalyzer::setTimeStamps () private
Definition at line 48 of file ControlFlowAnalyzer.cpp.
References findEntryFragment(), findExitFragment(), m_postOrdering, m_revPostOrdering, updateLoopStamps(), updateRevLoopStamps(), and updateRevOrder().
Referenced by structureCFG().
setTravType()
void ControlFlowAnalyzer::setTravType (const IRFragment * frag, TravType type) inline
Definition at line 190 of file ControlFlowAnalyzer.h.
References m_info.
Referenced by setCaseHead(), updateLoopStamps(), updateRevLoopStamps(), and updateRevOrder().
setUnstructType()
void ControlFlowAnalyzer::setUnstructType (const IRFragment * frag, UnstructType unstructType) private
Definition at line 648 of file ControlFlowAnalyzer.cpp.
References Case, Cond, LoopCond, and m_info.
Referenced by checkConds().
structConds()
void ControlFlowAnalyzer::structConds () private
Structures all conditional headers (i.e. nodes with more than one outedge)
Definition at line 153 of file ControlFlowAnalyzer.cpp.
References Case, Cond, getCondFollow(), getCondType(), getImmPDom(), hasBackEdge(), m_postOrdering, setCaseHead(), setCondFollow(), setStructType(), and Twoway.
Referenced by structureCFG().
structLoops()
void ControlFlowAnalyzer::structLoops () private
Precondition
The graph for curProc has been built.
Postcondition
Each node is tagged with the header of the most nested loop of which it is a member (possibly none). The header of each loop stores information on the latching node as well as the type of loop it heads.
Definition at line 335 of file ControlFlowAnalyzer.cpp.
References Cond, determineLoopType(), findLoopFollow(), getCaseHead(), getLatchNode(), getLoopHead(), getPostOrdering(), getStructType(), isBackEdge(), Loop, m_postOrdering, Seq, setLatchNode(), setStructType(), and tagNodesInLoop().
Referenced by structureCFG().
structureCFG()
void ControlFlowAnalyzer::structureCFG (ProcCFG * cfg)
Structures the control flow graph.
Definition at line 29 of file ControlFlowAnalyzer.cpp.
References checkConds(), m_cfg, setTimeStamps(), structConds(), structLoops(), unTraverse(), and updateImmedPDom().
tagNodesInLoop()
void ControlFlowAnalyzer::tagNodesInLoop (const IRFragment * header, bool *& loopNodes) private
Precondition
header has been detected as a loop header and has the details of the latching node
Postcondition
the nodes within the loop have been tagged
Definition at line 309 of file ControlFlowAnalyzer.cpp.
References getLatchNode(), getPostOrdering(), isFragInLoop(), m_postOrdering, and setLoopHead().
Referenced by structLoops().
unTraverse()
void ControlFlowAnalyzer::unTraverse () private
Definition at line 735 of file ControlFlowAnalyzer.cpp.
References m_info, and Untraversed.
Referenced by structureCFG().
updateImmedPDom()
void ControlFlowAnalyzer::updateImmedPDom () private
Finds the immediate post dominator of each node in the CFG.
Adapted version of the dominators algorithm by Hecht and Ullman; finds immediate post dominators only.
Note
graph should be reducible
Definition at line 68 of file ControlFlowAnalyzer.cpp.
References findCommonPDom(), getImmPDom(), getPostOrdering(), getRevOrd(), isBackEdge(), m_postOrdering, m_revPostOrdering, and setImmPDom().
Referenced by structureCFG().
updateLoopStamps()
void ControlFlowAnalyzer::updateLoopStamps (const IRFragment * frag, int & time) private
Definition at line 525 of file ControlFlowAnalyzer.cpp.
References DFS_LNum, getTravType(), m_info, m_postOrdering, and setTravType().
Referenced by setTimeStamps().
updateRevLoopStamps()
void ControlFlowAnalyzer::updateRevLoopStamps (const IRFragment * frag, int & time) private
Definition at line 553 of file ControlFlowAnalyzer.cpp.
References DFS_RNum, getTravType(), m_info, and setTravType().
Referenced by setTimeStamps().
updateRevOrder()
void ControlFlowAnalyzer::updateRevOrder (const IRFragment * frag) private
Definition at line 571 of file ControlFlowAnalyzer.cpp.
References DFS_PDom, getTravType(), m_info, m_revPostOrdering, and setTravType().
Referenced by setTimeStamps().
Member Data Documentation
m_cfg
ProcCFG* ControlFlowAnalyzer::m_cfg = nullptr private
Definition at line 292 of file ControlFlowAnalyzer.h.
Referenced by findEntryFragment(), findExitFragment(), and structureCFG().
m_info
std::unordered_map<const IRFragment *, FragStructInfo> ControlFlowAnalyzer::m_info mutable private
mutable to allow using the map in const methods (might create entries).
DO NOT change FragStructInfo in const methods!
Definition at line 305 of file ControlFlowAnalyzer.h.
Referenced by getCaseHead(), getCondFollow(), getCondType(), getImmPDom(), getLatchNode(), getLoopFollow(), getLoopHead(), getLoopType(), getPostOrdering(), getRevOrd(), getStructType(), getTravType(), getUnstructType(), isAncestorOf(), isFragInLoop(), setCaseHead(), setCondFollow(), setCondType(), setImmPDom(), setLatchNode(), setLoopFollow(), setLoopHead(), setLoopType(), setStructType(), setTravType(), setUnstructType(), unTraverse(), updateLoopStamps(), updateRevLoopStamps(), and updateRevOrder().
m_postOrdering
std::vector<const IRFragment *> ControlFlowAnalyzer::m_postOrdering private
Post Ordering according to a DFS starting at the entry fragment.
Definition at line 295 of file ControlFlowAnalyzer.h.
Referenced by checkConds(), findLoopFollow(), setTimeStamps(), structConds(), structLoops(), tagNodesInLoop(), updateImmedPDom(), and updateLoopStamps().
m_revPostOrdering
std::vector<const IRFragment *> ControlFlowAnalyzer::m_revPostOrdering private
Post Ordering according to a DFS starting at the exit fragment (usually the return fragment).
Note that this is not the reverse of m_postOrdering for functions containing calls to noreturn functions or infinite loops.
Definition at line 300 of file ControlFlowAnalyzer.h.
Referenced by setTimeStamps(), updateImmedPDom(), and updateRevOrder().
The documentation for this class was generated from the following files:
ControlFlowAnalyzer.h
ControlFlowAnalyzer.cpp