Boomerang: RTLEditor Class Reference
RTLEditor Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang-gui/RTLEditor.h>
Public Slots
void updateContents ()
Public Member Functions
RTLEditor (Decompiler *decompiler, const QString &name)
Private Attributes
Decompiler * decompiler
QString name
Detailed Description
Definition at line 26 of file RTLEditor.h.
Constructor & Destructor Documentation
RTLEditor()
RTLEditor::RTLEditor (Decompiler * decompiler, const QString & name)
Definition at line 19 of file RTLEditor.cpp.
References updateContents().
Member Function Documentation
updateContents
void RTLEditor::updateContents () slot
Definition at line 30 of file RTLEditor.cpp.
References decompiler, Decompiler::getRTLForProc(), and name.
Referenced by RTLEditor(), and MainWindow::showRTLEditor().
Member Data Documentation
decompiler
Decompiler* RTLEditor::decompiler private
Definition at line 37 of file RTLEditor.h.
Referenced by updateContents().
name
QString RTLEditor::name private
Definition at line 38 of file RTLEditor.h.
Referenced by updateContents().
The documentation for this class was generated from the following files:
RTLEditor.h
RTLEditor.cpp