Boomerang: StmtSSAXformer Class Reference
StmtSSAXformer Class Reference
#include </home/ceeac/Projects/code/boomerang/src/boomerang/visitor/stmtmodifier/StmtSSAXFormer.h>
Public Member Functions
void handleCommonLHS (const std::shared_ptr< Assignment > &stmt)
Common code for the left hand side of assignments.
StmtSSAXformer (ExpSSAXformer *esx, UserProc *proc)
void visit (const std::shared_ptr< Assign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< BoolAssign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< CallStatement > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< ImplicitAssign > &stmt, bool &visitChildren) override
void visit (const std::shared_ptr< PhiAssign > &stmt, bool &visitChildren) override
virtual ~StmtSSAXformer ()=default
Private Attributes
UserProc * m_proc
Detailed Description
Definition at line 24 of file StmtSSAXFormer.h.
Constructor & Destructor Documentation
StmtSSAXformer()
StmtSSAXformer::StmtSSAXformer (ExpSSAXformer * esx, UserProc * proc)
Definition at line 26 of file StmtSSAXFormer.cpp.
~StmtSSAXformer()
virtual StmtSSAXformer::~StmtSSAXformer () virtual default
Member Function Documentation
handleCommonLHS()
void StmtSSAXformer::handleCommonLHS (const std::shared_ptr< Assignment > & stmt)
Common code for the left hand side of assignments.
Definition at line 33 of file StmtSSAXFormer.cpp.
References m_proc.
Referenced by visit().
visit() [1/5]
void StmtSSAXformer::visit (const std::shared_ptr< Assign > & stmt, bool & visitChildren) override
Definition at line 57 of file StmtSSAXFormer.cpp.
References handleCommonLHS(), and stmt.
visit() [2/5]
void StmtSSAXformer::visit (const std::shared_ptr< BoolAssign > & stmt, bool & visitChildren) override
Definition at line 47 of file StmtSSAXFormer.cpp.
References handleCommonLHS(), and stmt.
visit() [3/5]
void StmtSSAXformer::visit (const std::shared_ptr< CallStatement > & stmt, bool & visitChildren) override
Definition at line 94 of file StmtSSAXFormer.cpp.
References ExpSSAXformer::getProc(), LOG_WARN, and stmt.
visit() [4/5]
void StmtSSAXformer::visit (const std::shared_ptr< ImplicitAssign > & stmt, bool & visitChildren) override
Definition at line 67 of file StmtSSAXFormer.cpp.
References handleCommonLHS(), and stmt.
visit() [5/5]
void StmtSSAXformer::visit (const std::shared_ptr< PhiAssign > & stmt, bool & visitChildren) override
Definition at line 74 of file StmtSSAXFormer.cpp.
References handleCommonLHS(), and stmt.
Member Data Documentation
m_proc
UserProc* StmtSSAXformer::m_proc private
Definition at line 50 of file StmtSSAXFormer.h.
Referenced by handleCommonLHS().
The documentation for this class was generated from the following files:
StmtSSAXFormer.h
StmtSSAXFormer.cpp