Boomerang: BlockVarRenamePass Class Reference
BlockVarRenamePass Class Reference final
Rewrites Statements in BasicBlocks into SSA form.
#include </home/ceeac/Projects/code/boomerang/src/boomerang/passes/dataflow/BlockVarRenamePass.h>
Public Member Functions
BlockVarRenamePass ()
bool execute (UserProc *proc) override
Run this pass, updating proc.
Public Member Functions inherited from IPass
const QString & getName () const
PassID getType () const
IPass (const QString &name, PassID type)
virtual bool isProcLocal () const
virtual ~IPass ()=default
Private Member Functions
void popDefinitions (SharedStmt stmt, bool assumeABI)
pop definitions in this statement from the stacks
void pushDefinitions (SharedStmt stmt, bool assumeABI)
push definitions in this statement onto the stacks
bool renameBlockVars (UserProc *proc, std::size_t n)
bool subscriptUsedLocations (SharedStmt stmt)
void subscriptVar (const SharedStmt &stmt, SharedExp var, const SharedStmt &varDef)
For all expressions in stmt, replace var with var{varDef}.
Private Attributes
std::map< SharedExp, std::stack< SharedStmt >, lessExpStar > stacks
stores the last definition of a variable
Detailed Description
Rewrites Statements in BasicBlocks into SSA form.
Definition at line 22 of file BlockVarRenamePass.h.
Constructor & Destructor Documentation
BlockVarRenamePass()
BlockVarRenamePass::BlockVarRenamePass ()
Definition at line 39 of file BlockVarRenamePass.cpp.
References BlockVarRename.
Member Function Documentation
execute()
bool BlockVarRenamePass::execute (UserProc * proc) override virtual
Run this pass, updating proc.
Returns
true iff any change
The stack which remembers the last definition of an expression.
Implements IPass.
Definition at line 45 of file BlockVarRenamePass.cpp.
References renameBlockVars(), and stacks.
popDefinitions()
void BlockVarRenamePass::popDefinitions (SharedStmt stmt, bool assumeABI) private
pop definitions in this statement from the stacks
Definition at line 329 of file BlockVarRenamePass.cpp.
References LOG_FATAL, stacks, and stmt.
Referenced by renameBlockVars().
pushDefinitions()
void BlockVarRenamePass::pushDefinitions (SharedStmt stmt, bool assumeABI) private
push definitions in this statement onto the stacks
Definition at line 275 of file BlockVarRenamePass.cpp.
References a, defineAll, stacks, and stmt.
Referenced by renameBlockVars().
renameBlockVars()
bool BlockVarRenamePass::renameBlockVars (UserProc * proc, std::size_t n) private
Definition at line 68 of file BlockVarRenamePass.cpp.
References a, PhiAssign, popDefinitions(), pushDefinitions(), stacks, STACKS_EMPTY, stmt, and subscriptUsedLocations().
Referenced by execute().
subscriptUsedLocations()
bool BlockVarRenamePass::subscriptUsedLocations (SharedStmt stmt) private
Definition at line 188 of file BlockVarRenamePass.cpp.
References defineAll, PhiAssign, stacks, STACKS_EMPTY, stmt, and subscriptVar().
Referenced by renameBlockVars().
subscriptVar()
void BlockVarRenamePass::subscriptVar (const SharedStmt & stmt, SharedExp var, const SharedStmt & varDef) private
For all expressions in stmt, replace var with var{varDef}.
Definition at line 178 of file BlockVarRenamePass.cpp.
References stmt.
Referenced by subscriptUsedLocations().
Member Data Documentation
stacks
std::map<SharedExp, std::stack<SharedStmt>, lessExpStar> BlockVarRenamePass::stacks private
stores the last definition of a variable
Definition at line 47 of file BlockVarRenamePass.h.
Referenced by execute(), popDefinitions(), pushDefinitions(), renameBlockVars(), and subscriptUsedLocations().
The documentation for this class was generated from the following files:
BlockVarRenamePass.h
BlockVarRenamePass.cpp