Boomerang: Register.h File Reference
Register.h File Reference
#include "boomerang/core/BoomerangAPI.h"
#include "boomerang/util/Types.h"
#include <QString>
#include <memory>
#include <string>
#include <type_traits>
Typedefs
typedef uint16 RegNum
typedef std::shared_ptr< Type > SharedType
Enumerations
enum RegType { RegType::Invalid = 0, RegType::Int = 1, RegType::Float = 2, RegType::Flags = 3 }
Functions
class __attribute__ ((visibility("default"))) Register
Summarises one line of the @REGISTERS section of an SSL file.
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>>
bool operator!= (const RegID &lhs, T rhs)
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>>
bool operator!= (T lhs, const RegID &rhs)
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>>
bool operator== (const RegID &lhs, T rhs)
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>>
bool operator== (T lhs, const RegID &rhs)
Variables
static constexpr const RegID RegIDSpecial = RegID(RegType::Invalid, RegNumSpecial, 0)
static constexpr const RegNum RegNumSpecial = 0xFFFF
Typedef Documentation
RegNum
typedef uint16 RegNum
Definition at line 27 of file Register.h.
SharedType
typedef std::shared_ptr<Type> SharedType
Definition at line 23 of file Register.h.
Enumeration Type Documentation
RegType
enum RegType strong
Enumerator
Invalid
Int
Float
Flags
Definition at line 29 of file Register.h.
Function Documentation
__attribute__()
class __attribute__ ((visibility("default")))
Summarises one line of the @REGISTERS section of an SSL file.
This class is used extensively in sslparser.y.
Returns
the type of the content of this register
the type of the register(int, float, flags)
Definition at line 38 of file Register.h.
References operator!=(), and operator==().
operator!=() [1/2]
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>> bool operator!= (const RegID & lhs, T rhs)
Definition at line 71 of file Register.h.
Referenced by __attribute__().
operator!=() [2/2]
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>> bool operator!= (T lhs, const RegID & rhs)
Definition at line 76 of file Register.h.
operator==() [1/2]
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>> bool operator== (const RegID & lhs, T rhs)
Definition at line 69 of file Register.h.
Referenced by __attribute__().
operator==() [2/2]
template<typename T , typename Enabler = std::enable_if<!std::is_same<T, RegID>::value>> bool operator== (T lhs, const RegID & rhs)
Definition at line 74 of file Register.h.
Variable Documentation
RegIDSpecial
constexpr const RegID RegIDSpecial = RegID(RegType::Invalid, RegNumSpecial, 0) static constexpr
Definition at line 81 of file Register.h.
RegNumSpecial
constexpr const RegNum RegNumSpecial = 0xFFFF static constexpr
Definition at line 80 of file Register.h.
Referenced by fixRegNum().