Boomerang: SSL2ParserDriver.h File Reference
SSL2ParserDriver.h File Reference
#include "SSL2Parser.hpp"
#include "boomerang/ssl/Register.h"
#include <map>
#include <string>
Classes
class SSL2ParserDriver
Class for parsing an SSL specification file.
Macros
#define YY_DECL SSL2::parser::symbol_type SSL2lex(SSL2ParserDriver &drv)
Functions
SSL2::parser::symbol_type SSL2lex (SSL2ParserDriver &drv)
The main scanner function which does all the work.
Macro Definition Documentation
YY_DECL
#define YY_DECL SSL2::parser::symbol_type SSL2lex(SSL2ParserDriver &drv)
Definition at line 22 of file SSL2ParserDriver.h.
Function Documentation
SSL2lex()
SSL2::parser::symbol_type SSL2lex (SSL2ParserDriver & drv)
The main scanner function which does all the work.
Definition at line 1329 of file SSL2Scanner.cpp.
References ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, INITIAL, yy_accept, yy_base, YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_c_buf_p, yy_chk, yy_create_buffer, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_def, yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_flex_debug, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_init, yy_last_accepting_cpos, yy_last_accepting_state, yy_load_buffer_state, yy_meta, YY_MORE_ADJ, yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyensure_buffer_stack, yyin, yyleng, yyout, yytext, yytext_ptr, and yywrap.